### ISSUE TITLE
Disable swipe events

### ISSUE THREAD

**Issue by cjke** [xiaolin/react-image-gallery#100]
Hi, first, excellent library, thanks.

Would it be possible to add a prop that allows the swipe events to be switched on/off?

Perhaps around the following line, do a check if `enableSwipe` is true, and if not, don't wrap the `image-gallery-slides` in the Swipeable component:
https://github.com/xiaolin/react-image-gallery/blob/3e0ebcce3eebe982d5653cd28db22a71224d052f/src/ImageGallery.jsx#L748

For context - our project is using https://github.com/fengyuanchen/cropperjs within react-image-gallery and the swipe events interfere with the cropping tool. Otherwise, the two work surprisingly well together. 

Cheers

**Comment by xiaolin** [comment]
Sure this seems simple enough.

**Comment by cjke** [comment]
Thanks @xiaolin !

**Comment by xiaolin** [comment]
released in v0.7.2
