### ISSUE TITLE
Multiple image gallery in a same page

### ISSUE THREAD

**Issue by iiitmanikanta** [xiaolin/react-image-gallery#101]
when ther is multiple image gallery's in one page and if we click Arrow right to scrool image in a one image gallery , all the images in remaining gallery's are also moving,
same thing happens for the full screen option too. all gallery's images are opeing in full screen.

how to restrict each one functionality ???

**Comment by xiaolin** [comment]
Can you show me how you are rendering the `ImageGallery`?

**Comment by iiitmanikanta** [comment]
return (
      <ImageGallery
        onScreenChange={this.fullscreenElement}
        lazyLoad={false}
        showIndex
        indexSeparator=' / '
        showThumbnails={false}
        defaultImage={NoImageAvailable}
        showPlayButton={false}
        items={images}
        slideInterval={1500}
        onImageLoad={this.handleImageLoad} />
    )

i kept this in one component and i am calling the same component multiple times in another component

**Comment by xiaolin** [comment]
I'm not able to replicate your issue. I did,

```jsx
const Gallery = () => {
  const images = [
    {
      original: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=800&h=600',
      thumbnail: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=150&h=100'
    },
    {
      original: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=800&h=600',
      thumbnail: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=150&h=100'
    },
    {
      original: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=800&h=600',
      thumbnail: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=150&h=100'
    }
  ];
  return (
    <ImageGallery
      items={images}/>
  );
};

class MyApp extends React.Component {
    return (
      <div>
        {
          [1, 2, 3, 4].map((key) => {
            return <Gallery key={key}/>;
          })
        }
      </div>
    );
}
```

**Comment by OZZlE** [comment]
@xiaolin "when there are **multiple** image gallery's" on the same page, your test case has **one** <ImageGallery> component.

I have the same issue, I implemented a lightbox when clicking an image from the gallery, opening another gallery with the same items and then you can zoom those images as well. However the zoom is now acting on both image gallerys, I have no shared logic in my code related to the TWO gallerys.

Test case should be something like:

    const Gallery = () => {
      const images = [
        {
          original: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=800&h=600',
          thumbnail: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=150&h=100'
        },
        {
          original: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=800&h=600',
          thumbnail: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=150&h=100'
        },
        {
          original: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=800&h=600',
          thumbnail: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=150&h=100'
        }
      ];
      return (
        <div>
            <ImageGallery items={images} key=1 />
            <ImageGallery items={images} key=2 />
        </div>
      );
    };

    class MyApp extends React.Component {
        return (
          <div>
            {
              [1, 2, 3, 4].map((key) => {
                return <Gallery key={key}/>;
              })
            }
          </div>
        );
    }

**Comment by tsotneguti** [comment]
@xiaolin I have same problem. If I have multiple instances of Gallery on the screen (not rendered using array) and I click arrow left button, it affects both galleries
