### ISSUE TITLE
Fullscreen support on iOS 

### ISSUE THREAD

**Issue by jadonald72** [xiaolin/react-image-gallery#103]
I am using onScreenChange prop to call a script on my page, but iOS never calls this, fine on Android.  From what I can see the prop onScreenChange has no value.  

Also, when I do click on the fullscreen icon, the image doesn't go totally fullscreen.  I still see a header and footer.  I am building a hybrid app.  Perhaps a CSS issue?

After doing some research I have found that the Fullscreen API doesn't seem to be supported by mobile devices using iOS.  So, I am now asking myself should I still use this plugin if it doesn't work correctly on iOS mobile devices?

**Comment by xiaolin** [comment]
Right fullscreen API is currently not supported on most mobile devices. This is why I'm using a css solution when there is no fullscreen API supported.

I took a look and realize `onScreenChange ` does not return any values for unsupported devices, so thats a bug that will be fix soon #104.

Can you show me a screenshot of it not going totally fullscreen? Its probably css which you can adjust.

**Comment by jadonald72** [comment]
![property_details](https://cloud.githubusercontent.com/assets/10462983/19117021/7b263376-8b0f-11e6-94cd-aaa2bcfbead3.jpg)

As you can see the overlay does not cover the whole screen.  Any ideas?

**Comment by xiaolin** [comment]
Looks like an issue with css.

Check to see if your footer area has `z-index` attribute value higher than 5. The fullscreen CSS I wrote only has a `z-index: 5;` so that can be the issue.

**Comment by jadonald72** [comment]
Tried changing z-order, but still same issue. I think it could be the way my view manager is built. If you get the other bug fixed I should be able to call a function to show/hide the items that are showing on to of the overlay. A bit of a hack, but should work.

**Comment by xiaolin** [comment]
Is your footer area also `position: fixed` ? If so it probably has a higher z-index.

**Comment by jadonald72** [comment]
Thanks.  I will close this issue.
