### ISSUE TITLE
number of thumbnails to display

### ISSUE THREAD

**Issue by ilionic** [xiaolin/react-image-gallery#106]
Impressive gallery! Looking for alternatives to replace react-slick, and wondering if it's possible to control number of thumbnails to display as well as optionally hiding main image? 
Besides usage as a gallery I'd like to use it as carousel of slides. For example http://neostack.com/opensource/react-slick

**Comment by xiaolin** [comment]
You can set custom `classes` per thumbnail/slide then you can hide them via css. You can also decrease the amount of thumbnails to show by reducing the length of the thumbnail container via css.

**Comment by xiaolin** [comment]
@ilionic Did this solve your issue?

**Comment by Yuripetusko** [comment]
@xiaolin we have created a fork with `slidesToShow` and `slidesToScroll` will create a PR after some cleanup later next week. We couldn't use classes as if we reveal more slides, then when using inifinite and reaching last item, you could see transition animation of first slides moving to the end of carousel

**Comment by bftawfik** [comment]
where is this fork gone ?

**Comment by MohammadHosseinBagheri** [comment]
@Yuripetusko I didnt see slidesToShow but i add className and css to fix it .
for example in bootstrap i use col to show number of thumbnails .
