### ISSUE TITLE
Scrolling page doesn't work on thumbnails on mobile devices

### ISSUE THREAD

**Issue by twanschik** [xiaolin/react-image-gallery#107]
It seems like the call `event.preventDefault()` in `slideToIndex()` prevents scrolling of a page when on mobile devices (via touchstart).

**Comment by xiaolin** [comment]
Thats odd, If you go on the demo page using a mobile device I can scroll just fine.

**Comment by twanschik** [comment]
Try to scroll by "touchstarting" on a thumbnail. Doing so will lead the `event.preventDefault` call.

**Comment by xiaolin** [comment]
Ah I see the issue now.

**Comment by xiaolin** [comment]
I will fix this by removing the `onTouchStart` events since it is no longer needed.
https://github.com/facebook/react/issues/6221#issuecomment-204486835

**Comment by xiaolin** [comment]
fixed in 0.7.3
