### ISSUE TITLE
when the playing end ,it can't not play again

### ISSUE THREAD

**Issue by moxiaobei2** [xiaolin/react-image-gallery#108]
I set the setting infinite=false ,when I start to play the image,at the end of play,I want to play again,it did not worked

**Comment by xiaolin** [comment]
That is intended. If its not infinite It stops at the end once it finishes.

**Comment by moxiaobei2** [comment]
@xiaolin  but it can't not play again~the play do once~~I　mean I want to try like this:I gallery the images,at the ending,I want't to play again.

**Comment by xiaolin** [comment]
You should set `infinite=true` then it will play again.

**Comment by xiaolin** [comment]
Closing this, feel free to open if you have more questions.
