### ISSUE TITLE
Gallery exceeds 100% of screen height

### ISSUE THREAD

**Issue by jossi87** [xiaolin/react-image-gallery#111]
My screen resolution is 2560x1080px. When I start fullscreen on http://linxtion.com/demo/react-image-gallery/ only top of the thumbnails are visible on screen (see attached screenshot).

A similar problem occurs when I use portrait images.

![scale example](https://cloud.githubusercontent.com/assets/17472908/19997980/55f17c42-a26a-11e6-88d2-8a67eb247e9a.jpg)

**Comment by xiaolin** [comment]
@jossi87 You will have to play with the css to get it working on all your resolutions. The demo slides are naturally 1920x1200, and I've modified the gallery css on the demo page with
```
.app .image-gallery {
    margin: 0 auto;
    width: 65%; 
    transition: all 1s ease;
```
You can adjust the width / use media queries so that it fits appropriately on different screen sizes.
I've modified the width to about `58%` to fit the gallery in your resolution
![screen shot 2016-11-04 at 9 54 05 am](https://cloud.githubusercontent.com/assets/1286776/20007932/da560fe8-a274-11e6-9912-d26ff54ebba0.png)

**Comment by jossi87** [comment]
Thank you for your quick reply!

This solves the problem with landscape images.
But I still can't figure out how to fix portait images.
When I inspect one portrait image in fullscreen mode with Chrome the size is: "1664 × 2496 pixels (Natural: 720 × 1080 pixels)".
If I disable ".image-gallery-slide img { width: 100%; }" this is the result: "720 × 1080 pixels" (as I wanted). But now the image is not centered anymore, and landscape-images does not work as expected...

**Comment by xiaolin** [comment]
If you're mixing portraits and landscapes (with varying sizes), you're going to have to tweak the css to fit your needs. `ImageGallery` supports custom classes (`originalClass`, `thumbnailClass`) for each slide so you can probably do something with that to adjust your landscape and portrait images.

e.g. (untested)

```
const item = [
      {
        original: `landscape1080x720.jpg`,
        thumbnail: `landscapethumbnail.jpg`,
      },
      {
        original: 'portrait720x1080jpg',
        thumbnail: 'portraitthumbnail.jpg',
        originalClass: 'portrait-slide',
        thumnailClass: 'portrait-thumb'
      }
]
```

in the css you can override
```
.image-gallery-slides .portrait-slide {
    width: 50%; // restrict the width for portraits
    margin: 0 auto; // center the image
}
```

**Comment by jossi87** [comment]
Thank you again for your help.
I have many different sizes of images, and found a solution working for me (Chrome, IE, Edge).

I use my own render-method:
`renderImage(item) {
    return (
      <div className='image-gallery-image'>
        <img src={item.original} style={{maxHeight: '100vh', maxWidth: '100vw', objectFit: 'scale-down', fontFamily: "'object-fit: contain'"}}/>
      </div>
    );
  }`

The font-family here is to enable object-fit-support in IE and Edge using this library: https://github.com/bfred-it/object-fit-images

**Comment by xiaolin** [comment]
Awesome, glad it worked out. I'm closing this issue then 👍
