### ISSUE TITLE
Delete Image

### ISSUE THREAD

**Issue by DiegoGallegos4** [xiaolin/react-image-gallery#112]
Whenever deleting an image: 

`deleteImage(){
    const {images} = this.state.form
    let idx = this._imageGallery.getCurrentIndex();

    this.setState({
      form: update(this.state.form,{
        $merge: {
          images: images.filter((img, i) => i !== idx),
        }
      })
    });
  }`

The rendered gallery is empty but on the DOM there are still images. Are there any examples of image deleting?

**Comment by xiaolin** [comment]
When you update the state of your items it will delete whatever is not in there.

e.g.
```
  constructor() {
    this.state = {
      images: [
        {
          thumbnail: 'image1.jpg',
          original: 'image1.jpg',
        },
        {
          thumbnail: 'image2.jpg',
          original: 'image2.jpg',
        }
     ],
    };
  }

  deleteImage() {
    this.setState({images: this.state.images.filter(image => image.thumbnail === 'image1.jpg')})
  }

  render() {
    <div>
      <ImageGallery images={this.state.images} />
      <button onClick={this.deleteImage.bind(this)}>Delete image 1</button>
    </div>
  }
```

You might not be deleting your images correctly.

**Comment by xiaolin** [comment]
@DiegoGallegos4 were you able to fix your issue?

**Comment by DiegoGallegos4** [comment]
@xiaolin Images are being deleted correctly, the rest of the images are in the DOM when deleted but the carrousel does not update its active classes. I ended clicking on the right arrow to fix it but its an ugly hack.

**Comment by xiaolin** [comment]
@DiegoGallegos4 I see the issue you're having, to fix this you should slide to the index after you delete your images. If you're on index 7 and it gets deleted, you should handle where the slide should go to. You can do so using the function `slideToIndex` to get to where you want.

**Comment by xiaolin** [comment]
Closing this, feel free to reopen if this is still an issue.

**Comment by DiegoGallegos4** [comment]
The complete solution would be: 

let idx = this._imageGallery.getCurrentIndex();
this._imageGallery.slideToIndex(idx == 0 ? idx : idx - 1);

if index is 0 is trying to slide to the next then if could fall into the case that there is no other image because the last image passed to be the 0 idx. This works for all the cases:

1. Deleting 0 index
2. Deleting last index
3. Deleting from middle indexes. 

Thanks!
