### ISSUE TITLE
All images are viewed at the same time

### ISSUE THREAD

**Issue by Burak07** [xiaolin/react-image-gallery#114]
Screenshot below explains the issue

- Using webPack and I'm not sure it is about webpack configuration so posting it here.
-I suspect some configuration fail is behind it.

```

var path = require("path");

var DIST_DIR = path.resolve(__dirname, "dist");
var SRC_DIR = path.resolve(__dirname, "src");

var config = {
    entry: SRC_DIR + "/app/index.js",
    output: {
        path: DIST_DIR + "/app",
        filename: "bundle.js",
        publicPath: "/app/"
    },
    module: {
        loaders: [
            {
                test: /\.js?/,
                include: [SRC_DIR,'/node_modules'],
                loader: "babel-loader",
                query: {
                    presets: ["react", "es2015", "stage-2"]
                }
            },
            {
                test: /\.s?css$/,
                include: [SRC_DIR],
               loaders: ['style',  'css']
            }
        ]
    }
};

```
module.exports = config;

- I think  it can not access css and scss files in nodemodules/react-image-gallery and this causes the issue. If so not sure how to configure it .

-There is no error on console.
![untitled](https://cloud.githubusercontent.com/assets/15873388/20463704/d283af9e-af41-11e6-9001-9790ca0499b2.png)

**Comment by xiaolin** [comment]
I'm not sure how you're importing your css, double check by inspecting the elements to see if css is applied. This to me seems like an css import issue/configuration with your webpack.

**Comment by xiaolin** [comment]
Try using a webpack starter kit, and see what the issue is with your configuration. Its hard for me to tell what is actually wrong, and how you are importing the css file.

**Comment by VikrantShirvankar** [comment]
facing same issue.
