### ISSUE TITLE
Using this component in a form

### ISSUE THREAD

**Issue by karlguillotte** [xiaolin/react-image-gallery#115]
First, thanks for your component! It works like a charm. 

Here is my issue, I am using your component in a form to show images that are about to be submitted along with the form. Anytime I press one of the buttons (navigation or bullets) my form gets submitted. The reason, there is no `type` attribute specified. They default to `type=submit` when rendered in a form. 

Would it be possible to add `type=button` to these buttons? 

More details: https://html.spec.whatwg.org/multipage/forms.html#attr-button-type-submit-state

Thanks! 
Karl

**Comment by xiaolin** [comment]
Sure, that seems easy enough. Wanna open a PR?

**Comment by xiaolin** [comment]
Fixed in v0.7.4
