### ISSUE TITLE
Custom Arrows

### ISSUE THREAD

**Issue by davibq** [xiaolin/react-image-gallery#117]
Hi, 

I was thinking about the possibility of:
1- Create a css version of image-gallery.css without the icons import. Something like image-gallery-no-icons.css
2- Create properties to specify the buttons that need icons as React components.

I can implement them if you think this will be useful.

**Comment by xiaolin** [comment]
I'm totally cool with #1, but how would you implement #2? The current icons has specific css applied to them, will you be preserving that?

**Comment by Josephjbliss** [comment]
+1 for this feature

**Comment by tadjohnston** [comment]
+ 1 for this. I'd specifically like to override the navigation with my own (like `_renderItem`).

**Comment by kamui** [comment]
For `#2`, couldn't you have props for the icons as react components and then you just default those prop values to your current icon set? Then if you override those props, the existing css will load, but the elements with those classes wont be rendered, so it shouldn't be an issue.

**Comment by xiaolin** [comment]
@kamui you're right, that would work. If no one opens a PR, i'll try to get to this soon.

**Comment by xiaolin** [comment]
`#1`, and `#2` has been fully release in v0.7.10. Thanks @kamui for the help.

See [readme](https://github.com/xiaolin/react-image-gallery) for more information on adding custom icons
