### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by darklilium** [xiaolin/react-image-gallery#119]
I have this code and idk why is giving me an error or what im missing, any help will be very appreciate :)
Thanks in advice!.

```
import React from 'react';
import ReactDOM from 'react-dom';
import {browserHistory} from 'react-router';
import {DashboardHeader} from "./DashboardHeader.jsx";
import ImageGallery from 'react-image-gallery';


class AP_Dashboard extends React.Component {

  constructor(props){
    super(props);

    this.state = {


    }

  }
  handleImageLoad(event) {
      console.log('Image loaded ', event.target)
    }





  onChange(e){

  }

  onClickItem(a){

  }
  onClickThumb(f){}

  render(){
    const images = [
      {
        original: 'http://lorempixel.com/1000/600/nature/1/',
        thumbnail: 'http://lorempixel.com/250/150/nature/1/',
        originalClass: 'featured-slide',
        thumbnailClass: 'featured-thumb',
        originalAlt: 'original-alt',
        thumbnailAlt: 'thumbnail-alt',
        thumbnailLabel: 'Optional',
        description: 'Optional description...',
        srcSet: 'Optional srcset (responsive images src)',
        sizes: 'Optional sizes (image sizes relative to the breakpoint)'
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/2/',
        thumbnail: 'http://lorempixel.com/250/150/nature/2/'
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/3/',
        thumbnail: 'http://lorempixel.com/250/150/nature/3/'
      }
    ]

    var imageDiv = images.map((image,index)=>{
          return <div key={index} className="galleryDivImg"><img key={index} src={image.original} />
                    <p  className="legend">Legend {index}</p></div>;
    });


    return (
      <div className="wrapper_APDashboard">
        <DashboardHeader user="Evelyn"/>
        <ImageGallery
        ref={i => this._imageGallery = i}
        items={images}
        slideInterval={2000}
        onImageLoad={this.handleImageLoad}/>
      </div>

  );
  }
}

export default AP_Dashboard;
```

![image](https://cloud.githubusercontent.com/assets/8507515/21237227/d0d76fe2-c2dc-11e6-9cc0-452dcf665405.png)

**Comment by xiaolin** [comment]
I don't see anything wrong in this snippet.

You can google and look for some similar issues.

Are you using react-router? If so check out this issue.
https://github.com/ReactTraining/react-router/issues/2220

**Comment by darklilium** [comment]
Yes i am.

**Comment by darklilium** [comment]
I saw the issue here and the other website link :https://codereviewvideos.com/blog/warning-react-createelement/

And i still dont get where is the problem ):

**Comment by xiaolin** [comment]
If you remove `ImageGallery` does it work?

**Comment by darklilium** [comment]
Yes, im having the issue with the ImageGallery only

**Comment by xiaolin** [comment]
Hmm, I'm not seeing anything wrong that would cause that error. Its also hard for me to debug from that screenshot, since it doesn't look specific to `ImageGallery`

Try a simpler render like
```
  render() {
    const images = [
      {
        original: 'http://lorempixel.com/1000/600/nature/1/',
        thumbnail: 'http://lorempixel.com/250/150/nature/1/'
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/2/',
        thumbnail: 'http://lorempixel.com/250/150/nature/2/'
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/3/',
        thumbnail: 'http://lorempixel.com/250/150/nature/3/'
      }
    ]



    return (
      <div className="wrapper_APDashboard">
        <DashboardHeader user="Evelyn" />
        <ImageGallery items={images} />
      </div>
    );
  }
```

**Comment by darklilium** [comment]
Nope, it doesnt work.
Maybe its another problem but still doesnt know what it is.
Let me share with u all the code i have in this pen: http://codepen.io/darklilium/pen/pNQYVX

There are some notes in the js file in the last part.

Note: 
- Im just learning how to use react router, this is my second application where i use it. So when i try in the AP_Dashboard.jsx file to add the react-image-gallery with the example that also u provide me i have the error that i showed u before.
- The react router code i have it in App.js.

Thanks for ur help !

**Comment by darklilium** [comment]
My github repo : https://github.com/darklilium/APChilquinta2017 just in case.

**Comment by xiaolin** [comment]
Its hard to debug the issue because your build isn't working. I suggest taking a closer look at how you are implementing your routes, and initial rendering. Try taking out all the routes, and just rendering the component, see if that works.

**Comment by xiaolin** [comment]
closing this, as its not related to `react-image-gallery`
