### ISSUE TITLE
[Feature-Request] Adding more control elements (like fullscreen button)

### ISSUE THREAD

**Issue by venyii** [xiaolin/react-image-gallery#120]
Hi,

I'd like to add more options/elements like the fullscreen button to the gallery and position them individually. Therefore, I need to be able to render additional DOM elements on the same level (within `image-gallery-slide-wrapper` like [here](https://github.com/xiaolin/react-image-gallery/blob/bb737302da054a7949233866cc22f970ad6eb26a/src/ImageGallery.jsx#L703) to not have the thumbnails complicate the absolute positioning).

Do you think that this is a valid use case you're willing to support? It could be a callback defaulting to render nothing.

Thanks!

**Comment by xiaolin** [comment]
What type of options are you planning to add?

**Comment by venyii** [comment]
Right now, I'd just like to add a linked image that changes its position within the currently displayed image depending on the screen size. It isn't really a gallery control, but this case could be handled as well.

**Comment by xiaolin** [comment]
You should be able to add your icons via css? if you wrap

```jsx
<div className="my-class">
  <ImageGallery />
  <div className="my-controls">
     Your custom controls
  </div>
</div>
```

then you can do

```css
.my-class {
  position: relative;
}

.my-controls {
  position: absolute;
  bottom: ...;
}
```

**Comment by venyii** [comment]
The problem is, that my elements are not inside the image node `.image-gallery-slide-wrapper`, which means that I can't simply do `.my-controls { ..., bottom: 0; }` since they'll be at the end of the surrounding container. Additionally, the controls are excluded from the fullscreen view, as far as I can see.

**Comment by xiaolin** [comment]
Ah, the fullscreen view would exclude those options.

Sure I think we can support an additional render inside the wrapper. Feel free to open a PR.
