### ISSUE TITLE
Sliding to the end of collection triggers onSlide twice

### ISSUE THREAD

**Issue by barmalejj** [xiaolin/react-image-gallery#123]
When user clicks left slide change button the *onSlide* event is triggered twice - once with `index = -1` and once again with `index = <last in collection>`

Is it expected behavior?

**Comment by xiaolin** [comment]
Hmm I'm not able to replicate this. the `onSlide` event is triggered whenever the index is different. Index should not be `-1` it should start at `0`

**Comment by xiaolin** [comment]
closing this, feel free to re-open if this is still happening.
