### ISSUE TITLE
Slide transition: "Ghost images"

### ISSUE THREAD

**Issue by pablopaul** [xiaolin/react-image-gallery#125]
Hey guys, 

I have implented your great component with SVGs with transparent background and on some transitions it seems like "other" slides "ghosting around", I tried to capture in the following GIF:

![Gif](https://media.giphy.com/media/l4JyZJleV63tratFu/giphy.gif)

You can play with the live example here https://myinnerteam.com/

**Can you see wheat I mean?**

Any ideas how to avoid/fix?

Thanks

**Comment by mikkom** [comment]
Yeah, I think you can see this kind of behavior even without using transparent svg's. It seems to happen especially when selecting the first or last image. See for example https://carousel-testing-juetwjpedv.now.sh/

Configuration used in the example:

```javascript
{
  slideInterval: 2000,
  lazyLoad: false,
  infinite: true,
  showBullets: true
}
```

**Comment by pablopaul** [comment]
@mikkom thanks for the clarification and another example with the same issue

**Comment by xiaolin** [comment]
@pablopaul @mikkom thanks for the report, for now if you set `infinite={false}` it would prevent ghost images from appearing. I'll take a look at the code over the weekend to see if I can patch this up.

**Comment by xiaolin** [comment]
I was able to find a fix, gonna test it some more tonight, will update you guys once its released.

**Comment by xiaolin** [comment]
@pablopaul t@mikkom try setting a background color on your slides, I notice this issue is happening because the images are not taking the full width of the container, or the images are transparent.

```
.image-gallery-slide {
    background: #fff;
}
```

**Comment by pablopaul** [comment]
@xiaolin thx for your effort, background color is not a solution for me since the images have transparent background and a color would change the whole game 😒

**Comment by xiaolin** [comment]
What about adding

```
.image-gallery-slide {
    background: #fff;
    background-image: url('your_background_image');
    background-repeat: no-repeat;
    background-size: cover;
}
```

The difference here is the background is on every slide individually.

When you have `infinite={true}` and you go from the last slide to the first, the logic adjust the first and last slide so that they are appropriately positioned. Normally this happens in the background, but your background is transparent.

**Comment by xiaolin** [comment]
The latest version 0.7.5 I release should automatically fix your issue @mikkom.

As for transparent images, thats going to be a bit more tricky. I suggest the above solution with a custom set background image and color, or turning off `infinite`

**Comment by mikkom** [comment]
Thanks @xiaolin, version 0.7.5 definitely works much nicer with my example! Happy holidays - really appreciate what you've done with react-image-gallery 🙌

**Comment by xiaolin** [comment]
closing thing per release v0.7.5

**Comment by pablopaul** [comment]
@xiaolin Thanks again and the approach with the background image for each slide gives another visual transition (because of the skewed background), see the following example:

![img](https://media.giphy.com/media/l0JLVsldZbrR2lRgQ/giphy.gif)

I think `infinite: false` is the only solution here, or am I missing something?

**Comment by xiaolin** [comment]
@pablopaul infinite false is the only thing that I can think of right now due to the images being transparent.

**Comment by xiaolin** [comment]
@pablopaul I know its a bit late, but the latest release of the library `0.8.1` will fix the transparent image issue you were having.

**Comment by pablopaul** [comment]
@xiaolin Thanks for the heads up, can you point me to the exact code change which solves the problem?

**Comment by xiaolin** [comment]
@pablopaul https://github.com/xiaolin/react-image-gallery/commit/b08f3bf5c39454a8eb201ac57368150e87080be0
