### ISSUE TITLE
0.7.7 version problem

### ISSUE THREAD

**Issue by lamyat2005** [xiaolin/react-image-gallery#127]
Hi Xiaolin, I've found that the latest commit 0.7.7 image-gallery-slide-wrapper and thereafter are deleted and therefore photos are not displayed. Would you please have a look? Thanks.

**Comment by xiaolin** [comment]
I had to bump the version to 0.7.8, 0.7.7 was missing a default `thumbnailPosition`

**Comment by lamyat2005** [comment]
Hi Xiaolin, the latest version seems thumbnails now cannot click on it. Would you please have a look? Thanks.
