### ISSUE TITLE
lazyLoad buffering

### ISSUE THREAD

**Issue by tadjohnston** [xiaolin/react-image-gallery#128]
Is it possible to add a buffer image around the right and left images? Without the buffer, on swipe, you get a blank image as the next image ( shown by dragging slow) like so:

![swipe](https://cloud.githubusercontent.com/assets/10748767/21650042/908f02fc-d258-11e6-9b86-c763ea1becbc.gif)

Can another image be tacked on to each side (right, left) so the blank image thing doesn't happen?

**Comment by xiaolin** [comment]
This is odd, `lazyLoad` always loads the left, center, and right images.

**Comment by tadjohnston** [comment]
Yeah, but if you drag right or left, there is no image available yet.  Another image would need to be added so you don't see blank.

**Comment by xiaolin** [comment]
Left, and right should be added. You always start with center, left, and right images, all three being loaded so you can drag left, and right. 

Do you have the css/scss files loaded into your library? can you show me the full screen shot of how the gallery looks like?

**Comment by tadjohnston** [comment]
Currently `lazyLoad` looks like this:
```
<div class="image-gallery-swipe"><div class="image-gallery-slides">
  <div class="image-gallery-slide center" style="transform: translate3d(0%, 0px, 0px); z-index: 3;">      
    <div class="image-gallery-image"><img src="image-1"></div>
  </div>
  <div class="image-gallery-slide right" style="transform: translate3d(100%, 0px, 0px); z-index: 1;">  
    <div class="image-gallery-image"><img src="image-2"></div>
  </div>
  <div class="image-gallery-slide left" style="transform: translate3d(-100%, 0px, 0px); z-index: 1;">
    <div class="image-gallery-image"><img src="image-3"></div>
  </div>
</div>
```

What I'm proposing is something like this to fix the issue:
```
<div class="image-gallery-swipe"><div class="image-gallery-slides">
  <div class="image-gallery-slide center" style="transform: translate3d(0%, 0px, 0px); z-index: 3;">      
    <div class="image-gallery-image"><img src="image-1"></div>
  </div>
  <div class="image-gallery-slide right" style="transform: translate3d(100%, 0px, 0px); z-index: 1;">  
    <div class="image-gallery-image"><img src="image-2"></div>
  </div>
  <div class="image-gallery-slide left" style="transform: translate3d(-100%, 0px, 0px); z-index: 1;">
    <div class="image-gallery-image"><img src="image-3"></div>
  </div>
</div>

**Comment by tadjohnston** [comment]
Currently `lazyLoad` looks like this:
```
<div class="image-gallery-swipe"><div class="image-gallery-slides">
  <div class="image-gallery-slide center" style="transform: translate3d(0%, 0px, 0px); z-index: 3;">      
    <div class="image-gallery-image"><img src="image-1"></div>
  </div>
  <div class="image-gallery-slide right" style="transform: translate3d(100%, 0px, 0px); z-index: 1;">  
    <div class="image-gallery-image"><img src="image-2"></div>
  </div>
  <div class="image-gallery-slide left" style="transform: translate3d(-100%, 0px, 0px); z-index: 1;">
    <div class="image-gallery-image"><img src="image-3"></div>
  </div>
</div>
```

What I'm proposing is something like this to fix the issue:
```
<div class="image-gallery-swipe"><div class="image-gallery-slides">
  <div class="image-gallery-slide center" style="transform: translate3d(0%, 0px, 0px); z-index: 3;">      
    <div class="image-gallery-image"><img src="image-1"></div>
  </div>
  <div class="image-gallery-slide right" style="transform: translate3d(100%, 0px, 0px); z-index: 1;">  
    <div class="image-gallery-image"><img src="image-2"></div>
  </div>
  <div class="image-gallery-slide left" style="transform: translate3d(-100%, 0px, 0px); z-index: 1;">
    <div class="image-gallery-image"><img src="image-3"></div>
  </div>
  <div class="image-gallery-slide left-buffer" style="transform: translate3d(-200%, 0px, 0px); z-index: 3;">      
    <div class="image-gallery-image"><img src="image-4"></div>
  </div>
  <div class="image-gallery-slide right-buffer" style="transform: translate3d(200%, 0px, 0px); z-index: 3;">      
    <div class="image-gallery-image"><img src="image-5"></div>
  </div>
</div>

**Comment by xiaolin** [comment]
Just tested the latest build and it seems to be working.

**Comment by tadjohnston** [comment]
If you drag slow you'll see the blank screen if the image isn't cached already.

**Comment by tadjohnston** [comment]
Swipe:

| image_2 | image_3 | image_4 |

if I swipe ----->  I get

|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;| image_2 | image_3 |

until the component sets state / re-renders in which I would then get
| image_1  | image_2 | image_3 |

**Comment by xiaolin** [comment]
In the recent release I think 0.7.5 I removed the ability to swipe past more than 1 image. Is that what you're talking about? when swiping more than 1 image over?

**Comment by tadjohnston** [comment]
Pretty much yes, but only because of the blank space associated with only swiping 1 image.

**Comment by xiaolin** [comment]
What version are you on? I suggest using the latest build. `0.7.9`. being able to hold the swipe for over more than one image was a bug that is fixed.

**Comment by tadjohnston** [comment]
Hmm.. Maybe that's why, I'm on `0.7.8`

**Comment by xiaolin** [comment]
Oh, then you should be okay actually. `0.7.9` was just a package description change no updates to the js code.

**Comment by tadjohnston** [comment]
Looks like a css issue.  Gonna have to find out where. Sorry for the confusion here. This image gallery is really great btw! Closing this...
