### ISSUE TITLE
Less than 3 images breaks the gallery

### ISSUE THREAD

**Issue by tadjohnston** [xiaolin/react-image-gallery#130]
If I have less than 3 images, it shows a blank screen.

Example:

Load in 2 images. Notice it only creates a `image-gallery-slide left`.  It does not create a center image or right image

![screen shot 2017-01-05 at 10 52 58 am](https://cloud.githubusercontent.com/assets/10748767/21693313/4b2286c0-d335-11e6-82db-0059696d76ae.png)

Here is what it produces:

![screen shot 2017-01-05 at 10 52 47 am](https://cloud.githubusercontent.com/assets/10748767/21693325/54c06b84-d335-11e6-9b1b-b062018a5bf9.png)

**Comment by xiaolin** [comment]
I'm unable to replicate this. Can you double check your styles, and try using the example I provided as a test case for 2 images.

**Comment by xiaolin** [comment]
Were you able to fix your issue?

**Comment by tadjohnston** [comment]
Yeah, it looks like it's working now. Possibly a caching issue.  I'll make sure I do a better job submitting bugs in the future 😞
