### ISSUE TITLE
On Nav click scroll to top of Item

### ISSUE THREAD

**Issue by GramParallelo** [xiaolin/react-image-gallery#133]
Hey,  I have my gallery set to `overflow-y: scroll` and when I navigate to an item I want the scroll to be at the top. How do I do this? Thanks

**Comment by xiaolin** [comment]
Are you trying to slide the gallery from top to bottom instead of left to right?

**Comment by GramParallelo** [comment]
@xiaolin  No.  I have a fixed height gallery and mixed height items. as such, `overflow-y: scroll`  does that make sense.  the issue is that when i navigate left or right the scroll doesn't go to the top when entering a new item.

**Comment by xiaolin** [comment]
I see, I would try wrapping the gallery in your own container and set overflow-y on it. This way you have access.

Sample code (Untested)
```jsx
myOnSlide() {
 this.myDiv.scrollTop = 0;
}

render() {
  <div ref={i => this.myDiv = i} style={{'overflow-y': scroll}}>
     <ImageGallery onSlide={this.myOnSlide.bind(this)}/>
  </div>
}
```

I would also encourage you to not have a scroll, and instead use a fix height for mixed height images. This way they will all fit the gallery container.

```css
.image-gallery-image {
    text-align: center;
}

.image-gallery-slide img {
    width: auto;
    height: 400px;
}
```

**Comment by GramParallelo** [comment]
Awesome thanks for the help! I couldn't get your way to work how i needed but was able to learn from it :+1: 

what is working for me now is instead of wrapping in a div i just grab .image-gallery where i set the scroll on:  
`window.document.getElementsByClassName('image-gallery')[0].scrollTop = 0`
in my base.css: `.image-gallery { overflow-y: scroll }`
Is there any reason i should try another way? i.e. using the wrapper div etc.

The pro-tip would probably be avoid this but I'm using text not images and hence need the scroll.  And its an experimental blog idea :smile:

**Comment by xiaolin** [comment]
I suggested wrapping the ImageGallery component because you would have more control over your own wrapper then trying to access a components internals. This way if the component gets updated with a new class, your code will still work.

Ah, I didn't realize you were using text. 😄

**Comment by GramParallelo** [comment]
i played around a little more ... and i think i'll stick with adding to scrolling `.image-gallery` because with scrolling just added to the wrapper, when you go fullscreen you will no longer will be able to scroll.  if there's a better way let me know
for styling the buttons i would have to access the component internals, right?, is there a better practice for this?  thanks

**Comment by xiaolin** [comment]
Ah, fullscreen would be an issue for that.

For styling buttons I would overwrite the stylesheets, or you can overwrite the components using provided props `renderLeftNav`, `renderRightNav`, and any other controls you might want to style.

**Comment by xiaolin** [comment]
Feel free to reopen if you have anything else.
