### ISSUE TITLE
renderItem in lightbox vs carousel

### ISSUE THREAD

**Issue by bkniffler** [xiaolin/react-image-gallery#134]
Hey,
What a great library!
I would love to be able to have a renderItem and a renderLightboxItem or something alike.

This would allow to show a rich element with text in carousel and a pure image in lightbox.
Or it would allow to show a midres image in carousel and a highres image in lightbox.

What do you think?

**Comment by xiaolin** [comment]
Do you mean if an image is clicked a Lightbox would open with the image in it?

**Comment by bkniffler** [comment]
Maybe I used the wrong term, when I said lightbox I referred to the fullscreen view (that technically is a lightbox, no?). 

I'm in a situation, where I use the renderItem to display an image with overlaying div inside the carousel view (like for example https://www.wonderplugin.com/wordpress-slider/). But when fullscreen is entered, it shouldn't render the overlay stuff, only the pure image. 

I wonder if this might be of common interest or if this really is only an edge case. As it seems, the only way to currently achieve this is to listen to onScreenChange, set component state to `fullscreen: true` and to let renderItem return different markup based on `fullscreen === true`.

If we had more fine grained control over the rendering of items inside the carousel vs inside the fullscreen, that would be helpful. 

What do you think?

**Comment by xiaolin** [comment]
I think I understand what you are saying. You should be able to hide all your unwanted elements with CSS. When you enter fullscreen a new class will be added to the gallery container called `fullscreen`

You can then hide all your unwanted items
```
.fullscreen .my-overlaying-div {
  display: none;
}
```

**Comment by bkniffler** [comment]
Sure I could do that via css, but to achieve the overlay stuff I use the image as background-image inside a div and some other stuff that does not play well with the fullscreen view. 

Of course I can adapt styles and hack my way around it. But do you really think it is so uncommon, that people might want to have their slides render differently in the carousel/fullscreen mode?

In my case, it is a carousel that shows images and information, and as soon as fullscreen is active, I'd like to be able to only show the images. 

As I said, I could work my way around it by using the state. I thought it might be a useful addition to the library to have more control about the way slides are rendered throughout different views.

**Comment by xiaolin** [comment]
Your current solution to me is clean and I think is the right way to go for your needs. Listenting to `onScreenChange` and then adjusting your `renderItem` function. 

I don't see the benefits of adding it to the library vs your current solution.
