### ISSUE TITLE
icons not displaying on chrome and firefox

### ISSUE THREAD

**Issue by Grustamli** [xiaolin/react-image-gallery#135]
Hey, I was having and issue with icon display on chrome and firefox. But safari seemed fine. Putting `https` before the cdn url in _ionicons-variables.scss file fixed it. Maybe you should update it too.

**Comment by xiaolin** [comment]
Hmm, thats odd, are you able to see the icons on the demo page?

http://linxtion.com/demo/react-image-gallery/

**Comment by xiaolin** [comment]
@Grustamli Let me know if you are still having this issue.

**Comment by xiaolin** [comment]
closing, feel free to reopen.

**Comment by jspencer** [comment]
Not sure if it's the same as the original problem, but I ran into this when loading the page from a local file. It was trying to load the icons like so, which of course did not work.
file://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/fonts/ionicons.ttf?v=2.0.0

**Comment by xiaolin** [comment]
Ah, yes these icons would not load if you are not using a local webserver.

**Comment by xiaolin** [comment]
released in 0.7.13
