### ISSUE TITLE
Exit full screen after clicking on the background.

### ISSUE THREAD

**Issue by Ancinek** [xiaolin/react-image-gallery#143]
It would be nice to add this feature. Many people just involuntarily click the black background trying to leave the full screen mode. 

That plugin is awesome! Saved a lot o time 👍

**Comment by xiaolin** [comment]
Normally there shouldn't be too much of a black background, full screen takes the entire screen and are not meant to behave like a modal/lightbox. The example does a poor job at showing full screen images because of the image ratio.

Maybe a lightbox/modal solution makes more sense.

**Comment by Ancinek** [comment]
You are right. I did not noticed that. 
Lightbox/modal would be a great advantage. I will try to modify your plugin and see what I can do, but I am a newbie when it comes to JS.
