### ISSUE TITLE
Make Fixed Gallery Images Container

### ISSUE THREAD

**Issue by Shadowman4205** [xiaolin/react-image-gallery#144]
Hello, i tried different things but i cannot make it happen.

I have got images with different sizes, some of them has got width>height and some width<height
Depend on img with default react-image-gallery, when i change img the gallery adjust to image height.
I do not want this, i want the gallery with fixed height and image resizing if width<height . What changes i have to do?  Something like in this image example of anothe issue. Where motorcycle image do not go full.
thanks in advance

![2dcb1aae-af01-11e6-8b12-7695c8ae172c](https://cloud.githubusercontent.com/assets/23194476/22730175/8a51b81a-edee-11e6-8903-84fa2a358cad.jpg)

**Comment by kunokdev** [comment]
any solution to this?
