### ISSUE TITLE
On mobile web, two images are being slided on each click

### ISSUE THREAD

**Issue by giladbr** [xiaolin/react-image-gallery#145]
Hi,

When emulating mobile in Chrome or when trying on Samsung/LG phones, clicking on the arrows slides *two* slides instead of one. [Demo here](https://www.lastminutetravel.com/hotels/details?hotelId=293118&startDate=2017-02-15&endDate=2017-02-16&adults=2&children=).

Also, upon the first slide, the following warning pops up, but I don't know if it's connected:
`Unable to preventDefault inside passive event listener due to target being treated as passive`.

The funny thing is, if I pause the code on "slideToIndex", and then release the debugging, the bug won't appear - only 1 image will be slided, as should be. So this is probably a debouncing/throttling/MIN_INTERVAL/slideDuration/slideInterval issue, but I don't know what exactly causes it and how to solve.

Thanks!

**Comment by xiaolin** [comment]
I'm unable to replicate. What version of `react-image-gallery` are you on?

**Comment by giladbr** [comment]
0.6.7. Please note this only happens when on mobile emulation in Chrome.  Please see: https://www.youtube.com/watch?v=34PaGkJbSzY

**Comment by xiaolin** [comment]
Thats interesting, I also tried it on mobile emulation on Chrome, but I'm on OSX Chrome Version 55.0.2883.95 (64-bit).

The latest release is `0.7.12` wanna give that release a shot?

**Comment by giladbr** [comment]
I'm on windows 10. But this also happens on real Samsung and LG devices...

**Comment by xiaolin** [comment]
Can you try the [demo gallery](http://linxtion.com/demo/react-image-gallery/), and see if it still happens on the LG device?

**Comment by giladbr** [comment]
Updated to `0.7.12`, solved the bug immediately, plus I got for free a full-screen button + play/pause + prettier arrows!!!! Way to go!!!! Closing the issue :-)
