### ISSUE TITLE
React warning

### ISSUE THREAD

**Issue by hdzidic** [xiaolin/react-image-gallery#149]
Getting the following warning from react:

`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Component_name. See https://fb.me/react-warning-keys for more information.`

Any chance we can pass keys with the items prop?

**Comment by xiaolin** [comment]
Keys are currently set when iterating through items prop and using the [index](https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.jsx#L791) as the key. 
What is `Component_name`?

**Comment by hdzidic** [comment]
It's just a component the ImageGallery is in. Here's how I set it:

`<ImageGallery items={this.createImagePaths()} slideInterval={1000} showFullscreenButton={false} showPlayButton={false}/>`

This is a snippet of the createImagePaths method:

`pictures.forEach((picture) => {
      let picturePath = {};
      picturePath.original = picture.path;
      picturePath.thumbnail = picture.path;
      picturePaths.push(picturePath);
    });

    return picturePaths;`

**Comment by xiaolin** [comment]
Thats odd, if you're passing in an array of objects you shouldn't be getting the unique key warning. Is `ImageGallery` the only component you are rendering in your `Componenet_name`?

**Comment by hdzidic** [comment]
No, but the stack trace points to the method that renders the `ImageGallery`. I'll try this in a clean component and let you know.

**Comment by xiaolin** [comment]
Let me know if this is still an issue, otherwise we can probably close it.
