### ISSUE TITLE
Adjusting swipe smoothness 

### ISSUE THREAD

**Issue by jasan-s** [xiaolin/react-image-gallery#151]
Is it possible to adjust swipe resistance to achieve more smooth animation.

**Comment by xiaolin** [comment]
You can adjust the `slideDuration` to either make it last longer or shorter, the current default is `450ms`

**Comment by xiaolin** [comment]
@jasan-s did this solve your issue?

**Comment by jasan-s** [comment]
@xiaolin , Thanks that improved the swipe experience quite a bit, but is the resistance of each swipe adjustable as well? I mean to say the swipe threshold to where the image falls back instead of transitioning.

**Comment by xiaolin** [comment]
ah, the swipe threshold is not currently adjustable, but is very easy to add. If no PR is opened I can add it sometime this week.

**Comment by jasan-s** [comment]
😁 thanks

**Comment by xiaolin** [comment]
@jasan-s release v0.7.14 has a new prop called `swipingTransitionDuration` to adjust the transition in milliseconds while swiping.
