### ISSUE TITLE
[Question] Sizing images

### ISSUE THREAD

**Issue by rockchalkwushock** [xiaolin/react-image-gallery#155]
I see there is a property `sizes` on the `items` prop. Is that a way to set sizes for different viewports or is this where an array of the same image is stored just at different sizes?

```javascript
const images = [
      {
        original: 'http://lorempixel.com/1000/600/nature/1/',
        sizes: // is this an array, object, string?
      }
    ]
```
Could you possibly provide a small example snippet?

**Comment by xiaolin** [comment]
It's an HTML5 attribute on `img` see https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by rockchalkwushock** [comment]
@xiaolin 

ah I see now thanks for the quick response & great package! Very developer friendly. Closing issue.
