### ISSUE TITLE
Handling manual Open/Close gallery examaple

### ISSUE THREAD

**Issue by hazboun** [xiaolin/react-image-gallery#156]
First of all, thank you so much for this wonderful library!

I'm trying to manually launch the gallery from a different location in a page and would really appreciate an example of how to achieve that.

Thanks

**Comment by xiaolin** [comment]
What do you mean by launch the gallery from a different location?

**Comment by hazboun** [comment]
I'm using the gallery to show a bunch of images at the bottom of a page, but I also have a master photo at the very top where I want to allow users to click on it and launch the same gallery.

**Comment by xiaolin** [comment]
I suggest you google for a solution here, this seems very specific to your use case and I'm still confused what you mean by "launch the gallery" does launch mean open the gallery in a modal? or Navigate to a new page with a modal?

**Comment by hazboun** [comment]
What I'm trying to achieve is to call the same function that FullScreenButton does. I see in the docs fullScreen() function but how can can I call it?

**Comment by xiaolin** [comment]
Ah,  you call it by assigning a ref e.g.

```
openFullScreen = () => {
  this._imageGallery.fullScreen()
}
render() {
<div>
<a onClick={this.openFullScreen}>Open fullscreen</a>
<ImageGallery ref={a => this._imageGallery = a}/>
</div>
}
```

**Comment by hazboun** [comment]
Wonderful, thanks a lot for the help :)

**Comment by xiaolin** [comment]
take a look at the example app in the repo, has lots of examples on using the functions and taking advantage of the props.

https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js

**Comment by hazboun** [comment]
Thanks! Must say this is really well-built and powerful library you got there!
