### ISSUE TITLE
how to set height,width,x and y values on the gallery?

### ISSUE THREAD

**Issue by solancer** [xiaolin/react-image-gallery#157]
I'm trying to define Width, Height, X and Y cordinates for the gallery in my app. But it doesn't seem to take any css values.

```
<ImageGallery
		ref='thisImage'
		items={this.imageNodesRes}
		slideInterval={2000}
		disableArrowKeys={true}
		onImageLoad={this.handleImageLoad}
		style={{
	      		display: this.shouldDisplay(),
	      		position:this.imgRect.position,
	      		left:this.imgRect.left,
	      		top:this.imgRect.top,
	      		width:this.imgRect.width +'px',
	      		height:this.imgRect.height + 'px'
	      	}}
/>
```

**Comment by xiaolin** [comment]
You override the CSS.

The `style` prop is not a prop the component accepts. See the list of accepted props in readme.

**Comment by solancer** [comment]
@xiaolin is there any way I can do it inline? If I need to modify your code to add style as a prop to ImageGallery, would it work?

**Comment by xiaolin** [comment]
@solancer Is there any reason you can't override the CSS? If you modify the code yes you can add a style as a prop, but currently the library is not ready for inline styles.

**Comment by nituravi36** [comment]
i have styled the component like below.
.image-gallery-slide{
  height : 200px;
}
same styles applied when opened in fullscreen also.
how to style normal and fullscreen modes separately?
