### ISSUE TITLE
Pause auto play on mouse over in desktop

### ISSUE THREAD

**Issue by vrpruthvi** [xiaolin/react-image-gallery#164]
Thanks for the plugin 👍 . Is it possible to pause carousel on mouse over when auto play is ON?

**Comment by xiaolin** [comment]
This caused a lot of issues especially on mobile so this is something I won't be adding to the library.

Instead you can wrap the library in your own container, and `onmouseover` you can call the component functions `pause()` and `play()` to accomplish your requirements.
