### ISSUE TITLE
if useBrowserFullscreen is true, i cannot exit fullscreen mode

### ISSUE THREAD

**Issue by achtan** [xiaolin/react-image-gallery#167]
there is no cancel-fullscreen-button, keyboard `ESC` press dont to anything as well

**Comment by xiaolin** [comment]
What browser are you on? There is also a button to cancel full screen

https://d1zjcuqflbd5k.cloudfront.net/files/acc_418933/1EyP?response-content-disposition=inline;%20filename=Screen%20Shot%202017-03-16%20at%2019.42.37.png&Expires=1489708065&Signature=EMH08~rdwuo0QLkRi9xIkmW3AeBtfjhROsp~LmOCI1DMptH4un4LuLuilwnV6VEiQ-hTmnbhflAxNMX8Wr-gIO-F8TGHibECCpcAIgZ-XyDjF1anyft8OUiLto~oW8QpfYmDBM8F14TOoT3PGXpFgxdYcqGPJTj-yLmC3WjagnQ_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA

**Comment by achtan** [comment]
oh now i see, the problem is in screen ratio:
![screenshot 2017-03-17 09 30 15](https://cloud.githubusercontent.com/assets/1048212/24035132/904e690c-0af4-11e7-9c88-1feeaf88f80f.png)
vs
![screenshot 2017-03-17 09 30 38](https://cloud.githubusercontent.com/assets/1048212/24035140/9edc7540-0af4-11e7-8688-6d98527b1a7f.png)

but `ESC` key still not working (should i open new issue for this? )

**Comment by xiaolin** [comment]
This is not an issue because the gallery does not predict image ratio/sizes instead use css to adjust the gallery to your needs.

**Comment by achtan** [comment]
ok, and what about ESC key press ?

**Comment by xiaolin** [comment]
Oh, that I'm still curious about, based on your screenshots, it seems you didn't actually use the browser fullscreen API, what browser are you on? Normally you're whole screen should be blocked off, like when you full screen a video.

**Comment by achtan** [comment]
i'm using `useBrowserFullscreen: false` 

browser: Chrome 56.0.2924.87 (64-bit)
