### ISSUE TITLE
when useBrowserFullscreen is false thumbnails are 'silded' away with first image

### ISSUE THREAD

**Issue by achtan** [xiaolin/react-image-gallery#169]
![mar-17-2017 16-31-02](https://cloud.githubusercontent.com/assets/1048212/24050486/3d1d19f0-0b2f-11e7-9856-c8dcb0d760f9.gif)

**Comment by xiaolin** [comment]
I can't replicate this, I've set `useBrowserFullscreen=false`, and the thumbnails are working.

**Comment by achtan** [comment]
can u try it with only two images in gallery?

**Comment by xiaolin** [comment]
I just tried it with two images, and still unable to replicate with `useBrowserFullscreen=false`

**Comment by achtan** [comment]
problem was in my css... we van close this one,
