### ISSUE TITLE
Cannot set size

### ISSUE THREAD

**Issue by axelerate** [xiaolin/react-image-gallery#172]
I have tried looking up the rather obscure practice of specifying img sizes using HTML5's sizes and srcSet and have been not been able to successfully apply to the gallery's image. Is there any way to scale an image to a predefined size?

**Comment by zcgu** [comment]
Also tried to use sizes parameter but out of luck. Then I override the `renderItem` to set the height and it works:

```
_renderItem(item) {
    return (
      <div className='image-gallery-image'>
        <img
            // other props...
            style={{ width: '100%', height: height, objectFit: 'contain' }}
        />
      </div>
    )
  }

<ImageGallery
    // other props...
    renderItem={this._renderItem}
/>
```
I believe you can do the same thing to width as well.

**Comment by xiaolin** [comment]
Browsers will cache the sizes so if a larger size is already loaded, it won't attempt to load the lower resolution one despite the change in width. If you want to see your `srcSet` in action, I suggest you first open your browser in incognito mode set the width of the browser then load the gallery to test.

Using below as an example if you open incognito mode and adjust your browser to  <= 420width then load the gallery `my_image_420.jpg` will load first.

`srcSet: "my_image_1024.jpg 1024w, my_image_420.jpg 420w",`

**Comment by xiaolin** [comment]
Closing this, feel free to reopen if necessary.
