### ISSUE TITLE
Lazy Load False for more than 85 images causes iOS Safari/Chrome to crash

### ISSUE THREAD

**Issue by jam35L** [xiaolin/react-image-gallery#175]
First off, thank you for making this wonderful React Component. You've done a great job!

The issue:
When loading a lot of images and lazy load is set to false, iOS browsers will crash.

Cause:
iOS browsers are limited to ~10mb of GPU accelerated image elements.
You can read more about that [here](https://medium.com/@MerciMichel/don-t-abuse-enabling-gpu-acceleration-on-ios-95520da2428)

So we if we set lazy load to false and have a lot of images, it will create 1 browser layer for each image. Memory usage would depend on the display size of the image.

GPU acceleration is enabled when using css **translate3d**.

Fix:
Use **translate** instead of **translate3d**.
I took a peek at the code on **ImageGallery.jsx** and **translate** is enough since Z position is not really used.
I've tested it locally and it doesn't cause any issues.

I hope you can have this fix in. Would greatly appreciate that. I can also do the fix myself if you want.

Cheers.

**Comment by jam35L** [comment]
Pull request created [here](https://github.com/xiaolin/react-image-gallery/pull/176)

**Comment by xiaolin** [comment]
merged #176
