### ISSUE TITLE
Only Video

### ISSUE THREAD

**Issue by deathlover** [xiaolin/react-image-gallery#179]
Can videos be used in slider directly? if yes? what should be done?

**Comment by xiaolin** [comment]
Take a look at the example app.js file and see how youtube videos are implemented.

https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js

**Comment by deathlover** [comment]
thank you for reply.

New in react js could you please help me with the syntax for calling this syntax for calling the script.

 <ImageGallery showVideo = {true} item=[{embedUrl:url1, embedUrl:url2}]/>

**Comment by xiaolin** [comment]
I suggest doing some tutorials in react to understand it better. The `showVideo` state does not belong to `ImageGallery` but belongs to the example `App` component.

**Comment by deathlover** [comment]
Had succesfuly implemented for series of images

Trying to create a gallery of only videos, had tried every possible way. but no success.

Can you please help me with, how to give a call for your mentioned URL.

**Comment by xiaolin** [comment]
You need to override the `renderItem` property and render your own component within that custom renderer. See documentation about `renderItem` for more information and https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js#L140

**Comment by deathlover** [comment]
Thanks @xiaolin  
Successful with rendering of all type of media.
Excellent library.

**Comment by xiaolin** [comment]
awesome! I'm closing this.
