### ISSUE TITLE
Re-render entire gallery

### ISSUE THREAD

**Issue by tamirhuber** [xiaolin/react-image-gallery#182]
Hello,

I'm getting the images via user url input, and when the user changes the url, i would like the entire gallery to render itself to the new images array.
the app.state.items is changing as well as the Gallery prop, but somewhat the ImageGallery is not.

`export default class Gallery extends React.Component`
`{`
` render() {`
`    return (`
`        <div>`
`        Gallery      `
`        <ImageGallery items={this.props.items} slideInterval={this.props.slideInterval}/>`
`        </div>`
`    );`
`  }`
`}`

Thanks

**Comment by xiaolin** [comment]
You'll need to re-render the gallery when your `items` change you should be using this.state.items in your custom `Gallery` component

```
export default class Gallery extends React.Component {
  constructor() {
    super();
    this.state = {
      items: [your images]
    }
  }

  updateMyImages(images) {
     this.setState({items: images})
  }
  return (
    <div>
       <ImageGallery items={this.state.items} />
    </div>
  );
}
```
