### ISSUE TITLE
LazyLoading doesn´t work at all

### ISSUE THREAD

**Issue by mpluempe** [xiaolin/react-image-gallery#183]
Hi, I´m sorry to bother (kind of last resort thing here for me), but although the lazyLoad-Prop is set to true, at all times all images are instantly loaded. I´m not talking about thumbnails, but the original images!
I´m working with version 0.7.15, but tried to use other versions as well. But it was always the same thing, all images loaded instantly.

**Comment by xiaolin** [comment]
I just tried the example and its working for me. I checked the network tab on chrome to make sure the other image slides did not load.

**Comment by mpluempe** [comment]
I guess i found out what my mistake is. I expected just one image to be loaded, when lazyLoad is activated, but it seems there are three images loaded to start the gallery. Most of the galleries I have only have three images, so you can see my confusion. Matter of fact this is a no-go for my client...

sry to have you bothered and thx for the component and your answer to my query!
Have a nice weekend!
