### ISSUE TITLE
can't get renderRightNav working..

### ISSUE THREAD

**Issue by tamirhuber** [xiaolin/react-image-gallery#184]
hey,

I have got the following component - 

```
export default class Gallery extends React.Component {
  render() {
    return (
        <div className="gallery" >
        <ImageGallery ref={i => this._imageGallery = i} items={this.props.items}    
        showFullscreenButton={false} showPlayButton={false} showThumbnails={false}  />
        </div>
    );
  }
}
```

and i tried to add the renderRightNav function since i need to update the state as it pressed and cant figure out where and how to use it. 
Thanks

**Comment by xiaolin** [comment]
`renderRightNav` is passed in as a prop, take a look at the src and get that working first, then you can try overriding it


Use below for example (untested).
```
    myRenderRightNav = (onClick, disabled) => {
      return (
        <button
          type='button'
          className='image-gallery-right-nav'
          disabled={disabled}
          onClick={onClick}
          aria-label='Next Slide'
        >Hey My own button </button>
      );
    };

  <ImageGallery renderRightNav={myRenderRightNav}/>
```

**Comment by tamirhuber** [comment]
ok, thanks.
and how can i use the getCurrentIndex function inside myRenderRightNav?

**Comment by xiaolin** [comment]
Using the ref you assigned `this._imageGallery.getCurrentIndex()`

**Comment by tamirhuber** [comment]
OK, for some reason it didn't work, I'll try to figure it out later. 
Thanks

**Comment by xiaolin** [comment]
make sure  you use an arrow function for your `myRenderRightNav` or you'll have to add a bind for it `<ImageGallery renderRightNav={myRenderRightNav.bind(this)}/>`

**Comment by tamirhuber** [comment]
Yes I know. I'll try to get it to work and be in touch. Thanks again

**Comment by tamirhuber** [comment]
I've added and bind it as you said above, but still can't figure out where to add my  custom code, for example i would like to alert when clicking on the next nav, but if i just add alert function it fires right when page load.

**Comment by tamirhuber** [comment]
Ok, so i figured out that as it runs, `this._imageGallery` is set to null and only after a moment it get the object.  And managed to use the renderRightNav, but somehow i cant add custom functions to it without be fired onload. I did - 

```
myRenderRightNav = (onClick, disabled) => {
      var index = this._imageGallery.getCurrentIndex(); // this._imageGallery == null  ???
return (
        <button
          type='button'
          className='image-gallery-right-nav'
          disabled={disabled}
          onClick={onClick, alert("Hello") } // fires onload on NOT onclick..
          aria-label='Next Slide'
        >Hey My own button </button>
      );
    };
```
