### ISSUE TITLE
Hover on image doesn't stop animation

### ISSUE THREAD

**Issue by tomasztomys** [xiaolin/react-image-gallery#185]
Hover on image doesn't stop animation (but docs tell that animation should pause if hover). Can you fix it?

**Comment by xiaolin** [comment]
This was removed on purpose back in #71  where in the docs does it say it will pause on hover?

You can also add it yourself by adding a onhover on a container element that wraps ImageGallery and calling `pause()`, `play()`

**Comment by xiaolin** [comment]
Ah its the play function docs, I have to update that!

**Comment by tomasztomys** [comment]
I think that it should be in "standard", even default

**Comment by xiaolin** [comment]
Ideally would like help on this. The ideal solution should cover these cases

- `onmouseover` stop the current slide (only if its playing)
- `onmouseleave` resume the current slide (only if its playing)
- `onmouseover`/`onmouseleave` events are not activated on touch screens

**Comment by TheDolo** [comment]
I would actually like to hover on image to start play(), and no hover stop(), if possible!

**Comment by xiaolin** [comment]
Opening the option to add `onMouseOver`, and `onMouseLeave` as props to slides and closing this.
