### ISSUE TITLE
any way to add title attribute to images?

### ISSUE THREAD

**Issue by tamirhuber** [xiaolin/react-image-gallery#186]
I would like to use the html title attribute on the images in the gallery, is there a way to add them?

**Comment by xiaolin** [comment]
To add it now you would have to override the `_renderItem` method and add a title property. 

I'll add a todo and try to get this in the next release.

**Comment by xiaolin** [comment]
In the latest release `0.8.1` you can pass down props `originalTitle`, and `thumbnailTitle`
