### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by harrington101** [xiaolin/react-image-gallery#187]
I recently had an audit on my website for accessibility and this component did not pass for a couple of reasons. Can we update it so that it passes? 

**1. Invisible content read out by Screen reader**
The captions for the slides that are off the edge of the page are being read by the screen readers before they appear on the page. Could we add an aria-hidden attribute or display:none to the off screen slides?

**2. Unclear functionality of slideshow controls**
The auditor is suggesting that the slideshow have headings within the image-gallery-slides and image-gallery-slide-wrapper divs that are only visible to screen readers. These headings would be something like `<h2 class="screenreaderonly">Slideshow</h2>` and `<h2 class="screenreaderonly">Slide Controls</h2>`. They also suggest adding a hidden instruction for screen readers that says "Clicking on the slideshow controls will update the slide content above."

**3. Missing keyboard support for image links**
The auditors suggest moving the tab from the bullets to the images.

**4. Does not comply with W3 Validation.**
- Bad value "navigation" for role
- Button not allowed inside of ul. Must have li.
- Section "image-gallery" lacks a heading (h2-h6).

**Comment by xiaolin** [comment]
Feel free to open a pr for this.

**Comment by sureshHARDIYA** [comment]
Ran into same issue on my apps too. I would be great to have included.

**Comment by xiaolin** [comment]
I fixed 4 in a recent commit.

**Comment by xiaolin** [comment]
Closing this as 1, 2, and 3 lacks formal requirements. Please open a PR with changes if there are further accessibility issues
