### ISSUE TITLE
Allowing markup on description

### ISSUE THREAD

**Issue by sureshHARDIYA** [xiaolin/react-image-gallery#193]
I see the issue about [allowing markup as already been closed here](https://github.com/xiaolin/react-image-gallery/issues/25).  

I am using the package to render slideshow on my application. Has served my purpose except there are few problems I came across recent:

1. I need to render description that contains links and and normal HTML tags `[strong, i, em]` 
2. Description needs to be selectable. Currently it renders the description but it you can not really select the description. By select I mean, if someone tried to copy the description, you really can not. It appeared the text were part of image not the text node. 

Injecting `html` can be dangerous but what about using filters like [sanitize html](https://github.com/zacharystenger/sanitize-html-react) or [KlarnaUI](https://klarna.github.io/ui/#html2KlarnaUI) to sanitise the description. When a package user knows what description is being rendered is safe, we should allow the possibility to add markup IMO.  Like to know your thoughts on this. Thanks in advance.

**Comment by xiaolin** [comment]
You can use the custom render method to render any kind of description html you like, look at the readme documentation on `_renderItem`

The reason description is currently not selectable is because there is a css applied to the gallery with `user-select: none`. You can override that and you'll be able to select it.

**Comment by sureshHARDIYA** [comment]
Yes, I saw the alternative approach on the documentation. Thanks for linking me again. I guess that serves my purpose, but still would be happy to see package going towards ease of use. I will close the issue. Thanks. :)
