### ISSUE TITLE
Any way to prevent Fullscreen? 

### ISSUE THREAD

**Issue by JordyVialoux** [xiaolin/react-image-gallery#194]
Is it possible to prevent fullscreen but still have the images resize to a larger size? Like a lightbox almost? I've been trying to edit the raw .jsx file and the changes won't display.

**Comment by xiaolin** [comment]
You can turn off the fullscreen feature and implement your own lightbox by adding an `onClick` to the gallery properties.

**Comment by Aliprd92** [comment]
Hi 
How to turn off the fullscreen feature ?

**Comment by Aliprd92** [comment]
> You can turn off the fullscreen feature and implement your own lightbox by adding an `onClick` to the gallery properties.

Hi
how to  turn off the fullscreen feature ?

**Comment by SkaGitWork** [comment]
showFullscreenButton: Boolean, default true
