### ISSUE TITLE
Problems with full-screen mode

### ISSUE THREAD

**Issue by SemenKireev** [xiaolin/react-image-gallery#195]
(Translated from Russian by Google)
Hi. I'm having problems with working in full screen mode. That it was understandable in what I provide the screenshots. I use the package with a Twitter Bootstrap.
![2017-05-19 11-45-09](https://cloud.githubusercontent.com/assets/10635206/26233809/31a0ef0c-3c8a-11e7-8173-d40db75cd5c0.jpg)
![2017-05-19 11-45-18](https://cloud.githubusercontent.com/assets/10635206/26233814/36693fa8-3c8a-11e7-8a42-3bf0365bd54d.jpg)

**Comment by xiaolin** [comment]
The first screenshot can be fixed with some css adjustment.

I'll add some logic so its a bit smaller on mobile for the next release.

I'm not sure whats going on in the second screenshot, I'm not sure why your thumbnails are out of view. Its not happening in the [demo](http://linxtion.com/demo/react-image-gallery)

**Comment by SemenKireev** [comment]
Yes, in the demo version everything works fine. Maybe something from other packages affects the work.
Interestingly, in the browser Mozilla (tested on the versions under Windows and Ubuntu) full-screen mode also works poorly, this also applies to the demo version.
![2017-05-20 17-26-49](https://cloud.githubusercontent.com/assets/10635206/26275070/93b014fe-3d82-11e7-9825-6ea8d5852555.png)
![2017-05-20 17-27-21](https://cloud.githubusercontent.com/assets/10635206/26275071/995ccf64-3d82-11e7-8b8d-94ed5693638f.png)

**Comment by xiaolin** [comment]
Full screen on the demo might not fit in your screen, you'll have to adjust the css.

If your monitor is above 2000px it will stretch the gallery because its set to have 100% width. Its up to you to adjust the fullscreen css to fit all your required screen sizes.

**Comment by xiaolin** [comment]
This is now fixed in the latest release v0.8.1
