### ISSUE TITLE
SVG icons instead of font

### ISSUE THREAD

**Issue by jahglow** [xiaolin/react-image-gallery#199]
Hi, please make all the icons use svg icons from material.io/icons instead of a font. Today font didn't load from repo and shows boxes instead of font characters. There won't be a performance overhead if you just paste in svg code into JSX inside button tags and expose their hover color class to be overriden. I think that would definitely save another load for external server and reduce the redundant css in that case. Shadow isn't supported in svg with css cross browser but you may well use SVG stroke to give them an outline to stand out on white background.

**Comment by xiaolin** [comment]
@jahglow you can override the icons using css, and the provided functions.
