### ISSUE TITLE
Provide onThumbnailClick prop

### ISSUE THREAD

**Issue by 4muzar** [xiaolin/react-image-gallery#200]
Hi!

This component is awesome and fits to my project nearly perfect.
But in my case I have to hide main image, show only thumbnails and enter to full screen mode on thumbnail click.

So I suggest to add `onThumbnailClick` and `hideMainImage` props. `slideWrapper` has to be shown on full screen mode.
Having these props, I can do the rest of work by myself.

What do you think about these features?

I can implement it and create PR.
Thank you!

**Comment by xiaolin** [comment]
Adding a `onThumbnailClick` is okay, but `hideMainImage` is unique to your use case. You should be able to hide the the images with css.

**Comment by 4muzar** [comment]
Okay, I agree.
I'll add `onThumbnailClick`

**Comment by xiaolin** [comment]
released in version 0.8.3
