### ISSUE TITLE
Warning on unmount during resize

### ISSUE THREAD

**Issue by Arsolio** [xiaolin/react-image-gallery#203]
If you unmount component during resize, you'll got warning:

"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ImageGallery component."

It can be reproduced for example with [react-responsive](https://github.com/contra/react-responsive).  It's issue mostly for adaptive design

Check pr please : https://github.com/xiaolin/react-image-gallery/pull/202

**Comment by xiaolin** [comment]
Merged, and planning to release this tonight.

**Comment by xiaolin** [comment]
released in version 0.8.3

**Comment by Arsolio** [comment]
Thank you very much!
