### ISSUE TITLE
Swipe up/down to scroll page outside of gallery

### ISSUE THREAD

**Issue by ajmajma** [xiaolin/react-image-gallery#205]
Hello. I am implementing this gallery in a project and am running into an issue on mobile where if the user swipes up/down **inside** the gallery, it will not scroll the page up and down. Is there some way (or a good way in your opinion) to override this behavior? I would love to be able to keep the swipe left + right but also let the user swipe up/down to scroll the page. Thanks!

**Comment by xiaolin** [comment]
I'm not able to replicate this. I'm able to scroll up and down while touch is inside the gallery using the [demo link](http://linxtion.com/demo/react-image-gallery)

I'm using ios on chrome, and safari

**Comment by xiaolin** [comment]
Let me know if you are still having this issue, otherwise i'll be closing this issue soon.

**Comment by recurrence** [comment]
I've hit this issue as well.  I'll see if I can figure out what is going on here.

**Comment by ajmajma** [comment]
@recurrence I am using for my layout outside of the image gallery, are you as well? I am guessing that may be the issue.

**Comment by recurrence** [comment]
Hi @ajmajma Have you tried upgrading to the latest point release?  That actually solved the problem for me but I am unable to point to exactly why :)

**Comment by ajmajma** [comment]
@recurrence Will try right now, thanks for the heads up!

**Comment by ajmajma** [comment]
Yeah upgrading to 0.8.3 fixes this for me. Thanks!
