### ISSUE TITLE
react-native: Expected  a compenent class ,got [object object]

### ISSUE THREAD

**Issue by sunny635533** [xiaolin/react-image-gallery#211]
## I want to add it with  React native, maybe this library should uesd in React ,not RN?
`
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import ImageGallery from 'react-image-gallery';
// var ImageGallery = require('react-image-gallery');

export default class Ausesome extends Component {
  render() {
    const images = [
      {
        original: 'http://lorempixel.com/1000/600/nature/1/',
        thumbnail: 'http://lorempixel.com/250/150/nature/1/',
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/2/',
        thumbnail: 'http://lorempixel.com/250/150/nature/2/'
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/3/',
        thumbnail: 'http://lorempixel.com/250/150/nature/3/'
      }
    ];
    return (
      <ImageGallery
        items={images}
        slideInterval={2000}
      // onImageLoad={this.handleImageLoad}
      />
    );
  }
}

AppRegistry.registerComponent('Ausesome', () => Ausesome);
`

**Comment by xiaolin** [comment]
This library is not compatible with react native. Sorry 😞

**Comment by xiaolin** [comment]
I wonder if there is a polyfill for these type of thing. Basically elements like `div` are unrecognized in react-native.

**Comment by sunny635533** [comment]
@xiaolin thanks to answer.I feel sorry to hear that.I will use another library.
