### ISSUE TITLE
Images of bigger resolution couldnt be viewed properly when maximised

### ISSUE THREAD

**Issue by smilingpigs** [xiaolin/react-image-gallery#215]
Hello there, when uploaded images that are of longer heights, the images couldnt be viewed on a whole in the maximised mode, is there anyway I can scroll these images or set a standard width and height for these images when maximised?

**Comment by xiaolin** [comment]
You can override the styles with css to limit the height of your images.

**Comment by smilingpigs** [comment]
By defining the style to 'originalClass'? This 'originalClass' refers to the original image right?

**Comment by xiaolin** [comment]
Yes

**Comment by smilingpigs** [comment]
Thanks
