### ISSUE TITLE
Flying image, when trying back from 2+ image to first one.

### ISSUE THREAD

**Issue by traceur91** [xiaolin/react-image-gallery#217]
When I'm looking at second or further image in the gallery and when I'm going back to first one, by clicking on thumbnail or dot, there is an odd 'flying image' visible at first plan.

**Comment by JMazarati** [comment]
@traceur91 Have you found a solution? I think I've got the same problem when there are four images in gallery and I click on third thumbnail there is 'flying image' (and when back on the first thumbnail - also the same issue but works normally in other cases )

**Comment by xiaolin** [comment]
fixed in version 0.8.4
