### ISSUE TITLE
Put forward a little advice.

### ISSUE THREAD

**Issue by varrant** [xiaolin/react-image-gallery#218]
提出一点意见。
1.能否加一个旋转图片的功能？
2.图片加载完之前，用loading小图标显示，是否更好？
3.图片的拉伸是按比例拉伸的吗？

Put forward a little advice.
1. Can you add a function to rotate the picture?
2. Before loading the image, use the loading icon to show that it is better?
3. Is the stretch of the picture drawn in proportion?

**Comment by xiaolin** [comment]
> 1. Can you add a function to rotate the picture?

**What do you mean by this? Rotate upside down?**
> 2. Before loading the image, use the loading icon to show that it is better?

**That seems like a good feature, I will consider adding this when I get some time.**
> 3. Is the stretch of the picture drawn in proportion?

**All images, are set to 100% width of the container, so it will be in proportion.**

**Comment by varrant** [comment]
rotate 90  degree or other self-defined degree  from Clockwise or counterclockwise。

**Comment by xiaolin** [comment]
Sorry, rotating images is out of the scope of the gallery so I won't be adding it.
