### ISSUE TITLE
Strange thumbnails position in fullscreen (useBrowserFullscreen === false)

### ISSUE THREAD

**Issue by eljusto** [xiaolin/react-image-gallery#222]
Here is a video https://yadi.sk/i/1xTzkUm43NKW5W
I'll try to reproduce it with repo example.

**Comment by xiaolin** [comment]
Let me know if you can reproduce, this error looks odd to me.

**Comment by xiaolin** [comment]
Closing this, feel free to open if you can reproduce.

Thanks
