### ISSUE TITLE
First image with last image above when using on smartphone

### ISSUE THREAD

**Issue by witalobenicio** [xiaolin/react-image-gallery#227]
<img width="375" alt="captura de tela 2017-11-01 as 08 45 02" src="https://user-images.githubusercontent.com/4964291/32273379-08e840ae-bee1-11e7-99f2-d2727594d2b8.png">

Just like this!

**Comment by xiaolin** [comment]
I noticed you have different size images which is not automatically supported. I recommend cropping your images to the same dimensions, or use custom css to limit the max width, and height.
