### ISSUE TITLE
Thumbnails not rendering on page load until i mess with screen width

### ISSUE THREAD

**Issue by JiniHendrix** [xiaolin/react-image-gallery#228]
In the words of Marvin Gaye, whats goin on?????

**Comment by xiaolin** [comment]
Maybe something with your build? Its working fine in the demo
http://linxtion.com/demo/react-image-gallery/

**Comment by JiniHendrix** [comment]
it doesnt work when the thumbnails render on the right or left side of the image. it works fine when they render on the bottom and top. @xiaolin

**Comment by JiniHendrix** [comment]
Here is my component with props plus an image.
<ImageGallery
          items={images}
          thumbnailPosition="right"
          showFullscreenButton={false}
          showPlayButton={false}
          onSlide={this.handleSlide}
          onThumbnailClick={this.handleThumbnailClick}
        />

<img width="473" alt="screen shot 2017-11-02 at 6 58 29 pm" src="https://user-images.githubusercontent.com/16394190/32358073-ed06f1e4-bfff-11e7-86cb-c6253dc0af5f.png">

**Comment by xiaolin** [comment]
Seems like a css issue on your end, did you debug and see if you can find the element below in your browser debugger?
`<div class="image-gallery-thumbnails">`

**Comment by JiniHendrix** [comment]
yeah, that element is on the DOM but it's 0 height, although the container that directly contains the images is properly rendered with all the images. I've been trying to use a workaround by setting the height manually after the gallery renders, but the scroll offset is not correct.

**Comment by JiniHendrix** [comment]
Nope can't find anything messing with the styling of that element.

**Comment by JiniHendrix** [comment]
I just isolated the problem actually, and it's this. when I hardcode image urls it works fine, but when I load images from a backend the image-gallery-thumbnails element height is 0.

I suspect this is because the the height of that element is being set while the images are being fetched, and since no image is rendered in the main display and the element's height is being set from the main display, the height is set to the imageless main display height which is 0.

Will try to find a workaround.

**Comment by JiniHendrix** [comment]
my workaround is to conditionally render the ImageGallery component with the image array.length as the condition.
