### ISSUE TITLE
Swiping vertically is being detected as a horizontal swipe

### ISSUE THREAD

**Issue by kamui** [xiaolin/react-image-gallery#229]
With the latest flick detection change in 0.8.4 and 0.8.5, vertical swipes going down are now being detected as horizontal flicks unless the swipe is _exactly_ vertical. If it's offset by a little bit, it'll still trigger the slide swipe.

So every time you swipe to scroll the page, if there's a carousel in the frame, it'll scroll the carousel.

**Comment by xiaolin** [comment]
Thanks for reporting this. I was using `preventDefaultTouchmoveEvent={true}` which prevented the scrolling of the page when touching inside the gallery, and didn't notice the odd behavior when it was off. Will look into this.
