### ISSUE TITLE
strange animation when holding down the arrow key

### ISSUE THREAD

**Issue by saussayjesica** [xiaolin/react-image-gallery#230]
I've noticed a strange behaviour when the slide transitions if you continuously hold down the arrow key. Sometimes the next slide doesn't slide into screen. It just appears with no animation. Other times, the next slide appears to have been loaded underneath the current slide so the animation looks odd

![media-gallery-issue](https://user-images.githubusercontent.com/26707526/33153843-786d503c-d038-11e7-8c2e-6761d4e79e6d.gif)

**Comment by saussayjesica** [comment]
@xiaolin this only seems to occur when infinite is set to true

**Comment by saussayjesica** [comment]
@xiaolin adding an extra 100ms to _onSliding seems to help
 ` _onSliding = () => {
    const { isTransitioning } = this.state;
    window.setTimeout(() => {
      if (isTransitioning) {
        this.setState({isTransitioning: !isTransitioning});
      }
    }, this.props.slideDuration + 100);
  };`

**Comment by xiaolin** [comment]
@saussayjesica I think adding 50ms should be enough too. Feel free to open a pr.

**Comment by xiaolin** [comment]
closing via #235
