### ISSUE TITLE
Unable to get working with Webpack3, React 16, Typescript, soln to modify package.json

### ISSUE THREAD

**Issue by shudson250** [xiaolin/react-image-gallery#234]
Using Webpack 3.5.1, React 16 and Typescript, I am unable to get a basic example to work. My import statement seems to import the css file instead of the js file. I feel that the codebase shouldn't rely on correct user loader settings, but instead be more specific on which file is the main file by specifying it in the package.json.

Code:
```
import ImageGallery from 'react-image-gallery';
console.log('ImageGallery: ', ImageGallery); // see below for output
...
render () {
 return (<ImageGallery.default items={[
  {
    original: 'http://lorempixel.com/1000/600/nature/1/',
    thumbnail: 'http://lorempixel.com/250/150/nature/1/',
  },
  {
    original: 'http://lorempixel.com/1000/600/nature/2/',
    thumbnail: 'http://lorempixel.com/250/150/nature/2/',
  },
  {
    original: 'http://lorempixel.com/1000/600/nature/3/',
    thumbnail: 'http://lorempixel.com/250/150/nature/3/',
  },
]}
/>)}
```

Results in error 
`
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
`

The console log above outputs the following, which looks like a css object:
```
Object {
  active: "image-gallery__active___weOlL",
  center: "image-gallery__center___2SaSU",
  image-gallery: "image-gallery__image-gallery___1zoQc",
  image-gallery-bullet: "image-gallery__image-gallery-bullet___39o_N",
  image-gallery-bullets: "image-gallery__image-gallery-bullets___2cls4",
  image-gallery-bullets-container: "image-gallery__image-gallery-bullets-container___13Wvu",
  image-gallery-content: "image-gallery__image-gallery-content___3iLFJ",
  image-gallery-description: "image-gallery__image-gallery-description___3PRZ0",
  image-gallery-index: "image-gallery__image-gallery-index___3_Eqw",
  image-gallery-left-nav: "image-gallery__image-gallery-left-nav___FBVYr",
  image-gallery-right-nav: "image-gallery__image-gallery-right-nav___2yX1G",
  image-gallery-slide: "image-gallery__image-gallery-slide___jTaER",
  image-gallery-slides: "image-gallery__image-gallery-slides___-Xzxx",
  image-gallery-thumbnail: "image-gallery__image-gallery-thumbnail___yaBJs",
  image-gallery-thumbnails: "image-gallery__image-gallery-thumbnails___2iZ4m",
  image-gallery-thumbnails-container: "image-gallery__image-gallery-thumbnails-container___3TaWC",
}
```

To fix this, I manually changed the package.json to target the .js file directly:
```
"version": "0.8.6",
  "description": "React carousel image gallery component with thumbnail and mobile support",
  "main": "./build/image-gallery.js",
...
```

My webpack config is largely similar to this:
https://github.com/BaristaLabs/react-scripts-ts/blob/master/config/babel-presets.js

If anyone has a suggestion how to accomplish with my loader settings as opposed to altering the package.json file, I'm all ears. As mentioned above, my feeling is that the package should be more specific on the main file to avoid these types of issues.

**Comment by xiaolin** [comment]
Feel free to open a pr to update the main to be explicit of file extension

**Comment by xiaolin** [comment]
I've updated the target to be a specific .js file
