### ISSUE TITLE
Question regarding heic / renderThumbInner

### ISSUE THREAD

**Issue by MarcelMitzkus** [xiaolin/react-image-gallery#238]
Hello,

i've two questions regarding the component.
Will heic be supported ? 
Can anyone provide an example where renderThumbInner is passed as a prop to ImageGallery. With some modification. My goal is to render a checkbox on the thumbnail.

Thanks in advance.

**Comment by xiaolin** [comment]
@MarcelMitzkus 

* Will HEIC be supported?
Once browsers support it, sure.

* Can anyone provide an example where renderThumbInner is passed as a prop to ImageGallery. With some modification. My goal is to render a checkbox on the thumbnail.
Take a look at the `renderItem` function example, it is very similar.
