### ISSUE TITLE
Extra controls in thumbnails tray

### ISSUE THREAD

**Issue by jrock17** [xiaolin/react-image-gallery#242]
I'm seeing a second set of controls (play button and full screen button) in my thumbnails tray. I have the play button disabled (which works above). But I don't want these duplicate buttons in the thumbnails tray.

Any thoughts?
![2017-12-23_14-09-13](https://user-images.githubusercontent.com/1270524/34322986-1f49eb58-e7eb-11e7-9b83-819779545256.jpg)

**Comment by xiaolin** [comment]
That is odd the controls only render once, I'm unable to replicate.

**Comment by jrock17** [comment]
My bad, user error. Turns out I was calling the component twice.

Thanks for the reply!
