### ISSUE TITLE
How to support usage in an rtl language?

### ISSUE THREAD

**Issue by wissog** [xiaolin/react-image-gallery#243]
Hey,
currently when applied in an rtl language page/div, the scrolling and thumbnails direction remains LTR.
is there any support for this which i've missed? :)

**Comment by xiaolin** [comment]
Whats LTR?

**Comment by sag1v** [comment]
@xiaolin 
LTR -> Left To Right
RTL -> Right To Left
I was about to open an issue about `RTL`  support and noticed this issue was opened 4 hours ago 😄

**Comment by wissog** [comment]
😂
When used in rtl, the thumbnails when they're on top, still run ltr and
also image scrolling remains ltr

**Comment by sag1v** [comment]
@xiaolin did you understand the issue mate?

**Comment by xiaolin** [comment]
From what I gather the ideally the thumbnails should support RTL languages. In terms of `showIndex` that can be modified using css to be anywhere you like.

**Comment by wissog** [comment]
Yes, and also the traversal on the images should be the opposite way from
right to left

**Comment by xiaolin** [comment]
@wissog So the sliding of images should change from LTR -> RTL, and from RTL -> LTR?

**Comment by sag1v** [comment]
@xiaolin i think the index should change as well. the counting is backwards.
For example it shows `1/5` instead of `5/5`

**Comment by xiaolin** [comment]
Yes, if the last image starts first, the index should show 5/5.

**Comment by wissog** [comment]
yea exactly, that's the point of RTL 😁
e.g. the left slide button should move to next image and the right button
should move back.



*Gabi*

*"What R we living for?" :)*

**Comment by wissog** [comment]
Hi,
thanks for the fix.
i just tried it for hebrew (rtl), the indexes change nicely, but still the
thumbnails go the LTR way.
i have the thumbnails on top

please advise

*Gabi*

*"What R we living for?" :)*
