### ISSUE TITLE
Swipe problems

### ISSUE THREAD

**Issue by caiobatis** [xiaolin/react-image-gallery#244]
I'm trying to use Swipe to pass the slides but the disableSwipe property does not work. Nor in the example: http://linxtion.com/demo/react-image-gallery/

**Comment by xiaolin** [comment]
`disableSwipe` removes the swipeable feature from the gallery and its working for me. Are we talking about the same thing here?

**Comment by caiobatis** [comment]
I'm trying to use the swip, to pass the images on the mobile. I tested the example and it did not work

**Comment by xiaolin** [comment]
Can you show me an example screen shot of what you mean?

**Comment by caiobatis** [comment]
![screen shot 2018-01-01 at 13 17 14](https://user-images.githubusercontent.com/9372750/34468725-3bfe533a-eef6-11e7-8b9a-e1c937c7701c.png)
<img width="350" alt="screen shot 2018-01-01 at 13 16 54" src="https://user-images.githubusercontent.com/9372750/34468726-3c243014-eef6-11e7-902b-11221fb4640b.png">

I want to be able to move to the next image using Swip.

**Comment by xiaolin** [comment]
Are you saying the swipe feature is not working on your phone?

**Comment by caiobatis** [comment]
Thanks, I solved with CSS properties, the component is perfect

**Comment by honia19** [comment]
> Thanks, I solved with CSS properties, the component is perfect

what's property, now I have the same issue

**Comment by whoishoa** [comment]
@caiobatis What css properties did you use? I'm having the same problem
