### ISSUE TITLE
Allow mouse swiping

### ISSUE THREAD

**Issue by jorrit** [xiaolin/react-image-gallery#247]
react-swipeable supports the `trackMouse` prop so desktop or hybrid device users can swipe using the mouse instead of touch. Could this property be exposed by react-image-gallery? It is simple so I could make a PR, but I would like to know if you like a on-by-default behavior or off-by-default.

**Comment by MarioAraya** [comment]
You already can swipe with mouse, on Chrome at least, just make sure you are in "mobile device mode" in the Chrome Developer Tools

**Comment by jorrit** [comment]
That is right, swiping with the mouse works in emulate mode. With `trackMouse` it will also work when not emulating so regular desktop users can use it as well.

**Comment by xiaolin** [comment]
I tried the `trackMouse` feature awhile back and it does not work well. The drag/hold is a bit bugging when trying to swipe through images.

**Comment by jorrit** [comment]
I noticed that too, but I thought it was better than nothing.

**Comment by xiaolin** [comment]
Will be closing this as the `trackMouse` prop on `react-swipeable` does not function well.

**Comment by konsalex** [comment]
Have this been implemented? Desktop mouse swipe would be helpful without custom function
