### ISSUE TITLE
Question, ¿How can I pass another array of ImagesUrls[] to loop, not listed in thumbnails?

### ISSUE THREAD

**Issue by MarioAraya** [xiaolin/react-image-gallery#248]
Hi, congratulations for your beautiful code,

please ¿can you help me to loop through a list of images not initially added to the this.images property? I don't know where to begin

Thanks!

**Comment by xiaolin** [comment]
I'm not sure what you mean, I would try

**Comment by MarioAraya** [comment]
I do it in a different way, just instantiating multiple times with different images[] 

thanks anyway.
