### ISSUE TITLE
Can original/thumbnail url accessors be changed?

### ISSUE THREAD

**Issue by smoleniuch** [xiaolin/react-image-gallery#250]
Hi,
First of all, thank you for the awesome work!

I was wondering if there is any way to change url accessors for items property.

If i would like to get original url i would change it through props like this:

```javascript
const Images = [

  { url:'some-image-url.com/1', description:'example1' },
  { url:'some-image-url.com/2', description:'example2' }

]

const accessors = {
 original:'url'
}

<ReactImageGallery 
   items={images}
   accessors={accessors}
/>
```
Can something similiar be done through existing api?
Is it worth of implementing in future if there is no way this can be done right now?

I know you can map items before passing it to the gallery but this is a little bit cumbersome.

**Comment by xiaolin** [comment]
I don't think something similar can be done through existing api. I don't believe this feature is worth implementing as most users would not have an existing array of images that you have.

**Comment by smoleniuch** [comment]
I know that they will not have same structure of images as in the specified example.If im fetching images from external source i would have to map through them and update them according to react-image-gallery component needs.

Maybe im just overthinking, i will close it.

**Comment by xiaolin** [comment]
Yeah, mapping through the external source to update the fields should be really quick. I wouldn't worry too much about it.
