### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by mansern** [xiaolin/react-image-gallery#251]
There should be video support just like images. On clicking the video screenshot, video should be played. Anyone working on this thing?

**Comment by xiaolin** [comment]
I'm not sure what you mean, the demo shows an example of video support. There is also sample code showing how to implement a video slide.

**Comment by xiaolin** [comment]
Closing, feel free to open if this does not solve your issue.

**Comment by mansern** [comment]
It's fixed. Thanks.

**Comment by urjit0204** [comment]
Is there any way to possibly support s3 video or any other video rather than the youtube iframe? @xiaolin
