### ISSUE TITLE
Set size of height based on width

### ISSUE THREAD

**Issue by gadzhimari** [xiaolin/react-image-gallery#252]
Hi. I wanna say thank you for great library. I have one question. Is any possibilities to set height the same size as a width(for example 400x400 and etc.) I mean to do those as square. Not statically set size through the css. Maybe I should add own method as a props in original source code and listen handleResize method.

**Comment by xiaolin** [comment]
Hmm, I'm not 100% sure what you mean. Do you have different image sizes and want to keep them all the same height as their width?

**Comment by gadzhimari** [comment]
No, I want to set all a wrapper of image set height as the same as width.

**Comment by Adamkzh** [comment]
Really nice library.
Is there any way to resize the image in the library??  like change the height and the width of the gallery?
