### ISSUE TITLE
Can I start slider with the specific image from images array?

### ISSUE THREAD

**Issue by saleemnasa** [xiaolin/react-image-gallery#253]
I have an array of images in a list, When a user selects an image I need to show image slider with the selected image opened. But in this the slider is starting from the first image. Anyone to help?

**Comment by xiaolin** [comment]
You can use the `startIndex` prop to set a different index other than `0`.

**Comment by saleemnasa** [comment]
That's awesome, thanks for your help and Everything is working well.

But after loading image slider with _startIndex_ other then 0 the thumbnail's list is moving to left and coming to its normal place. Can you help me fixing this too?

**Comment by saleemnasa** [comment]
_disableThumbnailScroll_={true} 
worked after I use this prop
Thank You
