### ISSUE TITLE
styles not getting applied

### ISSUE THREAD

**Issue by vnallamhawk** [xiaolin/react-image-gallery#258]
Hi Team,

The styles are not getting applied.I am trying to achieve it by importing the following import '../../node_modules/react-image-gallery/styles/scss/image-gallery.scss';. i am getting module not found error.

**Comment by DragosRotaru** [comment]
+1

**Comment by xiaolin** [comment]
I would check your path to make sure `react-image-gallery` is actually in `../../node_modules/react-image-gallery/`. This seems like a  build issue, and not related to `react-image-gallery`, are you using Webpack?

**Comment by DragosRotaru** [comment]
Im using webpack and sourcing the file correctly yet it's not being
loaded.  I've tried both css imports and ES6 imports.

**Comment by xiaolin** [comment]
This seems like an issue with your webpack setup. I'm currently using webpack with this library and its working as expected.

**Comment by xiaolin** [comment]
Feel free to reopen if you can provide an example that can be reproduced.
