### ISSUE TITLE
How to load component with fullscreen enabled?

### ISSUE THREAD

**Issue by 7h3m4dS0u1** [xiaolin/react-image-gallery#260]
First thanks for your work, this is a great component.

I'm trying to start it in fullscreen, but with no success.
I tried this approach: 

```javascript
   openFullScreen = () => {
  this._imageGallery.fullScreen()
};
componentDidMount() {
    this.openFullScreen()
  };
    render() {
        return (            
            <ImageGallery ref={f => this._imageGallery = f} showThumbnails={this.state.showThumbnails} items={this.images} />            
            );
    }
}
```
The class "fullscreen" is applied by fullScreen() function, but nothing change.
The console warn: 
_image-gallery.js:482 Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture_

Do you have any idea?

thanks

**Comment by xiaolin** [comment]
I have not seen this issue before. Does the demo page fullscreen button work for you?

**Comment by 7h3m4dS0u1** [comment]
Yes the demo is ok. But i think i didn't explain myself well...

My goal is that the first thing to appear on the page is the fullscreen gallery, without having to click a button. The page will only have the fullscreen gallery, nothing more.

**Comment by xiaolin** [comment]
The fullscreen takes over the entire user screen so it needs to be prompted by a user. See
https://stackoverflow.com/questions/29281986/run-a-website-in-fullscreen-mode

I think what you might want instead is to set prop `useBrowserFullscreen` to false. Then your function call should work. This property when set to `false` uses CSS to create a fullscreen effect and not the native fullscreen API.

**Comment by 7h3m4dS0u1** [comment]
Sure! This make sense. 
Thanks.
