### ISSUE TITLE
Example appears to constrict image media to fixed height

### ISSUE THREAD

**Issue by EdwaRen** [xiaolin/react-image-gallery#261]
This looks like one of the nicest gallery packages I have seen, however, I have been running into some issues getting the gallery to properly size images. I've copied the example shown in the readme nearly word by word but the end results constrict the entire gallery to a small fixed height. My code is below

```
import React from 'react';
import {Component } from 'react';
import ImageGallery from 'react-image-gallery';
import "react-image-gallery/styles/css/image-gallery.css";

class Gallery extends Component {
  render() {
  const images = [
      {
        original: 'https://drive.google.com/uc?export=download&id=1lrnhJlSOtjNnEuvm6j7GwOBMOPl5wJk0',
        thumbnail: 'https://drive.google.com/uc?export=download&id=1lrnhJlSOtjNnEuvm6j7GwOBMOPl5wJk0',
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/2/',
        thumbnail: 'http://lorempixel.com/250/150/nature/2/'
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/3/',
        thumbnail: 'http://lorempixel.com/250/150/nature/3/'
      }
    ]


    return (
      <ImageGallery items={images} />
    );
  }

}

export default Gallery
```

The end result is something like the following where the image is squeezed into a corner. I've removed all encapsulating components of the gallery so it is unlikely anything else is affecting the gallery.

https://imgur.com/a/DkelH

Any help would be greatly appreciated!

**Comment by xiaolin** [comment]
@EdwaRen What version of react-image-gallery are you on? Based on your screenshot it seems to be an older version.
