### ISSUE TITLE
Can you provide an option to zoom the image?

### ISSUE THREAD

**Issue by rajeshnagireddy** [xiaolin/react-image-gallery#265]
Actually i'm using for documents slider, sometimes we may to zoom in the image for more clarity

**Comment by xiaolin** [comment]
I suggest using another library that handles zooming ability and override the `renderItems` property to wrap your images with the zoom functionality.

**Comment by jimjiang07** [comment]
Hi @xiaolin, do you know any library can handle the zooming properly in both desktop and mobile(pinch gesture)? It would be great if you can provide an example. Thanks!
