### ISSUE TITLE
Thumbnails not aligned correctly when items.length changes

### ISSUE THREAD

**Issue by LaurentHellebrandt** [xiaolin/react-image-gallery#267]
After every slide I do the following
```
handleSlide = index => {
    if (index >= media.length - 5) {
      this.props.onLoadMore();
    }

    this.setState({
      currentIndex: index,
    });
  };
```
This means that while the user is still sliding through the images the `items` property of the `ImageGallery` is changing. After every `onLoadMore()` there a `n` more objects in the `items` array. The state property `thumbsTranslate` is getting adjust correctly but the thumbnails does not get repositioned.
This leads to that after a while the selected thumbnail is not visible anymore.

**Comment by xiaolin** [comment]
When you load more images, are you updating the `items` property on `ImageGallery`?

**Comment by LaurentHellebrandt** [comment]
Yes

**Comment by xiaolin** [comment]
https://github.com/xiaolin/react-image-gallery/commit/26489446cfa97b20683304ec010ed1f02f54b4d9 fixes this

**Comment by LaurentHellebrandt** [comment]
Hi, I noticed that the thumbnails are not rearranged correctly after I added the next set of photos.
To reproduce this behaviour I cloned your repository and modified `example/app.js` file.

```
...
let photoId = 0;

class App extends React.Component {
  constructor() {
    super();

    this.items = [];
    this._addItems();

    this.handleOnSlide = this.handleOnSlide.bind(this);
  }

  handleOnSlide(index) {
    if (index >= this.items.length - 5) {
      this._addItems();
    }
  }

  _addItems() {
    for (let i = 0; i < 12; i++) {
      this.items.push({
        thumbnail: `https://picsum.photos/200/200?image=${photoId}`,
        original: `https://picsum.photos/600/600?image=${photoId}`,
      });
      photoId++;
    }
  }

  render() {

    return (
      <section className="app">
        <ImageGallery
          items={this.items}
          showBullets={false}
          showPlayButton={false}
          showFullscreenButton={false}
          autoPlay={false}
          preventDefaultTouchmoveEvent={true}
          onSlide={this.handleOnSlide}
        />
      </section>
    );
  }
}
...
```

This is how the app looks like:
`currentIndex`: 19
`items.length`: 36
(The selected thumbnail is out of view)

![bildschirmfoto 2018-08-16 um 09 39 03](https://user-images.githubusercontent.com/6348294/44195105-5882ae80-a138-11e8-8883-a08364006189.png)

I am not sure if this a bug or if I misunderstood the way how I should fetch the next photos and update the `ImageGallery`.
