### ISSUE TITLE
react-swipeable preventDefaultTouchmoveEvent clean up

### ISSUE THREAD

**Issue by hartzis** [xiaolin/react-image-gallery#268]
Heyo!

was going through dependants of [react-swipeable](https://github.com/dogfessional/react-swipeable) and found your lovely library.

I noticed that you needed to do some interesting things to allow the `preventDefaultTouchmoveEvent` to work:

https://github.com/xiaolin/react-image-gallery/blob/e5171084663fa0e2d6d91a0b92708f634cf079d8/src/ImageGallery.jsx#L1115-L1118

So i created a PR https://github.com/dogfessional/react-swipeable/pull/102 to hopefully clean this up. 
 I'll try to make a PR to `react-image-gallery` when the above gets merged 😺

**Comment by xiaolin** [comment]
Amazing, thank you!
