### ISSUE TITLE
"sizes" prop is not working

### ISSUE THREAD

**Issue by giuliagworld** [xiaolin/react-image-gallery#269]
Hi, I am trying to set a width and a height for the <img> tag but the "sizes" prop doesn't seem to be working. 

Here's the code:

`let images = [
  {
    original: 'https://c5.staticflickr.com/9/8768/28941110956_b05ab588c1_b.jpg',
    sizes: {
      width: 100,
      height: 100
    }
  },
  {
    original: 'https://c3.staticflickr.com/9/8583/28354353794_9f2d08d8c0_b.jpg',
  },
  {
    original: 'https://c7.staticflickr.com/9/8569/28941134686_d57273d933_b.jpg',
  }
]

let Component = (props) => (
  <div className={css(Sheet.container)}>
    <ImageGallery items={images} showThumbnails={false} showBullets={true} showIndex={true} infinite={false} />
  </div>
);`

And this is what I get: 

![screen shot 2018-04-25 at 10 43 01](https://user-images.githubusercontent.com/13138513/39238180-84292cf6-4875-11e8-8363-ee0173233ded.png)

Any chance I might be doing something wrong?

Thanks

**Comment by xiaolin** [comment]
`srcSet` and `sizes` are <img> element attributes, see
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by giuliagworld** [comment]
Thanks a lot @xiaolin !

**Comment by sdhmdh** [comment]
Hey @giuliagworld how did you fit it?
