### ISSUE TITLE
remove unsafe lifecycles

### ISSUE THREAD

**Issue by xiaolin** [xiaolin/react-image-gallery#270]

**Comment by gshilin** [comment]
But this is closed... And it's not enhancement, it's must...

**Comment by xiaolin** [comment]
This ticket is still open, I've removed the the enhancement label and will get to this as soon as I can. Can you show me a link that says `componentWillReceiveProps` will be removed in 16.7? I thought it was being removed in react 17.

**Comment by xiaolin** [comment]
It seems it will be available until react 17. Based on what I'm reading here.
https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

![screen shot 2018-12-07 at 10 00 24 am](https://user-images.githubusercontent.com/1286776/49654856-f3183d80-fa06-11e8-8464-3b0737e2034e.png)

**Comment by gshilin** [comment]
It will be available until react 17, but StrictMode already reminds about it.

**Comment by dancerphil** [comment]
`componentWillReceiveProps` can be renamed as `UNSAFE_componentWillReceiveProps` and it will still work in react 17.

But It should be removed, as it is unsafe in ConcurrentMode, which will be default open in react 17.(I think it may be available in the late 16.x)

`window.addEventListener` would like to be called more than once then.

I can do some pr if you want to start this progress.

**Comment by xiaolin** [comment]
Sure feel free to open a pr if you like.

**Comment by xiaolin** [comment]
commit aba1cb8
