### ISSUE TITLE
Thumbnail sliding issue when using images with with varying width

### ISSUE THREAD

**Issue by VentroArt** [xiaolin/react-image-gallery#271]
How can i to control/set the distance for swiping? 
I'm asking because right now my thumbnails images have different width and  after i do a  few scrolls the active thumbnail goes away from display.
The main goal is have opportunity to set active thumbnail to center of thumbnail panel and solve the problem that was described above.
Here you can see example of issue before thumbnail disappear from display. So after next scroll active thumbnail will can't be seeing.

![GitHub Logo](http://i.prntscr.com/3o0iewOzTP_uJ-wDix6AXw.png)

**Comment by xiaolin** [comment]
The distance the thumbnail slides is based on the thumbnail container width / total thumbnails.
If you adjust the thumbnail container it will adjust the scroll distance too.
```
.image-gallery-thumbnails-wrapper {
   width: 80%;
}
```

**Comment by xiaolin** [comment]
Right now it assumes thumbnails to be equal in width, so may be worth adding a feature to support various size thumbnails.
