### ISSUE TITLE
Auto sliding for hover on the main image

### ISSUE THREAD

**Issue by jaisonjjames** [xiaolin/react-image-gallery#273]
Nice image gallery. May I know is there any feature exist like sliding start on the hover of the large image itself and stop on the mouse leave. Because as per my requirement there is no need for any thumbnail or arrow navigation etc.

**Comment by xiaolin** [comment]
That feature does not exists, but you can implement it by adding your own `onmouseover` event listener on the gallery and trigger `play()` or `pause()`
