### ISSUE TITLE
Custom play or pause button

### ISSUE THREAD

**Issue by jaisonjjames** [xiaolin/react-image-gallery#276]
Any code sample available for custom play/pause button for a hover/ click?

I have tried like below, but no luck.
`<ImageGallery onMouseOver={this.handleHover} play={this.state.play} autoPlay={this.state.play} showNav={false} lazyLoad={true} items={images} showThumbnails={this.state.play} showFullscreenButton={false} showPlayButton={false} showBullets={false} />`

**Comment by xiaolin** [comment]
There is no code sample available for custom play/pause for hover/click but you can fire available functions if you attach a `ref` to the gallery see for reference. https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js for
