### ISSUE TITLE
better lazy loading

### ISSUE THREAD

**Issue by tadjohnston** [xiaolin/react-image-gallery#278]
Lazy loading works great, but what I notice is that if i have say 30 images to put into the gallery with lazyLoad turned on, it still creates 2 dom nodes for each image.  See the screen shot.

![screen shot 2018-05-14 at 2 32 17 pm](https://user-images.githubusercontent.com/10748767/40024615-ba78d852-5783-11e8-88eb-0df7e9f0cc29.png)

I don't see the need for all of these. The problem is magnified when you have X number of galleries on a given page.  What do you think about trying to shrink down the dom nodes to just those that need to be available to interact with (possibly just previous, current and next)?

**Comment by xiaolin** [comment]
For context, the placeholder slides are there because of #137.

**Comment by tadjohnston** [comment]
Yeah, I guess since we don't need thumbnails right now this fix works for us, but back to the drawing board for me I guess 😄

**Comment by knro** [comment]
This is probably unrelated but how scalable is react-image-gallery? What if I have 1000 images? 10,000? Right now, I'm thinking of dividing very high number of images into "manageable" groups (say 50 images each) and then provide another control to load each consecutive group in the gallery.

But I'd like to know if perhaps the component can already handle large data sets without a performance hit.

**Comment by xiaolin** [comment]
If you're dividing the images into groups of 50 images and loading them only when requested. I don't see any scaling issue the component would run into.
