### ISSUE TITLE
Add class to image-gallery div when fullscreen

### ISSUE THREAD

**Issue by JeffreyLaCroix** [xiaolin/react-image-gallery#282]
Is there a way to add a class to the parent div "image-gallery" when full screen is active?
We are trying to add some specific styles when in full screen. We see the class "fullscreen" is added to "image-gallery-content" but would like to target the parent div.

**Comment by DezChuang** [comment]
I got the same problem too. And I found there is a props called "onScreenChange" and a class called "fullscreen-modal". However, even when I declare the props "onScreenChange" function, it's still not working, so I also wanna know if there is way to solve this issue.

**Comment by xiaolin** [comment]
Below is a solution to add a wrapper which you can manage.

```javascript
state = {
  fullScreen: false;
}

onScreenChange = (isFullScreen) => {
  this.setState({ fullScreen: isFullScreen });
}

render() {
  return (
    <div className={this.state.fullScreen ? 'my-full-screen-class' : ''}>
      <ImageGallery onScreenChange={this.onScreenChange} />
    </div>
  );
}
```

**Comment by kamir222** [comment]
I ran into this problem myself and found the example above useful, but incorrect. `isFullScreen` is not a of type boolean, but of type Element. I work with TypeScript and was able to uncover that by looking up the typings.

Thought this might help someone else. This worked for me: 

```
state = {
  fullScreen: false;
}

onScreenChange = (isFullScreen) => {
  this.setState({ fullScreen: isFullScreen !== null });
}

render() {
  return (
    <div className={this.state.fullScreen ? 'my-full-screen-class' : ''}>
      <ImageGallery onScreenChange={this.onScreenChange} />
    </div>
  );
}
```
