### ISSUE TITLE
Uncaught TypeError on unmounting

### ISSUE THREAD

**Issue by wouterh** [xiaolin/react-image-gallery#288]
Since v0.8.8, when an image gallery is unmounted, an Uncaught TypeError occurs:

```
Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
    at image-gallery.js:137
    at invokeFunc (index.js:160)
    at trailingEdge (index.js:207)
    at timerExpired (index.js:195)
```

I believe it is introduced by adding the debounce in b273f9d0da94.

**Comment by wouterh** [comment]
Actually, the `debounce` introduced in b273f9d0da94, fixed the problem on remount, but not on unmount?

**Comment by xiaolin** [comment]
Hmm, I think adding a `this._initGalleryResizing.cancel`  in `componentWillUnmount` should fix the issue.

**Comment by allexysleeps** [comment]
This is actually is reproducing on 0.8.7 as well

**Comment by Raja-Sharma** [comment]
@xiaolin Is your proposed fix for a future version of the package?

**Comment by xiaolin** [comment]
If no PR is opened I'll get to this soon.

**Comment by stfwoxry** [comment]
I have this problem too... any news about it? I can not find a fix for this

**Comment by xiaolin** [comment]
How can this be reproduced? Can someone give me a simple example?

**Comment by C-jeff** [comment]
@xiaolin If I'm not mistaken it happened for me after I've updated React to 16.4. Previously it was fine with 16.2.

**Comment by stfwoxry** [comment]
I just downgrade to the 0.8.7 and works at least for me!

**Comment by xiaolin** [comment]
This is fixed in 0.8.9 that was just released.

**Comment by OZZlE** [comment]
Still same issue in v.0.8.9 .. using a router and switching to another page with a gallery on it (using <Link />)

**Comment by xiaolin** [comment]
reopening and needs investigation

**Comment by s7dhansh** [comment]
@xiaolin Can't we simply use `if (element) this.resizeObserver.observe(element);` to fix this error? Any repercussions?

**Comment by xiaolin** [comment]
That is the current logic. It was released in `v0.8.9`

**Comment by xiaolin** [comment]
@OZZlE If this is isolated to using react router feel free to open a separate issue or PR. I'm closing this one as it solved the original issue.

**Comment by frayeralex** [comment]
@xiaolin, please see https://github.com/xiaolin/react-image-gallery/pull/306 - my solution in preventing call setState() in _handleResize callback function after component unmiunted
