### ISSUE TITLE
window.removeeventlistener not defined

### ISSUE THREAD

**Issue by reeda6** [xiaolin/react-image-gallery#293]
Hello,

I followed the instructions verbatim on the npm page yet continue to have this bug and I am not sure why.

import ImageGallery from 'react-image-gallery';

class Home extends React.Component {

render() {
    const images = [
      {
        original: 'http://lorempixel.com/1000/600/nature/1/',
        thumbnail: 'http://lorempixel.com/250/150/nature/1/',
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/2/',
        thumbnail: 'http://lorempixel.com/250/150/nature/2/'
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/3/',
        thumbnail: 'http://lorempixel.com/250/150/nature/3/'
      }
    ]
    return (
      <div className={s.root}>
        <Row>
          <Col xs={2} md={2} mdOffset={2} />
          <Col className={s.trythis} xs={12} md={8} mdOffset={2} />
        </Row>
        <div className={s.container}>
          <ImageGallery items={images} />
        </div>
      </div>
    );
  }
}

export default withStyles(s)(Home);

Thanks

Edit:
Error is now
element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports

**Comment by xiaolin** [comment]
Double check your imports. This issue looks to be unrelated to the library.

https://stackoverflow.com/questions/34130539/uncaught-error-invariant-violation-element-type-is-invalid-expected-a-string

**Comment by xiaolin** [comment]
Seems this was quite an old one, going to close for now.
