### ISSUE TITLE
Adding HTML elements in Image Description

### ISSUE THREAD

**Issue by srinivas025** [xiaolin/react-image-gallery#299]
Is it possible to add html to image description

**Comment by xiaolin** [comment]
Not in the library, but if you override the `renderItem` function you can render anything.

**Comment by SandMoshi** [comment]
If you pass in an array as a description you can have HTML elements inside.

For example, the following should work.

```
description: [

        <h3>Hello</h3>, 

        <p className='text' >Line 2</p>

]
```
