### ISSUE TITLE
srcSet Not working

### ISSUE THREAD

**Issue by OZZlE** [xiaolin/react-image-gallery#300]
imagesArray looks like:

    [{
        original: "image_path", // this one works
        // as string doesn't work
        srcSet: "https://staging-lorem.s3.amazonaws.com/media/catalog/product/cache/small_image/568x/fe048ded4c6db6c6afa45b749bc258ce/3/0/30007351100_st.jpg 1536w", 
        // as object doesn't work
        srcSet: {"1986w":"https://staging-lorem.s3.amazonaws.com/media/false","1536w":"https://staging-lorem.s3.amazonaws.com/media/catalog/product/cache/small_image/568x/fe048ded4c6db6c6afa45b749bc258ce/3/0/30007351100_st.jpg","640w":"https://staging-lorem.s3.amazonaws.com/media/false"},
       // as array doesn't work
       srcSet: ['https://staging-lorem.s3.amazonaws.com/media/catalog/product/cache/small_image/568x/fe048ded4c6db6c6afa45b749bc258ce/3/0/30007351100_st.jpg 640w', ... 
        thumbnail: BASE_MEDIA_URL + thumbnailImage,
        originalClass: 'originalImage',
        thumbnailClass: 'thumbnailImage',
        bestseller,
        renderItem: this.renderRibbon.bind(this),
    }, ...]

            <ImageGallery
              items={imagesArray}
              showThumbnails
              slideOnThumbnailHover
              lazyLoad
              showNav
              showBullets
              onClick={this.openLightbox}
              slideInterval={3000}
              showPlayButton={false}
              showFullscreenButton={false}
              thumbnailPosition="left"
              onSlide={this.setImageIndex}
            />
          </div>

You haven't written anything regarding it's formatting..

**Comment by OZZlE** [comment]
The problem seems to come from:

    const renderItem = item.renderItem ||
        this.props.renderItem || this._renderItem;

It needs to use `this._renderItem` to add the `srcSet`

**Comment by xiaolin** [comment]
`srcSet` is not specific to this library. Its a [HTML5 img](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img) property.

It seems you've overwritten `renderItem` and that is why `item.renderItem` will be used instead of `this._renderItem` If you override the render item method you are responsible for handling the item properties yourself. See the documentation for examples.
