### ISSUE TITLE
Upgrade from 0.8.5 to 0.8.9 causing console error listed in description.

### ISSUE THREAD

**Issue by davidthrasher** [xiaolin/react-image-gallery#309]
"[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted. Swipeable.js?efad:228"

I was having an issue with the image gallery not working when nested inside of one component, but it would then work perfectly fine inside of another. I upgraded my package to the latest version and it fixed this issue. But now I'm receiving the above error message in my console. I believe it's an issue within swipeable.js but its pretty far down the rabbit hole. 
![screen shot 2018-07-30 at 11 00 42 am](https://user-images.githubusercontent.com/25215475/43405524-09ce5f58-93e8-11e8-9e1c-baae9754da02.png)

Any idea how to fix this?

**Comment by davidthrasher** [comment]
It appears the reason that this error is occurring is due to an update in react-swipeable. I was able to fix it by downgrading the nested dependency to version 4.2.1.

**Comment by xiaolin** [comment]
@Jayphen Is this happening with the latest version of the dependency `v4.30` of `react-swipeable`? If so feel free to reopen.

**Comment by Jayphen** [comment]
@xiaolin  Yes, it is happening with 4.30.

**Comment by davidthrasher** [comment]
Im glad this issue has reopened as we are still using an older version of react-swipeable to avoid these warrnings in the console. Agreed having to manually downgrade is not a good fix, but its what we had to do at the time.

**Comment by zhipu123** [comment]
[1AZ1`1`¸V](url)

**Comment by xiaolin** [comment]
closing in favor of duplicate #321
