### ISSUE TITLE
startIndex not working if user come back next time

### ISSUE THREAD

**Issue by mukeshkumarkarn** [xiaolin/react-image-gallery#314]
First time image gallery is working properly. I selected an image and saved it in database. Next time it should show that saved image as first, so i used startIndex property.

startIndex property is not taking the value from the current state, it takes the default values as zero always.
If i hard code the startIndex propery to something as 1, then only it works as desired.

**Comment by xiaolin** [comment]
The default `startIndex` is 0 but if you pass `startIndex` as a prop to the component it will work.

**Comment by Jasminff** [comment]
it cannot change the startIndex dynamicly.if I change the startIndex with 10, it would be 10 next time, but the new number 6

**Comment by Jasminff** [comment]
like ths,<ImageGallery
								items={imgData}
								showFullscreenButton= {false}
								showPlayButton= {false}
								showThumbnails={false}
								startIndex = {startIndex}
							/>
the startIndex can not work right,can you help me?@ @xiaolin

**Comment by xiaolin** [comment]
How are you changing the `startIndex` dynamically? The start index is working as intended. Can you show me an example of how you're using `startIndex`?
