### ISSUE TITLE
renderCustomControls binding to gallery instead of item

### ISSUE THREAD

**Issue by kaYcee** [xiaolin/react-image-gallery#316]
Great lib! I tried to use the `renderCustomControls` with binding `this` to its attached actions as described but all I get are the props of the `ImageGallery` with no reference to the currently displayed item. Might it have to do with the ES6-implementation of the `forEach`-loop which binds to the class rather than the iterated item or am I doing something wrong? Thanks!

Here the property list of `this` in the bound action:

`{items: Array(3), lazyLoad: true, showPlayButton: false, showIndex: true, thumbnailPosition: "bottom", …}
autoPlay: false
disableArrowKeys: false
disableSwipe: false
disableThumbnailScroll: false
flickThreshold: 0.4
indexSeparator: " / "
infinite: true
isRTL:false
...`

**Comment by xiaolin** [comment]
`renderCustomControls` is a function for injecting custom components into the gallery, it does not have reference to each of the slides. You can use other functions like `getCurrentIndex()` to get the currently displayed item.
