### ISSUE TITLE
iOS flicker on image change

### ISSUE THREAD

**Issue by Japjappedulap** [xiaolin/react-image-gallery#319]
How to reproduce (even on example):

1. Reload page (fresh reload)
2. Swipe/tap right to change the image (preferably tap, because the motion is much faster than swiping)
3. For a very short moment, the next image appears to be white.

I've found this occurs mainly on iOS devices (test device: iPhone 7) no matter the browser. On Android phones, I haven't been able to reproduce this (test devices: Nexus 5, Samsung S5, Samsung S9).

**Comment by neoighodaro** [comment]
+1. I have this issue too.

**Comment by niklaslavrell** [comment]
This seems to be resolved for me now after bumping to the latest version `0.8.14` 🙌

**Comment by xiaolin** [comment]
This is no longer reproducible with the latest version. Feel free to reopen if you can reproduce.

**Comment by Himkumar2** [comment]
Hi @xiaolin I'm using 1.2.8 version but still facing this issue . 
I'm suing below code . Please help

` <ImageGallery
          ref={elementRef}
          items={mediaGallery}
          infinite
          showThumbnails={false}
          showNav={false}
          showFullscreenButton={false}
          showPlayButton={false}
          showBullets={true}
          swipeThreshold="10"
          onSlide={handleOnSlide}
        />`
