### ISSUE TITLE
Can't call setState on an unmounted component

### ISSUE THREAD

**Issue by hchoriq** [xiaolin/react-image-gallery#320]
When I scroll quickly through a list of ImageGallery, I am receiving this error:

Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

On this line:

![image](https://user-images.githubusercontent.com/15879364/45277226-a2329080-b47b-11e8-8684-cc4997398f46.png)

Any ideas?

**Comment by hchoriq** [comment]
I should also mention I'm using it with react-virtualized. The error appears when I scroll past each gallery very quickly.

**Comment by xiaolin** [comment]
This looks related to pr #288. Can you reproduce it on the example link? linxtion.com/demo/react-image-gallery
