### ISSUE TITLE
disableArrowKeys

### ISSUE THREAD

**Issue by DungBuiDeveloper** [xiaolin/react-image-gallery#327]
this props not working

**Comment by xiaolin** [comment]
Can you explain a little more? If you use prop `disableArrowKeys` you can still go to next and previous slide using your left and arrow keys on your keyboard?

**Comment by DungBuiDeveloper** [comment]
yes , and i must use css for hidden arrow , any props for hidden arrow. disableArrowKeys is hiiden or disable function next or pre , i think it's not be rendered arrow

**Comment by xiaolin** [comment]
I think you confused `disableArrowKeys` and `showNav`

`showNav`: Will hide the navigation arrows
`disableArrowKeys`: Will disable the left and right arrow keys on your keyboard from triggering sliding to the next slide

**Comment by DungBuiDeveloper** [comment]
showNav:ok
disableArrowKeys (removed) but not working with arrow key from keyboard. can you please check.
<ImageGallery
        autoPlay={true}
        lazyLoad={true}
        slideInterval={4000}
        ref={i => this._imageGallery = i}
        items={images}
        showPlayButton={false}
        showFullscreenButton={false}
        useBrowserFullscreen={false}
        showNav={false}
      />

**Comment by xiaolin** [comment]
It looks good to me. The arrow keys should be working with that configuration. If you take a look at the demo below you'll notice the arrow keys are working (It works for me at least).

http://linxtion.com/demo/react-image-gallery/
