### ISSUE TITLE
Transition Animation on Large Monitors 

### ISSUE THREAD

**Issue by tomgallagher** [xiaolin/react-image-gallery#329]
Hi

I'm looking at full screen pictures with gallery on autoplay on a 2580x1600 monitor and the transitions are lagging with artefacts on the screen from time to time.

I wanted the full screen with height as well so I have added this to my CSS:

`.image-gallery-slide img { height: 100vh; }`

That does not seem to be causing the problem. It seems smoother when I reduce the browser size. Is there anything else I can do to improve performance on bigger screens? Would adjusting the .jpg image quality help? A slower duration in the transition?

Any thoughts?

Thanks for this gallery, it's good stuff.

**Comment by xiaolin** [comment]
I tested on a 3440x1440 monitor using default transition duration and it doesn't seem laggy to me. What transition duration are you using?

**Comment by tomgallagher** [comment]
I was running the browser on one screen of a dual-monitor setup, with each monitor being 2580x1600.

I've come to the conclusion that my graphics card is the problem, not your slider, as I also get small distortions with other animation using requestanimationframe.

Thanks for checking this out for me. Feel free to close.

**Comment by vladimir-fsh** [comment]
Nice to have a different type of animation (fadein/fadeout). I customized your gallery for a big screen and it looks not so smoothy when you slide. A good example of fadeIn animation is on airbnb.com

 
![image](https://user-images.githubusercontent.com/17701600/48714256-94834f00-ec12-11e8-9261-026714ea50be.png)

**Comment by xiaolin** [comment]
Please see issue #166 
Adding  the below CSS override will give you a fadeIn affect, you can also customize the CSS further based on your needs.

```css
.image-gallery-slide {
  opacity: 0;
}
.image-gallery-slide.center {
  opacity: 1;
}
```

**Comment by vladimir-fsh** [comment]
@xiaolin and also transition: image-gallery-slide { opacity 0.2s ease-out !important; } in my case
