### ISSUE TITLE
IE11 bug on image-gallery-slide

### ISSUE THREAD

**Issue by pungggi** [xiaolin/react-image-gallery#331]
Hello in IE have this bug:
![grafik](https://user-images.githubusercontent.com/5635709/46008546-5e679a00-c0bd-11e8-9078-b9247598f65c.png)

that could be sorted out by 
![grafik](https://user-images.githubusercontent.com/5635709/46008638-9078fc00-c0bd-11e8-943e-f90158c071b3.png)

would you accept a PR for that?

**Comment by xiaolin** [comment]
I think its best to override the CSS to fix the issue for IE11 (not supported).
