### ISSUE TITLE
Warning on _toggleShowVideo(url) Method from Demo = Do not mutate state directly. Use setState()

### ISSUE THREAD

**Issue by M-Husein** [xiaolin/react-image-gallery#334]
Hi,

Thanks for share your nice work.

But I get Warning on _toggleShowVideo(url) Method from Demo = Do not mutate state directly. Use setState(). I use create-react-app.

I try to change this method but doesn't work.

Please fix this warning. I think this is not good.

Thanks.

**Comment by xiaolin** [comment]
Can you list steps to reproduce? I'm not seeing the error.
