### ISSUE TITLE
Invalid or unexpected token in browser v0.8.11 version due to unicode underscore used

### ISSUE THREAD

**Issue by huksley** [xiaolin/react-image-gallery#336]
## Invalid or unexpected token in browser v0.8.11 version due to unicode underscore used

In src/ImageGalery.jsx function ـslidePrevious is declared using unicode underscore.
Browser complains with error when trying to load 0.8.11 version.

![image](https://user-images.githubusercontent.com/1594349/46601390-8f03f680-caf5-11e8-8ed0-96d8549d4c7d.png)

![image](https://user-images.githubusercontent.com/1594349/46601409-9deaa900-caf5-11e8-843f-c64f2f623109.png)

**Comment by huksley** [comment]
Nice! Thanks for fast review. When we should expect new release? Rolled back to 0.8.9 for now.

**Comment by xiaolin** [comment]
I'll try to get a release out today or tomorrow.
