### ISSUE TITLE
how to set the image height 

### ISSUE THREAD

**Issue by Jasminff** [xiaolin/react-image-gallery#339]
when the pixels of the image is too large,how can I set the height and width of the image to fit the screen of the computer,looking forward to your answer,thankeyou very much!

**Comment by juanpallares** [comment]
If you are talking about full screen mode, I'm also interested

**Comment by Jasminff** [comment]
@xiaolin Could you response me?

**Comment by xiaolin** [comment]
The gallery does not automatically adjust if you have different size images. I suggest using images with the same height and width to have a smoother user experience. If you cannot do that, then you'll have to override the css to maintain the height and width of all your images. For example if you do something like

```css
.image-gallery-slide img {
    width: 100%;
    height: 300px;
}
```

This will keep all your image heights to a maximum of `300px`

You can read more about the `sizes` attribute here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by Jasminff** [comment]
I had try it like you say, but it can not to adapt to the full screen

**Comment by Jasminff** [comment]
thank you for your response, I want to set the height of the images in JavaScript,not in css. So can you provide a new property to set the image so that it can automatically adjust the different  size images

**Comment by xiaolin** [comment]
I'm a bit confused why you need to set the height of images using javascript?

If you need to maintain the height for full screen you can use `100vh` so

```
.image-gallery-slide img {
    width: 100%;
    height: 100vh;
}
```

**Comment by Jasminff** [comment]
<ImageGallery 
    items={imageData}
    onImageLoad={this.load}
    onScreenChange = {this.onScreenChange}
     />
 load = () => {
         let fullscreen = document.querySelectorAll('.fullscreen')
         if (fullscreen.length) {
             this.onScreenChange(fullscreen.length)
         } else {
             this.getImageSize()
}

onScreenChange = (full) => {
        if (full) {
            let out = document.querySelectorAll('.fullscreen .image-gallery-image')
            for (let j = 0; j < out.length; j++) {
                out[j].style.height = window.innerHeight - 150 + 'px'
            }
            let outW = document.getElementsByClassName('image-gallery-image')[0].clientWidth
            let outH = document.getElementsByClassName('image-gallery-image')[0].clientHeight
            let imgOutSize = document.querySelectorAll('.image-gallery-slide img')
            for (let i = 0; i < imgOutSize.length; i++) {
                 let w = imgOutSize[i].naturalWidth
                 let h = imgOutSize[i].naturalHeight
                 let outSize = outW / outH
                 let size = w / h
                 if (size > outSize) {
                    if ((w < outW) && (h < outH)) {
                        imgOutSize[i].style.width = w + 'px'
                        imgOutSize[i].style.height = h + 'px'
                     } else {
                        imgOutSize[i].style.width = outW + 'px'
                        imgOutSize[i].style.height = 'auto'
                    }
                } else if (size == outSize) {
                    if (w >= outW) {
                        imgOutSize[i].style.width = outW + 'px'
                        imgOutSize[i].style.height = outH + 'px'
                    } else {
                        imgOutSize[i].style.width = w + 'px'
                        imgOutSize[i].style.height = h + 'px'
                    }
                } else {
                    if ((w < outW) && (h < outH)) {
                        imgOutSize[i].style.width = w + 'px'
                        imgOutSize[i].style.height = h + 'px'
                     } else {
                        imgOutSize[i].style.height = outH + 'px'
                        imgOutSize[i].style.width = 'auto'
                    }
                }
            }
        } else {
            this.getImageSize()
        }
    }

 getImageSize = () => {
        let out = document.querySelectorAll('.image-gallery-image')
        for (let j = 0; j < out.length; j++) {
            out[j].style.height = 440 + 'px'
        }
        let outW = document.getElementsByClassName('image-gallery-image')[0].clientWidth
        let outH = document.getElementsByClassName('image-gallery-image')[0].clientHeight
        let imgOutSize = document.querySelectorAll('.image-gallery-slide img')
        for (let i = 0; i < imgOutSize.length; i++) {
             let w = imgOutSize[i].naturalWidth
             let h = imgOutSize[i].naturalHeight
             let outSize = outW / outH
             let size = w / h
             if (size > outSize) {
                 if ((w < outW) && (h < outH)) {
                    imgOutSize[i].style.width = w + 'px'
                    imgOutSize[i].style.height = h + 'px'
                 } else {
                    imgOutSize[i].style.width = outW + 'px'
                    imgOutSize[i].style.height = 'auto'
                 }
            } else if (size == outSize) {
                if (w >= outW) {
                    imgOutSize[i].style.width = outW + 'px'
                    imgOutSize[i].style.height = outH + 'px'
                } else {
                    imgOutSize[i].style.width = w + 'px'
                    imgOutSize[i].style.height = h + 'px'
                }
            } else {
                if ((w < outW) && (h < outH)) {
                    imgOutSize[i].style.width = w + 'px'
                    imgOutSize[i].style.height = h + 'px'
                 } else {
                    imgOutSize[i].style.height = outH + 'px'
                    imgOutSize[i].style.width = 'auto'
                 }
            }
        }
    }

**Comment by xiaolin** [comment]
If I understand what you want can be achieved using CSS. See example in the stackoverflow link below.
https://stackoverflow.com/questions/12991351/css-force-image-resize-and-keep-aspect-ratio

The library does not handle dynamic images. I suggest using CSS or resizing all your images to the same dimensions.

**Comment by Jasminff** [comment]
I didn't do that.I control it with Js.
 <ImageGallery 
     items={imageData}
     onImageLoad={this.load}
     onScreenChange = {this.onScreenChange}
/>
 load = () => {
         let fullscreen = document.querySelectorAll('.fullscreen')
         if (fullscreen.length) {
             this.onScreenChange(fullscreen.length)
         } else {
             this.getImageSize()
         }
    }

    // 获取非全屏时图片的宽度与高度
    getImageSize = () => {
        let out = document.querySelectorAll('.image-gallery-image')
        for (let j = 0; j < out.length; j++) {
            out[j].style.height = 440 + 'px'
        }
        let outW = document.getElementsByClassName('image-gallery-image')[0].clientWidth
        let outH = document.getElementsByClassName('image-gallery-image')[0].clientHeight
        let imgOutSize = document.querySelectorAll('.image-gallery-slide img')
        for (let i = 0; i < imgOutSize.length; i++) {
             let w = imgOutSize[i].naturalWidth
             let h = imgOutSize[i].naturalHeight
             let outSize = outW / outH
             let size = w / h
             if (size > outSize) {
                 if ((w < outW) && (h < outH)) {
                    imgOutSize[i].style.width = w + 'px'
                    imgOutSize[i].style.height = h + 'px'
                 } else {
                    imgOutSize[i].style.width = outW + 'px'
                    // imgOutSize[i].style.height = (outW * h) / w + 'px'
                    // imgOutSize[i].style.height = '100%'
                    imgOutSize[i].style.height = 'auto'
                 }
            } else if (size == outSize) {
                if (w >= outW) {
                    imgOutSize[i].style.width = outW + 'px'
                    imgOutSize[i].style.height = outH + 'px'
                } else {
                    imgOutSize[i].style.width = w + 'px'
                    imgOutSize[i].style.height = h + 'px'
                }
            } else {
                if ((w < outW) && (h < outH)) {
                    imgOutSize[i].style.width = w + 'px'
                    imgOutSize[i].style.height = h + 'px'
                 } else {
                    imgOutSize[i].style.height = outH + 'px'
                    imgOutSize[i].style.width = 'auto'
                 }
            }
        }
    }

    onScreenChange = (full) => {
        if (full) {
            let out = document.querySelectorAll('.fullscreen .image-gallery-image')
            for (let j = 0; j < out.length; j++) {
                out[j].style.height = window.innerHeight - 150 + 'px'
            }
            let outW = document.getElementsByClassName('image-gallery-image')[0].clientWidth
            let outH = document.getElementsByClassName('image-gallery-image')[0].clientHeight
            let imgOutSize = document.querySelectorAll('.image-gallery-slide img')
            for (let i = 0; i < imgOutSize.length; i++) {
                 let w = imgOutSize[i].naturalWidth
                 let h = imgOutSize[i].naturalHeight
                 let outSize = outW / outH
                 let size = w / h
                 if (size > outSize) {
                    if ((w < outW) && (h < outH)) {
                        imgOutSize[i].style.width = w + 'px'
                        imgOutSize[i].style.height = h + 'px'
                     } else {
                        imgOutSize[i].style.width = outW + 'px'
                        imgOutSize[i].style.height = 'auto'
                    }
                } else if (size == outSize) {
                    if (w >= outW) {
                        imgOutSize[i].style.width = outW + 'px'
                        imgOutSize[i].style.height = outH + 'px'
                    } else {
                        imgOutSize[i].style.width = w + 'px'
                        imgOutSize[i].style.height = h + 'px'
                    }
                } else {
                    if ((w < outW) && (h < outH)) {
                        imgOutSize[i].style.width = w + 'px'
                        imgOutSize[i].style.height = h + 'px'
                     } else {
                        imgOutSize[i].style.height = outH + 'px'
                        imgOutSize[i].style.width = 'auto'
                    }
                }
            }
        } else {
            this.getImageSize()
        }
    }

**Comment by Jasminff** [comment]
Maybe I write more complicated.I would simplify it

**Comment by xiaolin** [comment]
Were you able to solve your problem using JS?

**Comment by Jasminff** [comment]
yeah,I use javaScript like above to solve my problem

**Comment by interpegasus** [comment]
The following CSS solved the issue for my gallery in case it helps : )

```
.image-gallery {
    width: 100%;
    height: auto;
}

.image-gallery-slide img {
    width: 100%;
    height: auto;
    max-height: 80vh;
    object-fit: cover;
    overflow: hidden;
    object-position: center center;
}

.fullscreen .image-gallery-slide img {
    max-height: 100vh;
}
```

**Comment by xiaolin** [comment]
Closing as this is solved.

**Comment by lishine** [comment]
My images are 1024px and with the default implementation they were zoomed beyond the size of the screen! The above snippet didn't help. And whenever I set image height, it put itself to the left. The bellow code works for me:
```
'.fullscreen .image-gallery-slide.center': {
                    display: 'flex',
                    bg: 'black !important',
                },
                '.fullscreen .image-gallery-image': {
                    mx: 'auto',
                    maxWidth: '1024px',
                },
```
