### ISSUE TITLE
ImageGallery onLoad

### ISSUE THREAD

**Issue by profdev** [xiaolin/react-image-gallery#341]
Is there any way to know when the ImageGallery is fully loaded?

When the page is loaded with the ImageGallery, this._imageGallery is undefined despite the thumbnail and images being loaded. Only when I click a thumbnail or next, then this._imageGallery can be inspected.

**Comment by xiaolin** [comment]
Can you list steps to reproduce? I'm able to reference `this._imageGallery` when the component mounts.
