### ISSUE TITLE
Add anchor tag to images.

### ISSUE THREAD

**Issue by Sam-Houlahan** [xiaolin/react-image-gallery#342]
Hi, I need to add an <a> tag to the images as I need them to link to somewhere else. Do you support this or do you advice i add the tag to your code manually.

**Comment by xiaolin** [comment]
You can override the render method for rendering images. See doc for more info.

**Comment by heshamelmasry77** [comment]
@xiaolin  could you please show us which part in the documentation

**Comment by xiaolin** [comment]
@heshamelmasry77 see `renderItem` in doc and see example js on how its used
https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js#L35

**Comment by heshamelmasry77** [comment]
not very helpful to be honest so big and i can't figure out a very small thing i wanna do.
Simply all what i want to do to add a nav link around the images !
as i understood i need to create a function 

```
_renderLink(id) {
    return (
        <div className='image-gallery-custom-action'>
        {
          <NavLink to={`/rooms/${id}`}> </NavLink>
        }
      </div>
    );
  }
```
and we add this to the 
ImageGallery 
```
                   renderCustomControls ={this._renderLink(roomId)}

```
``` roomId ``` is a dynamic variable i get

**Comment by heshamelmasry77** [comment]
this is the solution @Sam-Houlahan  
```
<ImageGallery
                   items={images}
                   showPlayButton={false}
                   slideOnThumbnailHover={false}
                   disableArrowKeys={true}
                   showNav={true}
                   showFullscreenButton={true}
                   showThumbnails={false}
                   renderCustomControls={()=>{return <NavLink to={`/rooms/${roomId}`} className='image-gallery-custom-action'/>}}
               />
```

**Comment by xiaolin** [comment]
The closed issue originally asked for wrapping an `<a>` tag around the image for link out. If you want to add your own control or element into the slide using `renderCustomControls` then you need to pass in a function.

You've seemed to have figured it out after passing in a function instead of a function call.
