### ISSUE TITLE
Fullscreen is cutting of the image

### ISSUE THREAD

**Issue by srka** [xiaolin/react-image-gallery#343]
When I use fullscreen mode in your demo the bottom part of the image is cutoff. I ma using Firefox on 1920x1080 landscape screen. Is there a way to show the whole image. Thanks.

**Comment by mongiellog1** [comment]
For portrait photos, fullScreen is cutting off half (or more) of the photo.  The controls also don't display in fullscreen
_Tested only with portrait photos._

**Comment by xiaolin** [comment]
You'll need to tweak the CSS for your various screen sizes. The demo does not support all screen sizes. There is also a specific css class added when fullscreen is activated.
