### ISSUE TITLE
Make different sizes of the big slide photos look good

### ISSUE THREAD

**Issue by daggala** [xiaolin/react-image-gallery#347]
It seems the gallery handles best the same size of images so I had to do plenty of css hacking to modify it. I'd like to contribute my experience so that it can become the default of this great gallery project. I always have the same hight of photos but then the width varies. I'd also like to do the same for the thumbnails #351

**Comment by daggala** [comment]
I've just started to work on it: https://github.com/xiaolin/react-image-gallery/pull/354

**Comment by xiaolin** [comment]
Please open a PR with the description. Ideally, like to keep Issues tab to bugs.
