### ISSUE TITLE
Make different sizes of the thumnails look good

### ISSUE THREAD

**Issue by daggala** [xiaolin/react-image-gallery#351]
When you have different sizes of photos the height of the photos varies in the list of thumbnails. I think it's more beautiful that by default the height will always be the same but the width varies (without deforming the photo)

**Comment by daggala** [comment]
I'm working on it: https://github.com/xiaolin/react-image-gallery/pull/353

**Comment by xiaolin** [comment]
Please open a PR with the description. Ideally, like to keep Issues tab to bugs.
