### ISSUE TITLE
onScreenChange triggered as many times as there are instances on the page

### ISSUE THREAD

**Issue by srka** [xiaolin/react-image-gallery#357]
When I add multiple instances of this component to the page and go into the fullscreen mode onScreenChange callback is called as many times as there are component instances.

**Comment by xiaolin** [comment]
This is expected behavior since the callback listens to the browser screenchange events.

What are you trying to accomplish with the callback?

**Comment by srka** [comment]
I tried to slide to a different initial index for each instance using slideToIndex when I open a fullscreen mode. For example, the when I open a fullscreen mode for the first instance I want to slide to its second image, but when I open a fullscreen mode for the second instance I want to slide to its third image.

I found a way by manually triggering the fullscreen mode (which is what I need to do anyway) so this issue is solved but thank you for the info. I thought it was supposed to trigger onScreenChange per instance not as a browser screenchange event.
