### ISSUE TITLE
Thumbnail label

### ISSUE THREAD

**Issue by iferunsewe** [xiaolin/react-image-gallery#360]
Hi nice library!

I'm trying to render the thumbnail label but passing it as a prop to the ImageGallery doesn't seem to render it anywhere. Is there more I need to do?

```
render() {
    var images = this.props.images;
    return (
      <ImageGallery 
        items={images}
        showPlayButton={false}
        startIndex={this.props.index}
        showFullscreenButton={false}
        thumbnailLabel={"Label FOR THUMBNAIL"} />
}
```

Thanks

**Comment by aakhan89** [comment]
> 
> 
> Hi nice library!
> 
> I'm trying to render the thumbnail label but passing it as a prop to the ImageGallery doesn't seem to render it anywhere. Is there more I need to do?
> 
> ```
> render() {
>     var images = this.props.images;
>     return (
>       <ImageGallery 
>         items={images}
>         showPlayButton={false}
>         startIndex={this.props.index}
>         showFullscreenButton={false}
>         thumbnailLabel={"Label FOR THUMBNAIL"} />
> }
> ```
> 
> Thanks

humbnail label  showing ?
