### ISSUE TITLE
Is it possible to fire an action on slide change?

### ISSUE THREAD

**Issue by bdmason** [xiaolin/react-image-gallery#363]
As the title states, I'm just looking for a change event prop to fire an action every time the slide changes. Couldn't find one in the docs.

It looks like I'd need to do the following to do it:

- use the onSlide prop
- use the renderLeftNav prop to create a component and hook into an onClick in there
- do the same for the right nav
- find a way to access clicks on the dots at the bottom

If someone can confirm there isn't a prop to capture all the above, is this an acceptable additional feature to request (I can create a pull request and do it myself)?

**Comment by bdmason** [comment]
Apologies, just checked the code and it looks like onSlide is in fact what I want! When I get round to using it and confirming I'll close this (unless it gets confirmed & closed first).

**Comment by xiaolin** [comment]
Yes it is `onSlide`
