### ISSUE TITLE
Autoplay is not respected when items are changed

### ISSUE THREAD

**Issue by ikovic** [xiaolin/react-image-gallery#379]
I'm using version `0.8.12` and I'm having trouble with changing the `autoPlay` setting once the component is already mounted. I'm building an online auction site and I use this library to display a rotating list of images and videos per each auction item. If item has videos attached to it, I set `autoPlay` to `false` and default to `true` if there are images only.

Problem I'm facing is that the `autoPlay` setting is read only on `componentDidMount`, so changing it later does not affect the gallery (eg autoplay will resume even though the item list contains a video so prop `autoPlay` is set to `false`). I've fixed this by patching `componentDidUpdate` like this:
```
componentDidUpdate(prevProps, prevState) {
    const itemsChanged = prevProps.items.length !== this.props.items.length;
    if (itemsChanged) {
      this._handleResize();
      if (this.props.autoPlay) {
          this.play();
        } else {
          this.pause();
        }
    }
...
```

Will this change cause any unwanted behaviour? I tested it a bit and it seems to work for my use case. If it makes sense, I can open a PR. Also if there's a better way of handling this, I'll be happy to update the solution.

Thanks for the awesome library BTW!

**Comment by xiaolin** [comment]
I think handling this outside the library makes sense. So overriding your `componentDidUpdate` is the right idea. I did the same thing in the example when `slideIterval` or `slideDuration` is changed.

**Comment by xiaolin** [comment]
Your change should not cause any unwanted behavior as long as it was done in your own wrapper component that wraps `ImageGallery`
