### ISSUE TITLE
Responsive Images 

### ISSUE THREAD

**Issue by texaspacm** [xiaolin/react-image-gallery#38]
Is there a way to load different sized images based on the view port.  

I.e. Not have the client download the high-res when they are on a phone.   

Thanks

**Comment by xiaolin** [comment]
You could have that logic when you generate the items object e.g.

```
if (device === 'mobile') {
  items = generateMobileSlides();
} else {
  items = generateDefaultSlides()
}
```

**Comment by xiaolin** [comment]
Closing this, feel free to reopen if you have further questions.
