### ISSUE TITLE
fullscreen button - image doesn't fit over screen

### ISSUE THREAD

**Issue by landrail8** [xiaolin/react-image-gallery#383]
thnks for awesome app!
When I click Fullscreen button - big image doesn't fit over screen. I only see part of the image.
What are the parameters of the component to fit the image on the screen?

**Comment by xiaolin** [comment]
You will have to modify via css and set a max heigh and or width so image does not go beyond the screen.

**Comment by landrail8** [comment]
tnks for response, I've seen the [theme](https://github.com/xiaolin/react-image-gallery/issues/339) and make custom css for solve problem of alignment.
Still it would be great to have the alignment in fullscreen rezime right in this library...

**Comment by xiaolin** [comment]
This has been fixed in 0.8.15 using screen height. 

If your image is beyond the width of your screen then you'll have to customize the CSS yourself.

**Comment by xiaolin** [comment]
v0.8.15 caused a bug for smaller size screens and was reverted in v0.8.16.

**Comment by xiaolin** [comment]
Closing. The solution will be up to the user to define the appropriate image width/height depending on their media resolutions.
