### ISSUE TITLE
defaultImage Property not working

### ISSUE THREAD

**Issue by aakhan89** [xiaolin/react-image-gallery#384]
Can anyone help out, why default Image not calling ?

![image](https://user-images.githubusercontent.com/38126236/53489826-ebbb7a00-3ab3-11e9-961c-4fa0f87c51a8.png)

import React from 'react';
import ImageGallery from 'react-image-gallery';

import "react-image-gallery/styles/css/image-gallery.css";

const ImgGallery = () => {
    
    const images = [
        {
          original: 'http://lorempixel.com/1000/600/city/2/',
          thumbnail: 'http://lorempixel.com/250/150/city/2/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/3/',
          thumbnail: 'http://lorempixel.com/250/150/city/3/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/4/',
          thumbnail: 'http://lorempixel.com/250/150/city/4/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/5/',
          thumbnail: 'http://lorempixel.com/250/150/city/5/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/6/',
          thumbnail: 'http://lorempixel.com/250/150/city/6/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/7/',
          thumbnail: 'http://lorempixel.com/250/150/city/7/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/8/',
          thumbnail: 'http://lorempixel.com/250/150/city/8/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/9/',
          thumbnail: 'http://lorempixel.com/250/150/city/9/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/10/',
          thumbnail: 'http://lorempixel.com/250/150/city/10/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/11/',
          thumbnail: 'http://lorempixel.com/250/150/city/11/'
        },
        {
          original: 'http://lorempixel.com/1000/600/city/12/',
          thumbnail: 'http://lorempixel.com/250/150/city/12/'
        }
      ]

    return (
        <ImageGallery items={images} showBullets='true' showIndex='true' defaultImage='../assets/images/default.jpg' />
    )
}

and the default image path is Folder public/assets/images/default.jpg

**Comment by xiaolin** [comment]
@aakhan89 `defaultImage` shows on error. It doesn't seem any of the images you are displaying is throwing an error.

**Comment by aakhan89** [comment]
> @aakhan89 `defaultImage` shows on error. It doesn't seem any of the images you are displaying is throwing an error.

`import Logo from '../assets/images/logo.png';`

`return (
        <ImageGallery 
          items={images} 
          showBullets={true} 
          defaultImage={Logo} />
    )`

However the same image is calling in other component, so What should I do to display defaultImage before loading Image Gallery

**Comment by xiaolin** [comment]
> However the same image is calling in other component
What do you mean by this?
> so What should I do to display defaultImage before loading Image Gallery
Are you trying to load a placeholder image before the images from `images` load?

**Comment by aakhan89** [comment]
> > However the same image is calling in other component
> 
> What do you mean by this?
> 
> > so What should I do to display defaultImage before loading Image Gallery
> 
> Are you trying to load a placeholder image before the images from `images` load?

**Are you trying to load a placeholder image before the images from `images` load?**

Yes.. exactly....!

**Comment by aakhan89** [comment]
@xiaolin Kindly help out please

**Comment by aakhan89** [comment]
> you trying to load a placeholder image before the images from `images` load?

Just want Placeholder image or like default image before loading images from the server and also want to put any loader

**Comment by xiaolin** [comment]
There is no explicit feature that supports what you want, but you should be able to write some custom JS to accomplish what you need. You can load your default image and wait for all your images to load. Once your images load you can update the state of `images`

e.g. set images to use default images until you're ready to load the server images.

```jsx
const defaultImages = [
    {
      original: '../assets/images/default.jpg',
      thumbnail: '../assets/images/default.jpg'
    },
    {
      original: '../assets/images/default.jpg'',
      thumbnail: '../assets/images/default.jpg'
    },
]

<ImageGallery items={defaultImages} />
```

**Comment by aakhan89** [comment]
> There is no explicit feature that supports what you want, but you should be able to write some custom JS to accomplish what you need. You can load your default image and wait for all your images to load. Once your images load you can update the state of `images`
> 
> e.g. set images to use default images until you're ready to load the server images.
> 
> ```js-jsx
> const defaultImages = [
>     {
>       original: '../assets/images/default.jpg',
>       thumbnail: '../assets/images/default.jpg'
>     },
>     {
>       original: '../assets/images/default.jpg'',
>       thumbnail: '../assets/images/default.jpg'
>     },
> ]
> 
> <ImageGallery items={defaultImages} />
> ```

Ohkk.. thanks for your reply, I will handle it with JS..!

But if you can add this feature it will be highly appreciated
