### ISSUE TITLE
Modify .image-gallery-left-nav, & .image-gallery-right-nav and put Label on slider

### ISSUE THREAD

**Issue by aakhan89** [xiaolin/react-image-gallery#385]
Hi,

I want to modify Modify .image-gallery-left-nav, & .image-gallery-right-nav and put Label on slider:
see below example of before & after:

**Before**

![image](https://user-images.githubusercontent.com/38126236/53877557-4c563400-402b-11e9-9495-12e53208fec8.png)

**After**

![image](https://user-images.githubusercontent.com/38126236/53877994-8247e800-402c-11e9-8621-9e2d2f95d7fa.png)

**Comment by xiaolin** [comment]
Please see documentation on how you can modify the description label and navigation icons
