### ISSUE TITLE
how to set the image height (responsive)

### ISSUE THREAD

**Issue by aakhan89** [xiaolin/react-image-gallery#386]
@xiaolin 

I set the height on the image itself.

`.image-gallery-image img {
 max-height: 725px;
}`

but the issue is the height if fixed for all screen i.e responsive height always showing 725px and if I not set the height as mentioned above so is perfectly fine in responsive....

but when I play the images so slider toggle according to image size 

how can it fix?

**Comment by xiaolin** [comment]
Please see #339. The gallery does not handle dynamic image sizes and is up to you to define the responsive logic.
