### ISSUE TITLE
thumbnailPosition is not working except "bottom" and "top"

### ISSUE THREAD

**Issue by odgiv** [xiaolin/react-image-gallery#389]

**Comment by xiaolin** [comment]
Seems fine to me, check out the [ demo page ](http://linxtion.com/demo/react-image-gallery/)

**Comment by odgiv** [comment]
Yeah it does there. Is it the latest version there? Because I have a problem. When I set thumbnailPosition to left or right, whole images are gone and set width and height to 0s.

**Comment by odgiv** [comment]
Sorry it was my bad. I forgot to import css file in my main css file and it worked now.
