### ISSUE TITLE
It should check if a `onClick` handle was passed or not before calling it

### ISSUE THREAD

**Issue by grsabreu** [xiaolin/react-image-gallery#39]
Is just a minor bug, it isn't something to really worry about.
https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.react.jsx#L157

**Comment by xiaolin** [comment]
what do you mean by "`onClick` handle was passed "?

**Comment by xiaolin** [comment]
I see the error you're talking about :D

**Comment by xiaolin** [comment]
Will fix. Thanks

**Comment by xiaolin** [comment]
fixed in v0.5.10

**Comment by grsabreu** [comment]
Awesome!
