### ISSUE TITLE
defaultImage property

### ISSUE THREAD

**Issue by aakhan89** [xiaolin/react-image-gallery#390]
**### defaultImage property say below:**

defaultImage: String, default undefined

    an image src pointing to your default image if an image fails to load
    handles both slide image, and thumbnail image

I have an **`item={images}`** and images is array of multiple images for `original` & `thumbnail`
the confusion is when internet stop working so defaultImage should be shown instead of images which I have an in array of images until my internet working fine 

`import defaultImage from '../assets/images/default.jpg';`

```
const images = [
      {
        original: 'http://lorempixel.com/1000/600/nature/1/',
        thumbnail: 'http://lorempixel.com/250/150/nature/1/',
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/2/',
        thumbnail: 'http://lorempixel.com/250/150/nature/2/'
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/3/',
        thumbnail: 'http://lorempixel.com/250/150/nature/3/'
      }
    ]
```

`return<ImageGallery 
            items={images} 
            defaultImage={defaultImage}
            showBullets={true}
            showIndex={true}
            showThumbnails={false}/>`

**Comment by aakhan89** [comment]
@xiaolin

**Comment by xiaolin** [comment]
Were you able to solve this? The default image is loaded when the image errors out. I would first test to see that your `defaultImage` is in fact imported correctly and working. Do you see your default image when you render `<img src={defaultImage} />` ?

**Comment by aakhan89** [comment]
If I print the `defaultImage` in my console the pic render successfully but when the image errors out the default image not rendering in the browser

**Comment by xiaolin** [comment]
How are you creating an error for the image? What happens when you modify the url to an invalid url `http://lorempixel.com/fakepath.jpg` does the `defaultImage` show?

**Comment by aakhan89** [comment]
import defaultImage from '../assets/images/default.jpg';

<GalleryContainer>
          <ImageGallery
            items={props.setImages} 
            defaultImage={defaultImage}
            showBullets={true}
            showIndex={true}
            showThumbnails={false}
            lazyLoad={true}
            showPlayButton={false} />
        </GalleryContainer>

**Comment by xiaolin** [comment]
I'm not sure I follow. I tested `defaultImage` and it is working correctly. Can you list the steps to reproduce your issue? Can you replicate the same issue when running the library locally? 

You can run the lib locally by following the steps https://github.com/xiaolin/react-image-gallery#build-the-example-locally

**Comment by aakhan89** [comment]
@xiaolin 

I will create codeSandbox and share with you

**Comment by pthapli999** [comment]
try using template strings...works for me

**Comment by aakhan89** [comment]
@pthapli999 

Can you please share an example, it would be highly appreciated Thanks

**Comment by aakhan89** [comment]
Can you please guide how to use **`onImageError: Function, callback(event)`**

just want overrides defaultImage when there is no image in the array of images 

You may see the CodeSand Box example
https://codesandbox.io/s/ymv96pkl81
