### ISSUE TITLE
Show first image immediately from an array of images

### ISSUE THREAD

**Issue by aakhan89** [xiaolin/react-image-gallery#391]
I want to show first image immediately when my page is loading however rest of images load in backend but 1st image should be appeared immediately so how can I achieve this ?

kindly help me

**Comment by xiaolin** [comment]
Questions like this are better suited for stackoverflow. Please use the issues for lib specific issues.

**Comment by aakhan89** [comment]
It can be better if you add this feature in your gallery, anyway thanks
