### ISSUE TITLE
Feature request: different image for zoom view

### ISSUE THREAD

**Issue by mhp-borisbojic** [xiaolin/react-image-gallery#395]
Hi,

I really like your image-gallery, but one thing is not so optimal.

Right now, the image in normal view and fullscreen view is the very same.

That means, the user needs to load a very large image in advance (e.g. a high resolution 4k image) that is suitable for the zoom view, but it's unnecessarily large for the default view.

Any ideas how to implement or solve this issue?

**Comment by xiaolin** [comment]
There is actually an example of this on the demo page on slide #2 take a look at `imageSet` in the docs, and the example below
https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js#L41

**Comment by mhp-borisbojic** [comment]
No, the srcset can't help in this way. The base for srcset is the browser's window with, which is the same for the normal or zoomed mode.

Therefore, I can't define an alternative image for the zoom mode with that.

I achieved it now in another way, I'm using https://github.com/frontend-collective/react-image-lightbox as zoom instead of the one of your plugin (I combined your and this plugin) :)

**Comment by Kinniken** [comment]
I would like to second the original poster, it is also pretty much the only flaw I have had with this great image gallery.

I could also use some other library for the zoom mode, but it feels stupid when the current one is otherwise exactly what I need.

**Comment by xiaolin** [comment]
There is a `onScreenChange` function that will trigger wether or not the screen is fullscreen. You can update your array of images with fullscreen versions once that happens to accomplish the feature.

Should be easy enough to add a new property called `fullscreen` so that the library automatically updates to all the fullscreen images. If anyone wants to open a PR.

**Comment by xiaolin** [comment]
Closing, feel free to open a pr as this is a minor enhancement and not an issue.
