### ISSUE TITLE
Guide how to use onImageError: Function, callback(event)

### ISSUE THREAD

**Issue by aakhan89** [xiaolin/react-image-gallery#397]
Can you please guide how to use **`onImageError: Function, callback(event)`**
just want overrides **defaultImage** when there is no image in the array of images
You may see the CodeSand Box example:

https://codesandbox.io/s/ymv96pkl81

**Comment by xiaolin** [comment]
Please use stackoverflow and only use the `issues` tab to open issues related to the library.
