### ISSUE TITLE
Property to disable slide on onMouseOver and onMouseLeave

### ISSUE THREAD

**Issue by jossi87** [xiaolin/react-image-gallery#40]
Hover on thumbnail will cause the image to change (this.slideToIndex(index)).
Is it possible to add a property to disable this feature?
The blue frame on hovering is okay, but I don't want slideToIndex to be executed.

**Comment by xiaolin** [comment]
@jossi87 I'll release a version this weekend that will have an option to disable that. Will keep you posted!

**Comment by jossi87** [comment]
Perfect!

**Comment by xiaolin** [comment]
@jossi87 released 0.5.10 with `slideOnThumbnailHover` prop set to false by default.
