### ISSUE TITLE
Stretched images introduced in v0.8.15

### ISSUE THREAD

**Issue by mattcolman** [xiaolin/react-image-gallery#401]
Hi, since v0.8.15 we're experiencing stretched image in our image gallery.

**Comment by xiaolin** [comment]
Hmm, seems the solution in v0.8.15 won't work correctly for mobile/tablet type screens. I suggest using `v0.8.14` for now while I look into either reverting or coming up with a better solution.

**Comment by mattcolman** [comment]
I suggest unpublishing this version, as it’s quite a critical bug.

**Comment by xiaolin** [comment]
fixed in v0.8.16
