### ISSUE TITLE
Last Image scroll twice on phone full screen

### ISSUE THREAD

**Issue by RadekGluchowski** [xiaolin/react-image-gallery#404]
Hi, thank for great app, i found some annoying bug, when u are on last image and want to go to next u should be navigated to first, but unfortunatelly app as next taking last img second part, and when u click second time next on second part of last image, the first image in array blink and u will be thrown to second. it happens only on mobile full screen. i have got
   ( width: auto;
    height: calc(100vh - 85px) ). I thought it was my bug but when i test your demo:
http://linxtion.com/demo/react-image-gallery/ 
it happens too.
Any solve ?
I test it on Google chrome desktop, Android, iphone 
![bug](https://user-images.githubusercontent.com/40294777/55882910-9770e300-5ba5-11e9-842c-1078749e9e20.png)
![bug2](https://user-images.githubusercontent.com/40294777/55882925-9cce2d80-5ba5-11e9-8f5c-9a8a92a02d61.png)

**Comment by xiaolin** [comment]
Please update to the latest patch, the `width: auto; height: calc(100vh - 85px);` caused a bug that didn't work well for mobile/tablet full screens. The example is a patch behind.
