### ISSUE TITLE
Instant `slideToIndex`

### ISSUE THREAD

**Issue by stephencookdev** [xiaolin/react-image-gallery#405]
Hey :)

First of all, thanks for the great library.

Currently the `slideToIndex(i)` function works great, but my current use-case requires an option to be able to change the index that the image gallery is showing, but instantly (i.e. without animation)

I'm happy to raise a PR for this, but wondering if you have any concerns / design thoughts?

My current thinking is either to extend `slideToIndex` to be something like `slideToIndex(i, { animate: false })`, or add a new `setIndex(i)` method

**Comment by xiaolin** [comment]
@stephencookdev You can update the `slideDuration=0` prop before executing `slideToIndex`, and set `slideDuration` back after `slideToIndex` finishes. This will achieve your instant slide functionality.

**Comment by stephencookdev** [comment]
Sure, but the problem with it being a prop change means that my code would have to look something like
```
this.setState({ slideDuration: 0 },
  () => {
    this.imageGalleryRef.slideToIndex(n)
    this.setState({ slideDuration: initialSlideDuration })
  }
)
```
or something.

And even then, I would probably need a few `setTimeout`s, in order to let the state change apply to before calling the `slideToIndex` method

A direct method in the API feels a lot cleaner

**Comment by xiaolin** [comment]
@stephencookdev that's exactly it, and you don't need any `setTimeout` as you are using the `setState` callback function. Try it out, you'll be surprised how well it works. 

I'm hesitant on adding custom features like this as its highly customize and ideally be left to the user to extend with using available props and functions.

If more are interested in this feature I think its something we can add, but this is the first time I'm hearing of a need for this.
