### ISSUE TITLE
Img size stretched by the thumbnail container width

### ISSUE THREAD

**Issue by Rashlack** [xiaolin/react-image-gallery#407]
I have an unsolved problem, but it's maybe because I misunderstood something. 

If I disable the thumbnails, my img are displayed with their original size (600 x 338 for this example), but when I enable the thumbnails the img is stretched to the total width of all the thumbnails:
If I have 25 img, so 25 thumbnails : the size is 2548 x 1435
100 thumbnails: 10198 x 5744

Here is my ImageGallery, I didn't add any css
`return(
      <div>
      <button type="button" onClick={ this.onClick }>Close</button>
        <ImageGallery
          items={ this.state.photosViewer }
          disableSwipe={ true }
          slideDuration={ 200 }
          startIndex={ this.props.selectedPhotoIndex }
          onSlide={ this.onSlide }
          showThumbnails={ true }
          infinite={ false }
        />
      </div>
    );`

100 thumbnails:
![image](https://user-images.githubusercontent.com/36641803/56047692-fd7b7880-5d13-11e9-8da3-8bbb121838db.png)

11 thumbnails
![image](https://user-images.githubusercontent.com/36641803/56048506-abd3ed80-5d15-11e9-906d-93806c2484fd.png)
 
without thumbnails:
![image](https://user-images.githubusercontent.com/36641803/56048377-631c3480-5d15-11e9-8644-3706cc879d92.png)

**Comment by xiaolin** [comment]
It seems like you're not loading any of the css. Did you import it? Your elements should display css definitions from the gallery. 
![Screen Shot 2019-04-12 at 11 25 52 AM](https://user-images.githubusercontent.com/1286776/56048575-cdcd7000-5d15-11e9-9013-4f8d7b45bb57.png)

**Comment by xiaolin** [comment]
After looking at the screenshots, it seems to be a css issue with page. The container holding the gallery is bleeding out of the page. Try adding a width: 800px to the container and restrict the size of the gallery.

**Comment by Rashlack** [comment]
Yes If I add a css with : 
`.image-gallery-slide img{
  width: max-content
}
.image-gallery-thumbnails-container{
  width: 800px
}`

it's work better. I will head that way and customize my css file .

Thanks
