### ISSUE TITLE
Thumbnail container doen't ajust when adding photo with onSlide

### ISSUE THREAD

**Issue by Rashlack** [xiaolin/react-image-gallery#409]
Here is the issue, or maybe just my small problem:

In my application I'm adding new item as the user scroll the photos. I'm only loading 11 photos at beginning and add 1 each time the "onSlide" is call. 
The problem is: the thumbnail container is initialize with 11 photos, so the "squared thumbnail" when the selected photo = 11 is completely to the right, but is the user continue scrolling more to the right, the "squared thumbnail" is out of the screen. Here is some picture to explain what I mean:
![image](https://user-images.githubusercontent.com/36641803/56144786-01f09d00-5f71-11e9-860b-a21d800a2302.png)
![image](https://user-images.githubusercontent.com/36641803/56144833-192f8a80-5f71-11e9-8b5e-8a46c383a2d9.png)
![image](https://user-images.githubusercontent.com/36641803/56144871-28aed380-5f71-11e9-9d86-dc34685d413a.png)

Is there a way to always show the "squared thumbnail" in the middle? 
Or, I also notice that when the user get back to photo 0, the container reinitialized his size, but cannot figure out how to call this method. 
Thanks for your help

**Comment by xiaolin** [comment]
The gallery resizes every time the length of the items changes and the thumbnail container recalculates the space needed for the new thumbnail. Can you replicate the same issue from the example?

**Comment by Rashlack** [comment]
I've try to build an other imageGallery and I have the same issue,
I've also console.log the lenght it the object pass to Item props and it's change everytime onSlide is call. But the thumbnail container doens't recalculate the space needed. 

Here is the code to fill and render the ImageGallery. 
If there a solution to juste keep the selected thumbnail in the middle, It's fine for me. Or a way to call the recaltulated space needed. Thanks 

`onSlide = (currentIndex) => {
    this.fillViewer(currentIndex)
  };

fillViewer = (index, qty = this.props.photoToLoadQty) => {
    console.log(this.props.photosList.length)
    console.log(this.state.photosViewer.length)
    index = index - Math.round(qty / 2);
    index = index < 0 ? 0 : index;
    for(let i = index; i < index + qty; i++){
      if(this.state.photosViewer[i] === undefined){
        getPhoto(this.props.photosList[i], "large")
        .then(photo => {
          let temp = this.state.photosViewer;
          temp[i] = { original: photo, thumbnail: photo, srcSet: photo };
          this.setState({ photoViewer: temp })
        });
      }
    }
  };

render() {
    return(
      <div>
      <button type="button" onClick={ this.onClose }>Close</button>
        <ImageGallery
          items={ this.state.photosViewer }
          disableSwipe={ true }
          slideDuration={ this.props.slideDuration }
          startIndex={ this.props.selectedPhotoIndex }
          onSlide={ this.onSlide }
          showThumbnails={ true }
          infinite={ false }
        />
      </div>
    );
  };`

**Comment by xiaolin** [comment]
![Screen Capture on 2019-04-19 at 10-12-18](https://user-images.githubusercontent.com/1286776/56427984-d7ae2080-628b-11e9-865a-8a008e712676.gif)

I wrote a quick sample to show that this is working. Its a little hard to read your code, but you might be appending the new image incorrectly. try using array destructuring to add your new photo. See below.

```jsx
  onSlide(index) {
    if (index === this.state.images.length - 1) {
      // add new image...
      const newImage =       {
        original: `${PREFIX_URL}1.jpg`,
        thumbnail: `${PREFIX_URL}1t.jpg`,
      };
      const images = [...this.state.images, newImage];

      this.setState({images: images});
    }
  }
```

**Comment by xiaolin** [comment]
Closing, if this is still an issue feel free to open with an example of how to reproduce.
