### ISSUE TITLE
Cannot set property '_preventGhostClick' of null (in _touchEnd method)

### ISSUE THREAD

**Issue by Stevearzh** [xiaolin/react-image-gallery#41]
Using this plugin on a touch supported device will get this bug, on the line:

> https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.react.jsx#L128

with react 0.14.0 and react-image-gallery 0.5.11. My config file is kind like the example file:

> https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js

I use the react developer tool to detect the "showNav" state, this is mine:

![](http://i.imgur.com/TP0ydZI.png?1)

and this is the demo's:

![](http://i.imgur.com/gVrSP2R.png?1)

seemed I missed some steps, the bind method didn't work to the element.

I'm not sure where am I wrong. Any suggestions?

Thanks.

**Comment by xiaolin** [comment]
I think I know whats going on
all `onTouchEnd={this._touchEnd}` should be `onTouchEnd={this._touchEnd.bind(this)}` in the code

I will create a fix for this tonight, and release it.

**Comment by xiaolin** [comment]
@Stevearzh fixed on v0.5.12

**Comment by Stevearzh** [comment]
Awesome, thank you! 👍
