### ISSUE TITLE
Clicking thumbnail gallery icon automatically scrolls to the last picture

### ISSUE THREAD

**Issue by cesarvh** [xiaolin/react-image-gallery#410]
Hi all,

I'm not entirely sure what's going on but I'm using the default `onThumbnailClick` prop, and whenever I click a picture in the thumbnail, it automatically scrolls to the very last index. Anyone know what might be going on?

In the gif, I am clicking the sunflower (index #2) thumbnail, but it goes to the tulips (index #3). I then use the arrows to scroll back to index #1 (index #0 is transparent), and click on index #2, and it instead goes to index #4. 

![giphy](https://user-images.githubusercontent.com/9059527/56399056-b6ecb900-6200-11e9-8dea-35019910b77d.gif)

**Comment by xiaolin** [comment]
Can you show me your `onThumbnailClick` function?

**Comment by cesarvh** [comment]
I didn't implement my own, so I don't pass in a prop. Am I mistaken in that it will use the default `onThumbnailClick`? I have only implemented my own `renderLeftNav`,`renderRightNav`, `onClick`, `renderItem` and `renderThumbInner`

**Comment by xiaolin** [comment]
I would slowly undo all the customizations and see which one might be causing the issue. e.g comment out `renderItem` and `renderThumbInner` to see if those might be causing an issue.

**Comment by cesarvh** [comment]
Great idea. Just found the issue. Thanks!
