### ISSUE TITLE
SlideOnThumbnailOver or SlideOnThumnailHover?

### ISSUE THREAD

**Issue by Osanusi** [xiaolin/react-image-gallery#411]
Whenever I am trying to use the property slideOnThumnailOver, react autocompletes or recommends me using slideOnThumbnailHover. So I end up using it, but the thumbnails arent sliding when I hover over.

I took at look at the ImageGallery.jsx, and I can see the attribute still says slideOnThumbnailOver, so why is it asking me for (Hover) when it doesn't exist and neither does it work?

**Comment by xiaolin** [comment]
I'm not sure why your react autocomplete recommends using `slideOnThumbnailHover ` but the correct prop is `slideOnThumbnailOver`. There is no instance of `slideOnThumbnailHover` in the code so maybe its something with your autocomplete configuration?

**Comment by Osanusi** [comment]
I found out the issue. The creator of the types for this library seems to have misspelled the attribute/prop. I’m using typescript. In his index.d.ts file, he misspells it. 

Thanks, 
Seun Sanusi
