### ISSUE TITLE
Feature Request: a trash button to delete image from gallery

### ISSUE THREAD

**Issue by AishwaryaChat** [xiaolin/react-image-gallery#412]
Hi,

This image gallery package is really helpful, there is one feature request that I would like to recommend.

there is no property to pass on to ImageGallery, so that there shud be a delete button for each image on the gallery so that if someone will enable this property, a image can be deleted from the array of images.

Can I start working on this issue and raise a pull request?

**Comment by xiaolin** [comment]
Hi @AishwaryaChat. This isn't a common feature that most users would use from an image gallery. I suggest implementing it outside the gallery by modifying the the array of images you pass in.

**Comment by AishwaryaChat** [comment]
@xiaolin can you please suggest how we would be implementing that outside the gallery because the kind of requirement I have is to show a delete button each image. can I do it by passing my own render function?

**Comment by xiaolin** [comment]
@AishwaryaChat You can add a delete button outside the gallery and use CSS to position it the way you like. Then you can write a function so that when the button is clicked it deletes the current index using the function `getCurrentIndex`

e.g.

```jsx
handleDelete() {
   const currentIndex = this._imageGallery.getCurrentIndex();
   const { myItems } = this.state;
   this.setState({
     myItems: [...myItems.slice(0, currentIndex - 1), ...myItems.slice(currentIndex, myItems.length)]
   })
}
<div>
  <ImageGallery item={this.state.myItems} ref={i => this._imageGallery = i} />
  <button onClick={this.handleDelete}>Delete Slide</button>
</div>
```
