### ISSUE TITLE
Cache images when Lazy Load feature is enabled

### ISSUE THREAD

**Issue by InmobilesWeb** [xiaolin/react-image-gallery#415]
When Lazy Load feature is enabled with autoPlay=true  and infinite=true , the same images are loaded again from the server. Is there a way to cache already loaded images (after first load)?

**Comment by xiaolin** [comment]
`lazyLoad`, when set to `true`, will only mount the necessary images for `left`, `center` and `right`.

Most browser should cache images by default once they load it once. This library does not have the ability to persist images that were previously loaded. This is something that is usually handled on the server side or on the CDN you're using.

**Comment by InmobilesWeb** [comment]
Thank you xiaolin for your answer. The problem was the CDN I am using. It was preventing the images from caching in the browser.

**Comment by juanmait** [comment]
You should add a very clear item in the doc that says something like "by default this library will request all the images in every single slide action repeatedly" since the infinite option is `true` by default. At least that's what is happening when lazy loading is `false`

**Comment by xiaolin** [comment]
@juanmait Thanks for bringing this to my attention, I've released version `v1.2.5` which will not load images repeatedly even if the image cache is disabled.

**Comment by juanmait** [comment]
Hey @xiaolin thanks
