### ISSUE TITLE
originalClass applies to surrounding div, not to the img

### ISSUE THREAD

**Issue by fgaume** [xiaolin/react-image-gallery#416]
Hello Xio Lin,

First of all thank you so much for this helpful component.
I keep trying to set rounded images (either with the Bootstrap 'rounded' or more simply with CSS border-radius: 5px). It does work with thumbnails (by passing this to the thumbnailClass), but not with originals, because originalClass is applied to the **div** containing the targeted **img**. Have you an idea how to find a way to apply rounded corners to the originals ?
Thanks again !

```
.myclass (img or not) {
    border-radius: 5px;
}
```

**Comment by xiaolin** [comment]
I'm not sure I completely understand but, you should be able to target the image from the div containing the targeted img.

```html
<div class='image-gallery-slide myclass'>
  <img />  /* this can be targeted from parent css class */
</div>

.myclass img {
    border-radius: 5px
}
```

**Comment by fgaume** [comment]
It is exactly what I did but unfortunately the rounded corners are displayed in the div's corners (i.e. the background behind the img), not the img

**Comment by xiaolin** [comment]
Can you show a screenshot? You might also need to apply `border-radius: 5px` to the parent class `image-gallery-slides` too.

**Comment by fgaume** [comment]
<img width="898" alt="Capture d’écran 2019-05-13 à 17 08 34" src="https://user-images.githubusercontent.com/4450097/57632441-f5785800-75a1-11e9-9712-db098be0babc.png">

**Comment by xiaolin** [comment]
I opened the chrome dev tool and modified some css and its working for me. I would double check your CSS to make sure its being targeted correctly.

![Screen Shot 2019-05-13 at 11 15 55 AM](https://user-images.githubusercontent.com/1286776/57632889-94845c00-7570-11e9-932b-9d3a0f61a96c.png)

**Comment by fgaume** [comment]
thanks I had it as well, but the problem came from those 2 additional rules (mandatory in my context) :

`.image-gallery-slide img {
    object-fit: contain;
    max-height: calc(100vh - 136px);
...
`

Finally, adding : 

`    width: auto;
    display:block;
    margin-left:auto;
    margin-right:auto;
`

fixed the problem. 

So once more thank you for your help and as a result, this thread was definitely not an issue ;-)
