### ISSUE TITLE
History Navigation with gestures

### ISSUE THREAD

**Issue by shoaibnawaz** [xiaolin/react-image-gallery#417]
Chrome browser 74 has experimental feature called "Overscroll history navigation"
A normal horizontal swipe shows an overlaying arrow and upon releasing page is redirected to history item. Have a look in video. https://www.youtube.com/watch?v=X-KzZU1B6uo

Is there any possibility to create a better experience after overscroll history navigation becomes default feature?
Is there some workaround to overcome or discard browser behavior?

**Comment by xiaolin** [comment]
Feel free to open a PR when this experimental feature is out, sounds like something good.
