### ISSUE TITLE
Lazy loading multiple images from random points of the array?

### ISSUE THREAD

**Issue by gcosgreave-us** [xiaolin/react-image-gallery#419]
I have noticed that when I click the arrows for the next/prev slide there are multiple images loading in. I have tried to make sense of it because I am sure that there is a reason for it. 

Currently on first click I have the next slide loading (which I would expect) then 2 images from the end of the images array. Then on the 2nd click I have the same but 2 images from the start and end of the array, then the next click (3rd) its also getting 2 images for the slide 2 previous to the current slide. Then that happens going forward. 

I hope this makes sense? I have included some screen shots to maybe help you to better understand this issue. 

First click
<img width="613" alt="Screen Shot 2019-05-16 at 12 57 41" src="https://user-images.githubusercontent.com/39494540/57852209-7e79d400-77da-11e9-989c-73e2b1fe776e.png">

Second click
![Screen Shot 2019-05-16 at 13 00 14](https://user-images.githubusercontent.com/39494540/57852317-c4369c80-77da-11e9-9e57-8ddd02d87ea3.png)

Third click
![Screen Shot 2019-05-16 at 14 25 57](https://user-images.githubusercontent.com/39494540/57857675-8a1fc780-77e7-11e9-9f82-9e2be4a9b1ec.png)

I am passing the following props to ImageGallery: 

```
<ImageGallery
  items={imageArray2}
  lazyLoad
  renderLeftNav={this.renderLeftNav}
  renderRightNav={this.renderRightNav}
  showIndex={imageArray2.length > 1}
  onSlide={this.fadeIn}
/>
```

The array is structured as follows: 

```
original: slide.entity.fieldImage.entity.fieldMediaImage.large.url,
        originalAlt: slide.entity.fieldImage.entity.fieldMediaImage.alt,
        originalTitle: slide.entity.fieldCaption,
        description: slide.entity.fieldCaption,
        thumbnail: slide.entity.fieldImage.entity.fieldMediaImage.thumb.url,
        thumbnailAlt: slide.entity.fieldImage.entity.fieldMediaImage.alt,
        thumbnailTitle: slide.entity.fieldCaption,
        imageSet: [
          {
            srcSet: slide.entity.fieldImage.entity.fieldMediaImage.small.url,
            media: '(max-width: 576px)',
          },
          {
            srcSet: slide.entity.fieldImage.entity.fieldMediaImage.medium.url,
            media: '(min-width: 768px)',
          },
          {
            srcSet: slide.entity.fieldImage.entity.fieldMediaImage.large.url,
            media: '(min-width: 1280px)',
          },
        ],
```

I hope this is enough to go on for the moment. If you would like anything else or anymore info please let me know.

**Comment by lakshaylbb** [comment]
Yes, same issue, please fix this ...

**Comment by tamasPetki** [comment]
Same issue here: same pictures are downloaded repeatedly and continuously.

**Comment by zcsongor** [comment]
+1

**Comment by xiaolin** [comment]
@gcosgreave-us @lakshaylbb @tamasPetki @zcsongor can you reproduce using the example page? I am unable to reproduce with `lazyLoad` turned on. Can you try reproducing without using `imageSet` and see if `imageSet` is the issue.

**Comment by gcosgreave-us** [comment]
@xiaolin I already tried that and it just loads all the images in one go as you would expect. I can see if I can get time to set up a code sand box if that would help

**Comment by xiaolin** [comment]
@gcosgreave-us if `lazyload` is turned on, only the thumbnails are all loaded (they don't have proper lazy loading). The main images are only loaded as necessary.

**Comment by gcosgreave-us** [comment]
I am out of the country for a few days from tomorrow I will try and get something up before I go, if not if anyone else that is seeing this could replicate it on a code sand box and share it, it would be greatly appreciated

**Comment by gcosgreave-us** [comment]
@xiaolin Yep seems to be that imageSet is the issue https://codesandbox.io/s/pedantic-microservice-i65he

**Comment by tamasPetki** [comment]
For me, it is the same with or without imageSet. After swiping to the next picture all the previous pictures are reloaded again.

**Comment by tamasPetki** [comment]
Do you have any solution or workaround for this?

**Comment by xiaolin** [comment]
@gcosgreave-us I'm not very familiar with using `imageSet` myself and will have to investigate further. @tamasPetki can you reproduce what you're describing using a codesandbox? I'm only able to reproduce this using `imageSet`

**Comment by xiaolin** [comment]
@gcosgreave-us @tamasPetki actually it seems it may be something with how image urls are passed in. If I take out lorempixel urls and use my own absolute url to the images the issue goes away. Take a look at the sandbox below, the only image being loaded over and over is the one from lorempixel

https://codesandbox.io/s/busy-haibt-zww80

**Comment by grohmio** [comment]
same here, with every swipe the number of loaded images increases when lazy loading is enabled

first swipe loads `/3, /8`
2. swipe `/1, /4, /8`
3. swipe `/1, /2, /5, /8`
...
10. swipe `/1, /1, /2, /3, /4, /4, /5, /6, /7,  /8, /8`

code e.g.
```javascript
import ImageGallery from 'react-image-gallery';
import "react-image-gallery/styles/css/image-gallery.css";

class ImageGalleryComponent extends React.Component {

    render() {

        const images = [
            {
                original: 'http://lorempixel.com/1000/600/nature/1/'
            },
            {
                original: 'http://lorempixel.com/1000/600/nature/2/'
            },
            {
                original: 'http://lorempixel.com/1000/600/nature/3/'
            },
            {
                original: 'http://lorempixel.com/1000/600/nature/4/'
            },
            {
                original: 'http://lorempixel.com/1000/600/nature/5/'
            },
            {
                original: 'http://lorempixel.com/1000/600/nature/6/'
            },
            {
                original: 'http://lorempixel.com/1000/600/nature/7/'
            },
            {
                original: 'http://lorempixel.com/1000/600/nature/8/'
            },
            {
                original: 'http://lorempixel.com/1000/600/city/1/'
            },
            {
                original: 'http://lorempixel.com/1000/600/city/2/'
            },
            {
                original: 'http://lorempixel.com/1000/600/city/3/'
            },
            {
                original: 'http://lorempixel.com/1000/600/city/4/'
            },
            {
                original: 'http://lorempixel.com/1000/600/city/5/'
            },
            {
                original: 'http://lorempixel.com/1000/600/city/6/'
            },
            {
                original: 'http://lorempixel.com/1000/600/city/7/'
            },
            {
                original: 'http://lorempixel.com/1000/600/city/8/'
            },
        ]

        return (
            <ImageGallery
                items={images}
                lazyLoad={true}
                showNav={true}
                showThumbnails={false}
                showFullscreenButton={false}
                showPlayButton={false}
                autoPlay={false}
            />
        );
    }

}

ReactDOM.render(<ImageGalleryComponent />, document.getElementById("root"));

```

**Comment by gcosgreave-us** [comment]
> @gcosgreave-us @tamasPetki actually it seems it may be something with how image urls are passed in. If I take out lorempixel urls and use my own absolute url to the images the issue goes away. Take a look at the sandbox below, the only image being loaded over and over is the one from lorempixel
> 
> https://codesandbox.io/s/busy-haibt-zww80

Absolute URL's don't really work for us as the images are being served via Drupal

**Comment by xiaolin** [comment]
Can someone reproduce this without using a `lorempixel` image url?

**Comment by gcosgreave-us** [comment]
Sorry I have been stacked lately. I can try this next week

**Comment by xiaolin** [comment]
This issue was related to lorempixel. Images were not caching on the browser causing subsequent loads to reload the image. I've updated the readme to use another placeholder service for images called `https://picsum.photos`.
