### ISSUE TITLE
`renderItem` will be called when user scroll the slide

### ISSUE THREAD

**Issue by wszgxa** [xiaolin/react-image-gallery#423]
When scrolling the slide, the `renderItem` method will be called many times. It's a performance issue.

Related code: https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.jsx#L1037

It's because of we will call the method every time when the slide rerender. When the user scrolls the slide, we need to change the `style`, it will cause re-render. 

I guess we don't need to call the `renderItem` every time when the `style` change. 

And also, I suggest adding a note in README to suggest return a pure component. Could we change this one to return a PureComponent: https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.jsx#L885

If you are okey with this, I can help to send a PR.

**Comment by xiaolin** [comment]
Sounds good. A pure component will definitely help! Feel free to open a PR.

**Comment by OZZlE** [comment]
Was this fixed or? Was there any PR?

**Comment by xiaolin** [comment]
Not yet, I push some changes recently but need to revisit this.

**Comment by g1geordie** [comment]
hello~  did it have any solution?

**Comment by sachitram-cv** [comment]
@xiaolin 
Is this fixed?

Thanks.

**Comment by xiaolin** [comment]
Fixed in `1.2.6` https://github.com/xiaolin/react-image-gallery/releases/tag/v1.2.6
