### ISSUE TITLE
New version 0.8.18 causes slider to jump

### ISSUE THREAD

**Issue by finnp** [xiaolin/react-image-gallery#424]
When we update to the newest version 0.8.18, it causes our slider to jump strangely between images. 

Here is the settings that we are using:
```js
          <ImageGallery
            items={items}
            showThumbnails={false}
            showFullscreenButton={false}
            showPlayButton={false}
            showBullets={false}
            showIndex={false}
            onSlide={currentIndex => setCaseIndex(currentIndex)}
          />
```

**Comment by xiaolin** [comment]
@finnp can you reproduce this on the demo? You can turn all the props off the same way as you showed on the example above.

**Comment by finnp** [comment]
No I can't. I think it might be related to `items` always being a new instance in our case.

**Comment by xiaolin** [comment]
There was a bug fix that was not resetting the startIndex when the `items` change see #422 

But I don't think this would cause a flicker. May I ask why and how you're adjusting the `items`?

**Comment by yasserzubair** [comment]
Facing the same issue, It was working fine before. We are changing the showThumbnail via a state on `onSlide`. We don't want to show thumbnails on first image, however when we click next, it always slides back to the first slide

**Comment by xiaolin** [comment]
@yasserzubair updating the prop for `showThumbnails` should not cause a reset to where the slide is. Changing the `items` prop will.

**Comment by xiaolin** [comment]
@finnp Can this be closed?

**Comment by xiaolin** [comment]
Closing, feel free to reopen if the bug persists in `v0.9.1`
