### ISSUE TITLE
display broken when added next.js to my project

### ISSUE THREAD

**Issue by ziedHamdi** [xiaolin/react-image-gallery#425]
Hi,

I had a working image gallery until I attempted to do ssr on my project. 

As soon as I added next.js, the styles the lib uses disappeared from the page, which causes a horrible UI

Any suggestions?

**Comment by xiaolin** [comment]
I'm not familiar with next.js but there should be a way to import your styles.

Check out the docs
https://github.com/zeit/next-plugins/tree/master/packages/next-css
