### ISSUE TITLE
lazyload will break the total Box height

### ISSUE THREAD

**Issue by xjoyzaza** [xiaolin/react-image-gallery#427]
when use lazyload , 
 the height of image is gone when loading picture and the thubnail is raiseUp...

**Comment by ramneekhanda** [comment]
https://github.com/xiaolin/react-image-gallery/blob/07f4bf05d352f4d4822bc88e126f2f18d4c50197/styles/scss/image-gallery.scss#L209

You should add the following style there i believe: 
height: calc(100vh - 40px);

**Comment by amraliabugreedah** [comment]
lazyLoad is not working with me, could you give more instructions?

**Comment by RaymondMwaura** [comment]
Great package. I'm anticipating the lazyLoad fix.

**Comment by xiaolin** [comment]
Closing this as I leave the user to resolve appropriate container sizes when using lazyLoad.
