### ISSUE TITLE
Show larger images on fullscreen

### ISSUE THREAD

**Issue by geochanto** [xiaolin/react-image-gallery#429]
Is there any way to pass a separate set of images for fullscreen mode?

It makes sense to request small images originally, and then request large images if/when fullscreen is enabled. This can help save a lot of bandwidth. Something like:

```
const images = [
      {
        original: 'http://lorempixel.com/1000/600/nature/1/',
        thumbnail: 'http://lorempixel.com/250/150/nature/1/',
        fullscreen: 'http://lorempixel.com/2000/1200/nature/1/',
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/2/',
        thumbnail: 'http://lorempixel.com/250/150/nature/2/'
        fullscreen: 'http://lorempixel.com/2000/1200/nature/2/',
      },
      {
        original: 'http://lorempixel.com/1000/600/nature/3/',
        thumbnail: 'http://lorempixel.com/250/150/nature/3/'
        fullscreen: 'http://lorempixel.com/2000/1200/nature/3/',
      }
    ]
```

**Comment by xiaolin** [comment]
see #395. I can try to implement this if no one gets to this.

**Comment by geochanto** [comment]
@xiaolin if you could add some comments in this file to describe which function does what, I think that would be helpful for all contributors: https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.jsx

**Comment by xiaolin** [comment]
I do plan to rewrite most of the lib and document it better. 

I will try to get to this soon if no one opens a PR.

**Comment by xiaolin** [comment]
fixed in https://github.com/xiaolin/react-image-gallery/releases/tag/v1.0.5
