### ISSUE TITLE
Better example for showing video in the gallery?

### ISSUE THREAD

**Issue by Eric24** [xiaolin/react-image-gallery#436]
Maybe I'm not looking in the right place, but I don't see any examples of showing videos in the gallery. I see it in the on-line demo, but I can't find how an `items` object should be configured for video. For example, what URL should be used (for original and/or thumbnail)? Is there a separate URL for the actual video? Other than YouTube (as used in the on-line demo), are other sources supported (like Vimeo, for example)?

**Comment by xiaolin** [comment]
See https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js#L149

You can use any source you like as you have control over what is rendered.
