### ISSUE TITLE
Resizing the original container.

### ISSUE THREAD

**Issue by zasuh** [xiaolin/react-image-gallery#440]
Hi!
First of all this is probably the best carousel library I've found so far, works great with my Gatsby site. 

I couldn't find a prop where you could change the size of the entire gallery container? Currently it adjusts to the size of the currently selected picture which I would like to override.

Thanks!

**Comment by xiaolin** [comment]
Hi, You'll need to override the CSS to fit your needs. There is no prop to set a fixed size to the gallery.

**Comment by zasuh** [comment]
Do I go about overriding the original library CSS or can I somehow use styled-components? Currently using styled-components but no CSS is being overriden.

**Comment by xiaolin** [comment]
You can override the styles using styled-components by doing 

```jsx
const GalleryContainer = styled.div`
  .image-gallery {
     // your styles
   }
  .image-gallery-slide {
     // your styles...
  }
`

return (
   <GalleryContainer>
     <ImageGallery items={...} />
  </GalleryContainer>
);
```

**Comment by zasuh** [comment]
Thank you that worked perfectly!

One more question: what css property does the transformation of the image container? Currently if the first image is a square and the next image a rectangle it adjusts to that next image and so on. How do you make the main image container have a fixed width and size?

**Comment by xiaolin** [comment]
Having different size images is not ideal. If you have different images you'll need to restrict the width and height of the images so that they fit the container you set. If you dig around the CSS  you'll be able to figure it out.
