### ISSUE TITLE
Change corousel height to fit available space

### ISSUE THREAD

**Issue by fortesl** [xiaolin/react-image-gallery#441]
How do I change the height of images in carousel to fit all available height? In the pick below so that I would not have all the empty white space on the phone in portrait mode.

![image](https://user-images.githubusercontent.com/1156458/66281850-baddc780-e882-11e9-99a6-70a9adb3f90e.png)

**Comment by xiaolin** [comment]
@fortesl you can override the CSS to fit your needs.
