### ISSUE TITLE
Change iframe Video to pause on swipe video.

### ISSUE THREAD

**Issue by AlaguSelvan** [xiaolin/react-image-gallery#444]
Currently, OnSwipe while playing the video and moving to the next slide, It resets the video to initial state, Instead of resetting to the initial state, Can we pause the video alone, Is this feature able to implement in this library.

**Comment by xiaolin** [comment]
The library does not officially support video slides. It was put as an example of overriding `renderItem`.

**Comment by urjit0204** [comment]
@AlaguSelvan Did you find any solution regarding this issue?
