### ISSUE TITLE
Scrollbar on vertical thumbnails

### ISSUE THREAD

**Issue by mjohnstone14** [xiaolin/react-image-gallery#453]
Hello, 

I am trying to figure out a way to add a simple black scroll bar to the thumbnails. Currently I have the carousel (float: left) on my page to achieve vertical thumbnails, but I was wondering if there is a way to incorporate scrolling instead of clicking the images/arrows to scroll?

I tried to change it through styling in renderItem and renderThumbInner, but I am not quite sure how to use these props to override what I want to do. Any guidance would be appreciated!

**Comment by xiaolin** [comment]
If you override the CSS you should be able to achieve this.

```css
.image-gallery-thumbnails {
  overflow-y: scroll
}
```

**Comment by mjohnstone14** [comment]
Thanks for the response, can you elaborate a bit more on how I would override the css? I'm a bit new to this so I am just wondering if it's as simple as including the override in className or should I do something different given that the component css is separate from my app css?

**Comment by xiaolin** [comment]
Usually based on how you order the css definitions you can override it in your own css file.

Just make sure your styles are defined after the library included css definitions. If you are unsure you can also be extra specific with your override see https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Comment by Nasridean** [comment]
Hi,
how to remove the blank space at the bottom of the thumbnails container.
