### ISSUE TITLE
ImageGallery into its own component... do not mutate state directly in  _toggleShowVideo(url) --- QUESTION

### ISSUE THREAD

**Issue by holabruno** [xiaolin/react-image-gallery#454]
Hi, 

I have made the ImageGalleyry into its own component, but i get an error / problem stating "do not mutate state directly" that points towards that code: 

_toggleShowVideo(url) {
    this.**state**.showVideo[url] = !Boolean(this.state.showVideo[url]);
    this.setState({
      showVideo: this.state.showVideo
    });

Can you help Xiaolin ?

Thanks!

**Comment by xiaolin** [comment]
I believe you're attempting to mutate state by doing
`this.state.showVideo[url] = !Boolean(this.state.showVideo[url]);`
instead you should only use `setState` function to mutate state.

**Comment by xiaolin** [comment]
Closing, as this a general react question.
