### ISSUE TITLE
Please provide a pause to autoPlay, if user hover over the gallery 

### ISSUE THREAD

**Issue by jhaankit** [xiaolin/react-image-gallery#458]
If autoPlay is true then slider keeps sliding, as per provided slideInterval time.
Please provide a **pause** functionality to sliding gallery, if user hover over the gallery.
Resume the auto play functionality, once user hover out.

**Comment by xiaolin** [comment]
This caused issues on mobile and was later removed. You can use the provided custom props below to add your needs by calling `.pause()` and `.play()` 

```
onMouseOver: Function, callback(event) on gallery slide
onMouseLeave: Function, callback(event) on gallery slide
```
