### ISSUE TITLE
Can video playback support be implemented in the main component to avoid the need for complicated workarounds?

### ISSUE THREAD

**Issue by rodnolan** [xiaolin/react-image-gallery#459]
My current project uses Typescript and functional components. I have an API that provides image and video information. Not all products have videos associated with them but I'd like to display the videos for the products that have them. 

I'm trying to follow the source code in the example in my attempt to add video playback support to my  application. When I try to add an `embedUrl` property to an item, I get this:

```console
Type '{ thumbnail: string; original: string; embedUrl: string; description: string; }' is not assignable to type 'ReactImageGalleryItem'.
      Object literal may only specify known properties, and 'embedUrl' does not exist in type 'ReactImageGalleryItem'.
```
I'm using the latest version (0.9.2) of the type definitions from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-image-gallery

I'm obviously doing something wrong but these are the challenges I face trying to translate from class-based components with plain JavaScript to functional components with Typescript.

An easier way to integrate video is a common theme in the issues list. Could the ImageGallery component cannibalize the video player functionality provided in the example? How much effort would be required to make video playback a first-class feature that doesn't require a custom renderer? 

Thanks for your efforts, by the way. This is a great component.

**Comment by xiaolin** [comment]
I do not maintain `https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-image-gallery` and not very familiar with typescript. To solve this I would define/extend my ownType for `ImageGallery` instead of using `DefinitelyTyped` and add an `embedUrl` to the type definition.

**Comment by xiaolin** [comment]
Closing this, but open to ideas. The gallery main purpose is to serve images. Displaying videos were always secondary and are possible due to the custom nature of rendering slides.
