### ISSUE TITLE
currentIndex not set when received new props

### ISSUE THREAD

**Issue by msn0** [xiaolin/react-image-gallery#46]
Hi,

I noticed the following code has been removed some time ago

```js
componentWillReceiveProps(nextProps) {
  if (this.props.items.length !== nextProps.items.length) {
    const startIndex = nextProps.startIndex || 0
    this.setState({currentIndex: startIndex})
  }
}
```

Right now, when new props arrive, currentIndex stays as before. Hence when `nextProps` has more items than before, the gallery shows no image. I guess `currentIndex` should be reset in this case or is there some other way to do it right now?

**Comment by xiaolin** [comment]
Hi, this was discussed in issue #36 

The solution is using the `slideToIndex` function

You can do so by adding a ref to the ImageGallery component

e.g.

```javascript
class MyComponent extends extends React.Component {

  _shouldResetGalleryIndex(nextProps) {
    // Your logic goes here
  }

  componentWillReceiveProps(nextProps) {
    if (this._shouldResetGalleryIndex(nextProps) && this._imageGallery) {
      this._imageGallery.slideToIndex(0)
    }
  }

  render() {
    <ImageGallery
      ref={i => this._imageGallery = i}
      items={this.props.items}
    />
  }
}
```

**Comment by msn0** [comment]
Thanks, I did as you say and works perfectly. Thanks ;)
