### ISSUE TITLE
Description Size.

### ISSUE THREAD

**Issue by facundovs** [xiaolin/react-image-gallery#461]
Hi, first at all, thank you for this incredible contribution to the community.

I am creating this issue, but it is more a query than a bug. I would like to be if there is a way to inject the style of the image description. Currently I am using your silder and the text is pretty small compared with the image and I want to modify this.

Thanks in advance for your response.

**Comment by xiaolin** [comment]
You can override the CSS for the description element. 

```css
.image-gallery-description {
  font-size: 24px;
}
```
