### ISSUE TITLE
Add mousemove event and zoom functionality to image gallery

### ISSUE THREAD

**Issue by pleaseonthekeys** [xiaolin/react-image-gallery#465]
Greetings!

I used your awesome package for a project at Hack Reactor and enjoyed its sleek look and very comprehensive API. The component I built required zoom functionality on click and a mousemove zoom feature in the expanded view. I wrote some code to accomplish that in congruence with your image gallery and was wondering if you would be interested in including that code as part of your API.

If so, I would like to integrate the code with yours and submit a pull request. What do you think? If you're interested, I can send you a demo.

Thanks!
Lauren Albert

**Comment by atikmahbub** [comment]
I need zooming  functionality with this awesome package. Can you kindly share your code?

**Comment by pleaseonthekeys** [comment]
@atikmahbub here is the link to the file using my zoom code: https://github.com/Precise-Pangolins/greenfield-NDZ/blob/master/client/components/overview-components/ImgGallery/index.jsx

You should be able to access that. Let me know that it works for you and let me know if you have any questions regarding the code.

**Comment by xiaolin** [comment]
Hi, thanks for offering but I'd like to avoid adding additional complexity to this lib. There are a bunch of zoom libraries out there that can be combined with this lib as you've already done!

**Comment by gyto23** [comment]
@xiaolin you should at least add more examples on different behaviors of the library. This is really common to have a gallery with zoom option.
