### ISSUE TITLE
onSlide transition but called at beginning of slide

### ISSUE THREAD

**Issue by louh** [xiaolin/react-image-gallery#466]
I know that #380 was a request to call the `onSlide` callback after the slide was completed, but I actually expected `onSlide` to be called during the slide. This is because I have other parts of the UI that need to be updated at the same time as the slide transition itself. When `onSlide` is called after the slide, this means the other parts of the UI only updates after a slide transition has completed, which is not what I'm looking for.

Rather than revert the current behavior, what if we had an `onBeforeSlide` callback that re-implemented the prior behavior of `onSlide`?

Happy to create a PR, if that helps! Thanks!

**Comment by xiaolin** [comment]
Sure, feel free to open a PR for `onBeforeSlide`
