### ISSUE TITLE
Transition between 2 slides bug

### ISSUE THREAD

**Issue by Sergiiivzhenko** [xiaolin/react-image-gallery#469]
Hi, @xiaolin!
Thanks a lot for your library!
It's awesome and includes a lot of cases that it's rather hard to handle when you write such functionality from scratch.

When I've integrated it to the product, where I work on, I've found one minor issue during transitions between only 2 slides and only when the user clicks on navigation buttons.

Expected behavior: the direction of animation during transition is the same as the direction of the navigation button like it happens when there are 3 slides and more.

Here is a video of that issue:
https://youtu.be/cNHVM03yyFU

I highly appreciate it if that can be fixed!
Regards.

**Comment by xiaolin** [comment]
I will take a look at this.

**Comment by Sergiiivzhenko** [comment]
awsome! looking for any update on that

**Comment by xiaolin** [comment]
Fixed in 1.0.5
 https://github.com/xiaolin/react-image-gallery/releases/tag/v1.0.5

**Comment by Sergiiivzhenko** [comment]
Thanks a lot!
