### ISSUE TITLE
Outline minor issue

### ISSUE THREAD

**Issue by Sergiiivzhenko** [xiaolin/react-image-gallery#473]
Hi, @xiaolin !
Found such minor issue, that happens when the user clicks on the slide
http://joxi.ru/5mdqjVJTekKBL2

I've fixed that such way https://github.com/Sergiiivzhenko/react-image-gallery/commit/83fc4a77a44d951662a7e3e32afa33f255982213

Looking for an update on that!
Regards!

**Comment by xiaolin** [comment]
What browser are you using? I cannot replicate using chrome.

**Comment by Sergiiivzhenko** [comment]
It's google chrome

**Comment by maxhellwig** [comment]
```css
:focus {
    outline: auto 5px -webkit-focus-ring-color
}
```
gets applied when clicking on one of the elements inside the image gallery.

You can remove it by following this blog post, but it also says that you should not remove it completely.

https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/

**Comment by xiaolin** [comment]
closing in favor of overriding css
