### ISSUE TITLE
Fullscreen swipe enhancement on mobile devices

### ISSUE THREAD

**Issue by Sergiiivzhenko** [xiaolin/react-image-gallery#475]
On mobile devices, if the gallery takes all the screen horizontal swipe works not in all cases.
Take a look here: https://youtu.be/duscRq4K0Xg

During my investigations, I've found that it's related to setScrollDirection method.

Expected behavior: during swipe, even if it goes up first and then horizontally it should swipe to the next image.

**Comment by xiaolin** [comment]
Going to mark this as wontfix as ambiguous swipes should not assume a direction. e.g. see #574 and related tickets for future improvements.
