### ISSUE TITLE
Why are the arrows different from the demo?  Is there a recommended way to change the icon?

### ISSUE THREAD

**Issue by tayloraucoin** [xiaolin/react-image-gallery#477]
Why are the arrows and other action elements different from the demo?  Is there a recommended way to change the icon?  

imo the demo version looks better and is preferred. 

demo:
<img width="797" alt="Screen Shot 2020-01-22 at 7 45 50 PM" src="https://user-images.githubusercontent.com/10913613/72955222-1065b380-3d50-11ea-8555-175eeaca23d6.png">

local (latest release):
<img width="1351" alt="Screen Shot 2020-01-22 at 7 46 20 PM" src="https://user-images.githubusercontent.com/10913613/72955223-122f7700-3d50-11ea-82b7-de27b0f21705.png">

Thank you for your time

**Comment by xiaolin** [comment]
Hmm, that is odd, Those icons are inline SVG icons and should be the same as the demo. Maybe you have some CSS overriding the SVG styles?

**Comment by tayloraucoin** [comment]
Yes @xiaolin, it turns out that `fill` was being applied.  

Altered the style thereafter by targeting `.image-gallery-icon` and `.image-gallery-svg`
