### ISSUE TITLE
Slider timer doesn't reset on keyboard events and arrow clicks

### ISSUE THREAD

**Issue by juliosouza-pushstart** [xiaolin/react-image-gallery#483]
When a user clicks on the next and previous slide arrows and the gallery is playing, the slide timer doesn't get reset, possibly causing an unwanted quick change of slides.

There's already a check in place in `slideToIndex` to see if the slideTo request comes from a user event, but that parameter is not being passed down by `slideRight`, `slideNext`, etc.

**Comment by xiaolin** [comment]
Thanks for reporting.

**Comment by xiaolin** [comment]
Fixed in https://github.com/xiaolin/react-image-gallery/commit/39b2601b5db94bf0f6ff3b38616f65fcd3e746e6
