### ISSUE TITLE
Typescript definitions out of date

### ISSUE THREAD

**Issue by thomb** [xiaolin/react-image-gallery#484]
Apologies if this is not the correct repo in which to log this, but installing the types from `@types/react-image-gallery` doesn't reflect the most up to date interface definitions.

For example it doesn't accept `renderItem` on `ReactImageGalleryProps`, and still refers to `onErrorImage` as opposed to `onErrorImageURL`.

**Comment by xiaolin** [comment]
Right, I don't maintain the type lib and I'm not sure who does. I'm sure they will accept a PR since it looks like it was generated by the community.

**Comment by ErikParso** [comment]
You can download and edit typings file from there https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-image-gallery/index.d.ts
