### ISSUE TITLE
Arrows click event and styles, horizontal scollbar

### ISSUE THREAD

**Issue by muscaiu** [xiaolin/react-image-gallery#486]
Hello, i'm implementing `react-image-gallery` into our project and i have some basic questions that should be easy for contributors/owner.
I want to mention that we are using `styled-components`, but that shouldn't be an issue.

1. How can i pause/stop a video when clicking on thumbnail or arrow?
2. How can i style the left-right arrows?
3. How can i add a horizontal scrollbar?

```
import React from 'react';
import styled from 'styled-components';
import ImageGallery from 'react-image-gallery';

const StyledGallery = styled(ImageGallery)`
  .image-gallery-thumbnails {
    overflow-x: scroll; // doesn't work
  }
  &&.image-gallery-content {
    background: yellow; //doesn't work
  }
`;

const Gallery = ({ project }) => {
  const renderVideo = item => {
    return (
      <iframe
        title="video"
        width="637"
        height="369"
        src={item.embedUrl}
        frameBorder="0"
        allowFullScreen
      />
    );
  };

  const { assets } = project;
  const { screenshots, videos } = assets;

  const items = screenshots.map(screenshot => {
    return {
      original: screenshot.url,
      thumbnail: screenshot.thumbnailUrl,
    };
  });
  const video = videos.map(vid => {
    return {
      original: vid.url,
      thumbnail: vid.thumbnailUrl,
      embedUrl: vid.url,
      renderItem: renderVideo,
    };
  });
  const allItems = [...video, ...items];

  return <StyledGallery showFullscreenButton={false} showPlayButton={false} items={allItems} />;
};

export default Gallery;
```

**Comment by muscaiu** [comment]
```
const StyledGallery = styled(ImageGallery)`
  .image-gallery-thumbnails-container {
    overflow-x: scroll;
  }
`;
```
This works for adding the scrollbar and it has the correct length, but i when i click on a thumbnail or next arrow, the whole thumbnail container slides to the left like in the pic.
![2020-02-14_18-02-17](https://user-images.githubusercontent.com/11426309/74547467-d3f33500-4f54-11ea-9b2b-cb4a6369b5ae.png)

![2020-02-14_18-01-55](https://user-images.githubusercontent.com/11426309/74547479-d6ee2580-4f54-11ea-9564-0e769907f75b.png)

**Comment by xiaolin** [comment]
The thumbnail container width is limited to the width of the gallery. If you allow scroll on the thumbnail container you're breaking the function that moves the thumbnail container x% to the left or right because the container itself has another scrollable element in it.
