### ISSUE TITLE
Two images similar?

### ISSUE THREAD

**Issue by bayssenk47** [xiaolin/react-image-gallery#488]
First, I would like to thank you so much @xiaolin, for this wonderful carousel !
To begin with, the glitch is about when there's more than two images similar in the slider, 
the carousel gets broken by two parts, I really don't know if I made something wrong, but here's the code I'm using :

```
const images = [
    {
        original: 'https://picsum.photos/id/1018/1000/600/',
        thumbnail: 'https://picsum.photos/id/1018/250/150/',
    },
    {
        original: 'https://picsum.photos/id/1015/1000/600/',
        thumbnail: 'https://picsum.photos/id/1015/250/150/',
    },
    {
        original: 'https://picsum.photos/id/1019/1000/600/',
        thumbnail: 'https://picsum.photos/id/1019/250/150/',
    },
    {
        original: 'https://picsum.photos/id/1019/1000/600/',
        thumbnail: 'https://picsum.photos/id/1019/250/150/',
    },
];

render() {

     return (
             <ImageGallery 
                   items={images} 
                   lazyLoad={true}
             />
      );
 }
```

So that's all, and please if someone has faced a similar problem, share with us the solution.

Just a few questions please ?
- Is it possible that we use the embedded video youtube directly with <iframe> (without extension video) ?
- What about if we would like to use the option of swipe touch, even if we're not in mobile device ?

And thank you guys for your time and your help !

**Comment by xiaolin** [comment]
What the error that you get when there are two images?

> Is it possible that we use the embedded video youtube directly with <iframe> (without extension video) ?
I don't understand what this means, there is an example of how to override `renderItems` in the demo. 

> What about if we would like to use the option of swipe touch, even if we're not in mobile device ?
Swipe touch is currently only supported on touch devices.

**Comment by xiaolin** [comment]
closed due to inactivity
