### ISSUE TITLE
Doesn't work as expected when images array length is 1

### ISSUE THREAD

**Issue by etshi** [xiaolin/react-image-gallery#49]
First I would like to thank you for your work.

When I pass images as an array that contains only one object, the slider doesn't work as expected.
The div with class `image-gallery-slide` is translated by `transform: translate3d(-100%, 0px, 0px);`, leading the image to slide to the left and the slider displays nothing.

Is there a way to get this to work as expected by displaying the only image ?

**Comment by tauseef-inbetween** [comment]
Facing same issue

**Comment by xiaolin** [comment]
released 0.6.1
