### ISSUE TITLE
Console Warning: Each child in a list should have a unique "key" prop after upgrading to 1.0.6

### ISSUE THREAD

**Issue by daraclare** [xiaolin/react-image-gallery#490]
Since upgrading the package to v1.0.6 I get the following warning in the console:

<img width="1000" alt="Screenshot 2020-03-11 at 14 27 54" src="https://user-images.githubusercontent.com/5235711/76427852-cccd1480-63a4-11ea-8c9c-4823bc40e6f6.png">

The issue seems to be in the ImageGallery component, which is the library package and out of my control. Is a key missing from a list / map? Or maybe a key is not unique? Perhaps source.media here is not unique?

<img width="1000" alt="Screenshot 2020-03-11 at 14 32 51" src="https://user-images.githubusercontent.com/5235711/76428252-55e44b80-63a5-11ea-9504-79dca157adf9.png">

**Comment by ahakem** [comment]
same thing here and this make the gallery break after slider number 3. we have more then className center at the time.

**Comment by xiaolin** [comment]
It seems the key should be set to `srcSet` since `media` is not unique. Will label as bug to fix.

**Comment by xiaolin** [comment]
This has bee fixed in https://github.com/xiaolin/react-image-gallery/commit/f611b5e022baab8482f864171f8e10e45d79117e
