### ISSUE TITLE
Updating state with hook in onBeforeSlide and onSlide breaks gallery

### ISSUE THREAD

**Issue by clareoneill** [xiaolin/react-image-gallery#496]
Using version 1.0.6.

I would like to change the display while the gallery is sliding and grab the current item after the transition is complete. Using the state hook inside the `onBeforeSlide` and `onSlide` functions is causing the gallery to not slide at all. I've seen other issues with solves but haven't seen any using the state hook, not sure if that would make a difference here.
 
Gallery:
```
const Gallery = props => {
  const { images } = props;

  const [isSliding, setIsSliding] = useState(false);
  const [currentObject, setCurrentObject] = useState(images[0]);

  function onBeforeSlide() {
    setIsSliding(true);
  }

  function onSlide(nextIndex) {
    setCurrentObject(images[nextIndex]);
    setIsSliding(false);
  }

  return (
    <ImageGallery
      items={images}
      onBeforeSlide={onBeforeSlide}
      onSlide={onSlide}
    />
  );
};

**Comment by xiaolin** [comment]
Hmm, what errors are you seeing? Does it only break when you use hooks?

**Comment by clareoneill** [comment]
![Screen Recording 2020-04-01 at 08 53](https://user-images.githubusercontent.com/5748453/78145281-4c735f80-73f6-11ea-8bc6-2aa2d28930ea.gif)

My gallery code has changed a bit but the issue is still there, captured in the gif. When updating the `currentIndex` state value in the `onSlide` function, it looks like what's happening is the gallery component gets reset and goes back to the first slide.

```
const [currentIndex, setCurrentIndex] = useState(0);

function onSlide(currentIndex) {
  setCurrentIndex(currentIndex);
}

...

<ImageGallery
        items={images}
        ref={imageGalleryComponentRef}
        showThumbnails={false}
        showPlayButton={false}
        showBullets={false}
        showFullscreenButton={false}
        renderLeftNav={renderLeftNav}
        renderRightNav={renderRightNav}
        onScreenChange={onScreenChange}
        onSlide={onSlide}
      />
```

I have actually found a work around, if I add `startIndex={currentIndex}` to the `ImageGallery` component the slide navigation works as expected and doesn't jump around.

**Comment by xiaolin** [comment]
I'm glad you were able to solve the issue. The gallery resets to the first slide when you pass in a different set of `items`. https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.jsx#L269

I'm guessing thats why its resetting every time and why passing an explicit `startIndex` will fix it.

Closing this, but feel free to reopen if there is an underlying bug that should be fixed.

**Comment by christopherrobinson** [comment]
Was experiencing the same issue as @clareoneil; using `startIndex={currentIndex}` solved it 👍
