### ISSUE TITLE
prop `items[0].original` is marked as required warning

### ISSUE THREAD

**Issue by tylim88** [xiaolin/react-image-gallery#499]
this happen after I update the dependency from 0.9.1 to 1.0.7

![1](https://user-images.githubusercontent.com/5227509/78500302-2f3ce900-7788-11ea-83e3-4a69d85ec92d.png)

**Comment by xiaolin** [comment]
`objects` in `items` array should have a `original` value. How are you using the library without `items[x].original` ?

**Comment by tylim88** [comment]
I use `renderItem `and `renderThumbInner`

**Comment by xiaolin** [comment]
Ah, `original` is also used as a unique key for each slide.  Will mark this as an issue and look into it. For now If you like to get rid of the error, you can probably add an index key. [{original: 0}, {original: 1}]
