### ISSUE TITLE
wrong render in codesandbox.io

### ISSUE THREAD

**Issue by LaloMores** [xiaolin/react-image-gallery#500]
Trying the plain startup example seems pretty broken.
Something to do with lib versions? (using latest react and material ui).
Tried playing with thumbnails position and other params but all were crooked.
Same happens in my local real project.

**react**: 16.13.1
**react-fom**: 16.13.1
**react-image-gallery**: 1.0.7

index.js
```
import React from "react";
import { render } from "react-dom";
import ImageGallery from "react-image-gallery";

const images = [
  {
    original: "https://picsum.photos/id/1018/1000/600/",
    thumbnail: "https://picsum.photos/id/1018/250/150/"
  },
  {
    original: "https://picsum.photos/id/1015/1000/600/",
    thumbnail: "https://picsum.photos/id/1015/250/150/"
  },
  {
    original: "https://picsum.photos/id/1019/1000/600/",
    thumbnail: "https://picsum.photos/id/1019/250/150/"
  }
];

class MyGallery extends React.Component {
  render() {
    return (
      <div style={{ display: "block" }}>
        <ImageGallery items={images} />
      </div>
    );
  }
}

const App = () => {
  return <MyGallery />;
};

render(<App />, document.getElementById("root"));
```
index.html
`<div id="root"></div>`

![Captura de pantalla de 2020-04-06 17-30-30](https://user-images.githubusercontent.com/10523351/78602439-d5dac580-782c-11ea-8ab6-9287cdf18911.png)
![Captura de pantalla de 2020-04-06 17-30-17](https://user-images.githubusercontent.com/10523351/78602449-d7a48900-782c-11ea-97d6-2ce5d7cda58d.png)

**Comment by LaloMores** [comment]
I see I didn't import any css. I don't use webpack My fault.

**Comment by mykter** [comment]
How did you fix this? I'm using an out-of-the-box Gatsby site (gatsby-starter-default) and am having the same issue.
