### ISSUE TITLE
bug disableArrowKeys has no effect

### ISSUE THREAD

**Issue by citizen-dror** [xiaolin/react-image-gallery#503]
I need to disable the right and left keyboard , because I'm editing text next to a gallery,

I set disableArrowKeys = true , but it has no effect – right and left key strokes keep on  slide the images.

one more thing - disableArrowKeys  is called disableKeyDown in README.md

```
   <ImageGallery
                items={images}
                disableArrowKeys
                isRTL={isRTL}
                onSlide={(currentIndex: number) => handleOnSlide(currentIndex)}
              />
```
 "react-image-gallery": "^1.0.7",

**Comment by xiaolin** [comment]
In a recent update the prop was changed to `disableKeyDown` please use that.

**Comment by citizen-dror** [comment]
Thanks!  I'm using 1.0.7 ver , 

Maybe the problem is that i 'm using typescript? 
https://www.npmjs.com/package/@types/react-image-gallery
it says 
// Type definitions for react-image-gallery 0.9  
Please make a note about this, as it's very confusing.

**Comment by citizen-dror** [comment]
a work-around to this issue is using `// @ts-ignore` 
```
     <ImageGallery
            items={images}
            // @ts-ignore
            disableKeyDown
            onSlide={(currentIndex: number) => handleOnSlide(currentIndex)}
          />
```

**Comment by xiaolin** [comment]
I don't maintain that typescript definition. Someone would need to update it.
