### ISSUE TITLE
Google Lighthouse audit error - does not use passive listeners

### ISSUE THREAD

**Issue by a-tonchev** [xiaolin/react-image-gallery#510]
When I make audit on my code it pop-up google chrome message to make the event listeners as passive:

![image](https://user-images.githubusercontent.com/54528540/80967449-12471480-8e1f-11ea-8e67-4406bcd79f05.png)

Can you add this short fix?

With best regards

**Comment by xiaolin** [comment]
Can you show more debug information? I can't tell which line or function is causing this issue.

**Comment by a-tonchev** [comment]
Hello @xiaolin ,

thanks for the response. You can just open your demo here:

https://www.linxtion.com/demo/react-image-gallery/

And make Audit with google Lighthouse + Generate report. You will see under best practices the message I told you about:

![image](https://user-images.githubusercontent.com/54528540/82199478-6a454700-9906-11ea-98c1-d993b2451507.png)

**Comment by a-tonchev** [comment]
The error is comming from

react-swipable:

https://github.com/FormidableLabs/react-swipeable/commit/939ee9fdbc108e07af4ac1dfc5739f2db1a6f7d4

https://github.com/FormidableLabs/react-swipeable/pull/170

There are some suggestions how to fix this, 

https://github.com/FormidableLabs/react-swipeable/blob/4.x/src/Swipeable.js#L80-L105

Best regards

**Comment by xiaolin** [comment]
I ran the audit on chrome incognito and I don't see the warning.

![image](https://user-images.githubusercontent.com/1286776/108791623-5f25e400-7534-11eb-8bfe-402fb5222be6.png)

**Comment by xiaolin** [comment]
closing, feel free to open with steps to reproduce if the issue still exists.
