### ISSUE TITLE
Up and Down swipes on gallery causes movement

### ISSUE THREAD

**Issue by liverpool-Never-Walk-Alone** [xiaolin/react-image-gallery#512]
**Hello,
I realy like you galerry.** 

But I have found 1 bug. Maybe, you are aware of it and can help me to solve it. Maybe you can add "prop" or I can make a Pull requrest. It seems to me I found the sollution but it looks not proper. 

The issue is next - when the user swipes up and down fast, the slide is twigging from left to right. I looked at the code and found that the bug appears when the user swipes up-down quickly and sometimes it can triggers the left-right event. This behaviour comes from "react-swipeable".
https://www.youtube.com/watch?v=Q3Y3lvMXPNk
https://www.youtube.com/watch?v=B60C-pl7qug

**Expected result** - when user swipes up-down slide has not to be moved rigt-left.

Looking forward to your reply.

**Comment by xiaolin** [comment]
Hi, very late, but recently discovered this can be done via CSS using `touch-action: pan-x` which will disable up and down swipes on the element. you can do so by overriding css like so

```css
.image-gallery-swipe {
  touch-action: pan-x;
}
```
