### ISSUE TITLE
Buttons Dissappeared After Updating Package

### ISSUE THREAD

**Issue by SandMoshi** [xiaolin/react-image-gallery#513]
I updated from an old version to the latest `1.0.7` and the button icons (fullscreen, left, right, play) all disappeared.

When I inspect them, there is no `content` css property like there was before. I checked the old version and it had `content` css property applied to the `::before` pseudo-elements.

I am using the css import into my React application using:

`import ImageGallery from 'react-image-gallery';`
`import "react-image-gallery/styles/css/image-gallery.css";`

This is how I'm using the component:
```
         return(
                <ImageGallery 
                    items={items} 
                    lazyLoad={true}
                    showNavigation={true}
                    showPlayButton={true} 
                    slideInterval={10000} 
                    slideDuration={600} 
                    showFullscreenButton={true} 
                    useBrowserFullscreen={true} 
                    startIndex={startIndex}
                    showIndex={true}
                />
         )
```

When I inspect a button I see that it's just a button with nothing inside. Whereas inspecting the demo reveals there should be an `<svg>` element.

Here is what I see in Chrome inspector:

`<button type="button" class="image-gallery-left-nav" aria-label="Previous Slide"></button>`

### UPDATE: SOLUTION FOUND

In the end, it appears to have been a webpack/react issue related to going from the old package to the new one.

I was able to resolve the issue by doing the following.

1. Manually removed everything in `node_modules/react-image-gallery'
2. Terminated the local development server that was running React
3. Reinstalled the package using `npm install react-image-gallery`
4. Restarted the development server with `npm run start`

That fixed the issue. I am guessing the development server was still using the old files.

**Comment by xiaolin** [comment]
Glad you were able to fix it. Closing.
