### ISSUE TITLE
Image Description Proptypes

### ISSUE THREAD

**Issue by SandMoshi** [xiaolin/react-image-gallery#514]
For a while now this library has allowed you to use strings and arrays as a description. The array is useful for including several HTML elements or stylized content in the description box.

However now I'm getting a `propType` warning saying the description should be a string.

I think the prop types should be changed to allow for an array as well as a string, since the functionality is there and there is a legitimate use cases for using a non-string description.

**Comment by AustinLeeGordon** [comment]
It should be `PropTypes.node` with the way it's implemented. That covers anything that can be rendered (strings, arrays, elements, etc).

https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes

**Comment by xiaolin** [comment]
Feel free to open a PR on the proposed solution, and I can take a look.

**Comment by AustinLeeGordon** [comment]
@xiaolin Opened a PR #519
