### ISSUE TITLE
Hiding the Thumbnails on Fullscreen

### ISSUE THREAD

**Issue by SandMoshi** [xiaolin/react-image-gallery#515]
Hi,

I am wondering what is the best way to hide the thumbnails when full-screen mode is entered.

What I have come up with is:

use `onScreenChange` to trigger a function that changes the `showThumbnails` prop. Is that the best approach?

Also, the documentation doesn't really talk much about how `onScreenChange` works. What is a screen change in this context? Is it only triggered on the fullscreen being toggled? Does it trigger for any other events? Adding a sentence to the documentation would help a lot.

**Comment by xiaolin** [comment]
Yes, using `onScreenChange` is the proper approach. As fullscreen toggles will trigger a callback to `onScreenChange`. I've also updated the docs.

**Comment by SandMoshi** [comment]
Thank you, it worked.

Keep up the amazing work!

**Comment by tokict** [comment]
@xiaolin This approach does hide thumbnails, but it does not reuse the space left by them so I end up with an image that is not fullscreen but has a gap where the thumbnails should be
