### ISSUE TITLE
请问左右切换图片如何改为上下键切换呢？

### ISSUE THREAD

**Issue by tiantian000** [xiaolin/react-image-gallery#516]
请问左右切换图片如何改为上下键切换呢？

**Comment by xiaolin** [comment]
I did a google translate and it said
> How can I switch the left and right pictures to the up and down keys?

You can override your own keydown event listener for up and down arrow keys and then call `slideToIndex` [listed in docs](https://github.com/xiaolin/react-image-gallery#functions)
