### ISSUE TITLE
Changes slide while focused anywhere on page and left or right arrow is pressed

### ISSUE THREAD

**Issue by AustinLeeGordon** [xiaolin/react-image-gallery#517]
Whenever I'm focused outside of the slider (ex in a form input trying to move between characters), pressing the right and left arrow keys still causes the slide to change.

https://github.com/xiaolin/react-image-gallery/blob/6f1ee5ec5f5b3c21a80de5e331ad09a58772d362/src/ImageGallery.jsx#L252

Need to move this listener off the window.

**Comment by AustinLeeGordon** [comment]
Created a PR #518

**Comment by xiaolin** [comment]
released in v1.0.9
