### ISSUE TITLE
Prevent moving next slide if onBeforeSlide returns false

### ISSUE THREAD

**Issue by ivenxu** [xiaolin/react-image-gallery#520]
This is not a defect, more about feature request.

In some of the scenario, there's a need to pub some logic in onBeforeSlide event to determine whether should go to next slide. 

Do you think it's good idea?

**Comment by xiaolin** [comment]
Hmm, need to think a bit about this. What is your current use case for this?

This could be accomplished by adding a boolean to prevent sliding, like `disableSlide`. This way the Gallery does not have to deal with conditional logic based on an optional `onBeforeSlide` prop.

**Comment by ivenxu** [comment]
@xiaolin Thanks for reply!

My scenario is asking user to provide "yes" or "no" feedback before showing next slid. The workaround I use now is using MUI modal dialog.

![image](https://user-images.githubusercontent.com/248655/84448181-54207180-ac8d-11ea-8e5f-46a36fdda8fe.png)

I'm happen with the current workaround, but now I'm facing a problem that it doesn't work in fullscreen mode. It's really strange, the dialog has higher z-index, but I can see it. Do you have any hint about this?

**Comment by xiaolin** [comment]
`z-index` is a bit tricky and may depend on where your have your elements. 
Your modal dialog would need to be in the container of the fullscreen element otherwise it may not show is my guess.

You can read more about them here https://developer.mozilla.org/en-US/docs/Web/CSS/z-index

**Comment by ivenxu** [comment]
> `z-index` is a bit tricky and may depend on where your have your elements.
> Your modal dialog would need to be in the container of the fullscreen element otherwise it may not show is my guess.
> 
> You can read more about them here https://developer.mozilla.org/en-US/docs/Web/CSS/z-index

How can I make sure the dialog is alway in the fullscreen element?

This is the current code. Should I make it be child element of the ImageGallery?
```
<ImageGallery showThumbnails={false} items={imageList} onBeforeSlide={handleBeforeSlide} />
 <ConfirmationDialogRaw open={open} onClose={handleClose} />
```

**Comment by AustinLeeGordon** [comment]
@ivenxu What's the dialog's css `position`? For `z-index` to work, it need to be one of `absolute`, `relative`, `fixed`, or `sticky`.

**Comment by ivenxu** [comment]
@AustinLeeGordon 
it's fixed.

![image](https://user-images.githubusercontent.com/248655/84907089-1f317600-b0f6-11ea-8d68-f9d7ab4cad83.png)
