### ISSUE TITLE
Arrows on thumbs 

### ISSUE THREAD

**Issue by Petrik626** [xiaolin/react-image-gallery#522]
Is it possible to display arrows for thumbnails?

**Comment by nativ3-io** [comment]
simple way to do it is just create a wrapper of the component and add
`<Button onClick={()=>gallery.current.slideToIndex(gallery.current.getCurrentIndex() - 1)}>Left</Button>`
`<Button onClick={()=>gallery.current.slideToIndex(gallery.current.getCurrentIndex() + 1)}>Right</Button>`

**Comment by xiaolin** [comment]
You can add your own button/icons as @nativ3-io pointed out.
