### ISSUE TITLE
Add aria label to image-gallery-slide

### ISSUE THREAD

**Issue by a-tonchev** [xiaolin/react-image-gallery#525]
image-gallery-slide has role button thats why it is recommendet to have aria-label.

**Comment by mattschwartziq** [comment]
+1. Getting this accessbility error in Lighthouse:
![image](https://user-images.githubusercontent.com/59023472/84825046-72b49e80-afe6-11ea-93ba-cc6047289239.png)

**Comment by mattdell** [comment]
Have raised a PR for this. Needed for me so that I can add this on to a page without my accessibility score plummeting.

**Comment by xiaolin** [comment]
pr merged. closing.
