### ISSUE TITLE
Custom Thumbnail sizes 

### ISSUE THREAD

**Issue by HanliTheron** [xiaolin/react-image-gallery#528]
Hi, this isn't really an issue but more of a question. 

Does this package support custom thumbnail sizes, e.g. if I want to build something like this: 

![image](https://user-images.githubusercontent.com/46846877/86044730-ce514400-ba4a-11ea-9d8d-7eb30e0c2a5f.png)

**Comment by xiaolin** [comment]
If you modify the thumbnail CSS the thumbnails can be as large as you like.
