### ISSUE TITLE
Thumbnail navigation buttons

### ISSUE THREAD

**Issue by elisabedashvili-exceed** [xiaolin/react-image-gallery#529]
I am trying to manually implement this latter. Appending button itself isn't hard, the thing is I don't know how to give functionality to it so that on click it renders next/previous 5 (for example) thumbs.

**Comment by thug1705** [comment]
@elisabedashvili-exceed did you manage to achieve this, do you have any code example ?

**Comment by jw-miaem** [comment]
@elisabedashvili-exceed @xiaolin any movement on this - id also like to have this feature and thinking about adding myself

**Comment by xiaolin** [comment]
Thumbnail swipe support was released in `1.2.2` for mobile devices. Not sure if we still need explicit thumbnail navigation buttons, but leaning towards not adding these. If there is a strong argument against it, I may reconsider.
