### ISSUE TITLE
Navigation buttons resize based on total screen width - not carousel width

### ISSUE THREAD

**Issue by alexfiftysix** [xiaolin/react-image-gallery#536]
I am trying to create a carousel which is at most 320px wide.
On mobile this works great! On desktop the navigation buttons are huge. 

Is there a way to resize the navigation buttons based on the width of the carousel - rather than the width of the screen - without implementing custom nav buttons?

Eg:
![image](https://user-images.githubusercontent.com/25026852/88605819-6845f400-d0be-11ea-8ea5-f56a2d780fb4.png)

**Comment by alex-zwingli** [comment]
I am having the same issue. Here is another example.

![image](https://user-images.githubusercontent.com/21690533/89854356-93adf180-db48-11ea-8eda-aa87e67112e9.png)

**Comment by xiaolin** [comment]
You can resize via CSS. I'm also a bit surprised why it's larger than it should be. If you look at the [example ](https://www.linxtion.com/demo/react-image-gallery/)in 320px the arrows are not that big.

**Comment by alex-zwingli** [comment]
@xiaolin Can you please provide a react snippet for resizing the arrows/

**Comment by xiaolin** [comment]
You can override the following class via CSS.

https://github.com/xiaolin/react-image-gallery/blob/master/styles/scss/image-gallery.scss#L57
