### ISSUE TITLE
Unexpected sliding direction in a 2-image gallery

### ISSUE THREAD

**Issue by gaborluk** [xiaolin/react-image-gallery#54]
When the gallery only contains a total of 2 images, sliding direction is the opposite of what you would expect based on the order of the thumbnails. For example, when `image #1` is active, and you click `thumbnail #2`, you would expect that `image #1` slides out to the left, and `image #2` slides in from the right, however, it happens the other way around. Similarly, swiping left on `image #1` results in a bounce and slide backwards, arriving on `image #2`.

I haven't had time to look into this in detail, but if nobody picks it up and you don't have time either, @xiaolin, I might track this down sometime next week.

**Comment by xiaolin** [comment]
I don't have much time this week, but maybe next week if its not already fixed, I can take a look at it.

**Comment by xiaolin** [comment]
#64 fixes desktop sliding directions when there are 2 images, but mobile swipe is weird, and not seamless. So keeping this open for now.

**Comment by keustma** [comment]
Do you have an example what you mean with "not seamless"?
I tested this on mobile and it worked fine for me. Only what's not intuitive is if you swipe right on the last photo and it jumps to the right.

**Comment by xiaolin** [comment]
Right, thats exactly it, the swipe is not continuous compared to when there are 3 or more images.

**Comment by texate** [comment]
@gaborluk @xiaolin is there any progress in fixing this issue? it would be great to deal with this weird 2images swipe on mobile devices. Thanks in advance.

**Comment by xiaolin** [comment]
Been rather busy. I will try to get to this soon once I get some free time.

**Comment by xiaolin** [comment]
@texate not sure if you tried this or if this can be a solution for now, but you can disable `infinite` which would **not** allow users to swipe before the first element or beyond the last element.

**Comment by xiaolin** [comment]
@gaborluk @texate this issue is now fixed in v0.6.6 🎉

**Comment by texate** [comment]
great news, @xiaolin ! 
works like a sharm, thank you!

**Comment by gaborluk** [comment]
Thank you, @xiaolin!
