### ISSUE TITLE
Pinch-Zoom don't works on Android mobiles.

### ISSUE THREAD

**Issue by yupparslan-bit** [xiaolin/react-image-gallery#540]
While going to fullScreen functionality,it works fine but with following issue.
i) Pinch-Zoom works fine on Iphone devices and images are displaying on the middle of page. Whereas on android devices images are showing on top of the screen and pinch-zoom don't works.

**Comment by xiaolin** [comment]
Closing this as its quite old, feel free to reopen if its still an issue.

**Comment by DrAndri** [comment]
Hi!

I just noticed this behavior on android mobile as well. When in browser fullscreen you can't pinch zoom images

Haven't tried iOS or css fullscreen
