### ISSUE TITLE
original property as array?

### ISSUE THREAD

**Issue by foubei** [xiaolin/react-image-gallery#541]
Hello,

Is there a possibility to show a less quality image while the original quality is still loading (like implementing the [lqip plugin](https://github.com/zouhir/lqip)?

Or maybe we can send an array of images to `original` parameter and show the images on top of each other (just like background-image works).

Is there any way to make it working with the current version of your awesome library?

**Comment by xiaolin** [comment]
There is a prop called `renderItems` that you can use to override the render function. This way you can handle the logic on how and when the images are rendered. Take a look and see if that works.
