### ISSUE TITLE
Does it support rotate?

### ISSUE THREAD

**Issue by Uyarn** [xiaolin/react-image-gallery#543]
Does it support rotate?

**Comment by MarcLongJoyride** [comment]
If it does, I can't figure it out. This gallery causes our website's pages to freeze when a user rotates their phones.

**Comment by xiaolin** [comment]
@MarcLongJoyride are you sure its the gallery causing the freeze? Check out the demo https://www.linxtion.com/demo/react-image-gallery/ it works fine for me.

**Comment by xiaolin** [comment]
@Uyarn the gallery itself does not have a rotate function if that's what you're asking.

**Comment by MarcLongJoyride** [comment]
@xiaolin thank you for the quick response. I see the demo page does work on mobile. It appears this must be something custom one of our devs did, and not react-image-gallery. Thank you again.
