### ISSUE TITLE
Current image not in sync with fullscreen mode.

### ISSUE THREAD

**Issue by ErikParso** [xiaolin/react-image-gallery#551]
Hello. I have an issue when i switch to fullscreen mode, swipe few images and exit fullscreen, gallery is showing first image (same as before going to fullscreen mode). I am using Safari on IPad Air 2 and browserfullscreen mode is on. When running on other browser or device, images are in sync with fullscreen mode correctly. Any clues what an cause this issue ?

**Comment by xiaolin** [comment]
Are you seeing this with the demo gallery? I'm not able to replicate.

**Comment by ErikParso** [comment]
I have seen this behavior on one of browserstacks iPad air devices.

**Comment by 0bhat** [comment]
https://user-images.githubusercontent.com/10598279/123908692-80d92100-d995-11eb-80c9-4388973ac6ad.mp4

****

Full screen doesn't work on Safari, trying to port video of the behavior.
