### ISSUE TITLE
Bug: Image cutted with space between

### ISSUE THREAD

**Issue by agustindiazg** [xiaolin/react-image-gallery#552]
- I'm running react-image-gallery: 0.8.12
and sometimes we had this problems with the images. It's not always. 
Look like the image end up cutted in half with an space between.

![image (29)](https://user-images.githubusercontent.com/4489093/97037171-4afab780-153f-11eb-81b1-17072a837386.png)

Have someone spotted this before ?

**Comment by xiaolin** [comment]
I suggest updating to use the latest version. May be related to CSS or different image sizes?
