### ISSUE TITLE
exporting description

### ISSUE THREAD

**Issue by ziofitt** [xiaolin/react-image-gallery#553]
Hi,

I am a newbie to React, so I apologize in advance if I'll be asking something very obvious. Is there any way I can "export" the description so that I can show it, for example, in a different div? Ideally, I would like the description to appear on the side of the picture.

Thanks in advance.

**Comment by xiaolin** [comment]
You can try to use CSS to move the description around.

**Comment by ziofitt** [comment]
Thank you! What if I used getCurrentIndex() to know the current index and visualize the description straight from the list I feed to "items"? That should be possible by using refs right?

Thanks a lot for your help!

**Comment by xiaolin** [comment]
I'm not sure what that means, but if you need to move the description element you can do so using CSS.
