### ISSUE TITLE
Align image description with image

### ISSUE THREAD

**Issue by angelachan1997** [xiaolin/react-image-gallery#556]
Hi.... me again! Is there any way I can align the image description with the image?

Right now it is aligned left with the div:
![Screen Shot 2020-11-14 at 5 13 42 PM](https://user-images.githubusercontent.com/67937939/99158066-c19d5780-269c-11eb-85a6-19055c24c72c.png)

But I want it to be:
<img width="779" alt="Screen Shot 2020-11-14 at 5 14 13 PM" src="https://user-images.githubusercontent.com/67937939/99158071-d37efa80-269c-11eb-9d76-b4da51933540.png">

Let me know if there is any way I can do that.... thanks! :D

**Comment by xiaolin** [comment]
If you have consistent image sizes then you can use CSS to move the title over towards the image. It seems like you may have different size images, which makes it difficult to align the titles. I suggest using the same image sizes or you can try to override the `renderItem` and customize the rendered slide there.
