### ISSUE TITLE
Slider jumps between images after X slide

### ISSUE THREAD

**Issue by dylanesque** [xiaolin/react-image-gallery#557]
I have a site live using this library(https://www.intimatesmovie.com/), and I just noticed the slider stops smoothly scrolling after the 12th slide and just jumps from image to image. Has anybody encountered behavior like this before? I'm using version 1.0.8 of this library, with version 10.3.2 of Preact, and this error is present in both dev and prod versions of the site.

**Comment by xiaolin** [comment]
Hmm, thats odd. I'm not able to replicate this, the [demo site](https://www.linxtion.com/demo/react-image-gallery/) also has 13 slides and is not having issues. 

I've not tried Preact and unsure if that may cause an issue.

**Comment by Karol-Waliszewski** [comment]
I have the same problem, but not exactly after 12 images.
