### ISSUE TITLE
Cumulative Layout Shift

### ISSUE THREAD

**Issue by noii98** [xiaolin/react-image-gallery#559]
Allow height and width attributes to avoid CLS. 

It's pretty easy I guess. All you have to do is replace
`              <img
                className="image-gallery-image"
                alt={item.originalAlt}
                src={itemSrc}
              />`

with

`              <img
                className="image-gallery-image"
                alt={item.originalAlt}
                src={itemSrc}
                height={item.height}
                width={item.width}
              />`

**Comment by noii98** [comment]
#560 @xiaolin  Please add node version to the package.json file so that I can test these. As I am not able to install the packages on the latest node version.

**Comment by xiaolin** [comment]
Hi, you can use `renderItem` to customize your `<img>` render.

I'm not sure why you're unable to install packages, what node version are you using, and whats the error?

**Comment by noii98** [comment]
> I'm not sure why you're unable to install packages, what node version are you using, and whats the error?

Don't worry about it. It seems to be my local issue with visual studio version.

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Personal projects\\Open Source\\react-image-gallery\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Personal projects\Open Source\react-image-gallery\node_modules\node-sass
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.


> Can you explain a little why you need custom height and width on each image.

CLS(Cumulative Layout Shift) is a core web vital now. And from next year Google is going to use it as a page rank factor. So, for SEO and better UX it is important to add the height and width tags. Especially, for images which are above the fold or are loaded lazily. More about why it is necessary:
[https://web.dev/optimize-cls/](https://web.dev/optimize-cls/)

**Comment by xiaolin** [comment]
this should be fixed, and using yarn install should allow you to install this package locally.
