### ISSUE TITLE
fullscreen image not used

### ISSUE THREAD

**Issue by Kaeon** [xiaolin/react-image-gallery#563]
Hi, I work with HML5 srcSet & Sizes attributes which works great. But if I set the image in fullscreen mode it doesn't take the image from the fullscreen attribute (or the default original image). It still defaults to the tiny image calculated by the srcset & sizes which is very poor quality in fullscreen mode. Is this expected? How can this be fixed?

**Comment by xiaolin** [comment]
Take a look at the 2nd slide https://www.linxtion.com/demo/react-image-gallery/ it's using the code below and it swaps between cropped/default when you go from mobile to desktop. Not sure if this will help answer your question but you should be able to do the same depending on what media you expect at certain screen widths.
```js
      {
        original: `${PREFIX_URL}image_set_default.jpg`,
        thumbnail: `${PREFIX_URL}image_set_thumb.jpg`,
        imageSet: [
          {
            srcSet: `${PREFIX_URL}image_set_cropped.jpg`,
            media : '(max-width: 1280px)',
          },
          {
            srcSet: `${PREFIX_URL}image_set_default.jpg`,
            media : '(min-width: 1280px)',
          }
        ]
      },
```

**Comment by Kaeon** [comment]
If anyone else struggles with this: I added "**(display-mode: fullscreen) 100vw,**' as the first entry in sizes  which makes sure the image width is set to full width when in fullscreen.
