### ISSUE TITLE
onScreenChange type is (fullScreenElement: Element) => void; should be (fullScreen: boolean) => void

### ISSUE THREAD

**Issue by TrevorJamesH** [xiaolin/react-image-gallery#565]
According to the docs, and the logic, the callback for onScreenChange is passed a boolean. The type definition is asking for an Element.

**Comment by TrevorJamesH** [comment]
I realized this is actually coming from @types/react-image-gallery, I am unsure how that is maintained.

**Comment by TrevorJamesH** [comment]
I created a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50330

**Comment by xiaolin** [comment]
I'm not sure who maintains that glad a PR was opened! Closing this.
