### ISSUE TITLE
onImageLoad is not consistently called

### ISSUE THREAD

**Issue by sfurey** [xiaolin/react-image-gallery#566]
Is the expected behavior that this callback is triggered on every image load?  

If not is there another available callback that occurs on every image load?

Is it possible that images are being cached which could prevent this callback?

**Comment by sfurey** [comment]
I disabled caching and my GraphQL layer and now onImageLoad is called consistently.  That's not an ideal solution.  Is there any other method that is fired when a different is loaded?

**Comment by xiaolin** [comment]
I'm looking at the example and despite the images being loaded from cache, `onImageLoad` is called.

![image](https://user-images.githubusercontent.com/1286776/104858882-0335c300-58d7-11eb-98b0-c94ba06d504d.png)
