### ISSUE TITLE
CSS File is missing from /styles directory

### ISSUE THREAD

**Issue by tayloraucoin** [xiaolin/react-image-gallery#567]
Importing the stylesheet into Next.js has been a little problematic.

Just trying to copy the css file and keep locally in /public for now.  CSS file isn't available, only SASS.

Please add css into the /styles dir

**Comment by xiaolin** [comment]
Check `node_modules/react-image-gallery/styles` CSS files are not available on github because its ignored by .gitignore but package content does.

**Comment by tayloraucoin** [comment]
Thank you, that worked perfectly.
