### ISSUE TITLE
Cannot set % based height

### ISSUE THREAD

**Issue by k-ahn** [xiaolin/react-image-gallery#569]
**Background**: I have a React app that uses a combination of fixed height and % based divs to display content. 
**Desired Outcome**: I want `<imageGallery>` to be responsive within a variable height div, not anchor to the viewport height
**Current Behaviour**: `<imageGallery>` works perfectly with % on width but doesn't display as expected when substituting vh for % on height. 

An example is:

```
<div style={{ height: '100%', width: '100%' }}>
  <div style={{ backgroundColor: 'grey', height: '200px', width: '100%' }}>
  </div>
  <div style={{ backgroundColor: 'lightblue', height: 'calc(100% - 200px)', width: '100%' }}>
      <ImageGallery 
        showThumbnails={false}
        items={images} 
      />
  </div>
</div>
```
On investigation the issue is:
`.image-gallery-content .image-gallery-slide .image-gallery-image { max-height: calc(100vh - 80px); }`

I can override this in my css. For example, this works:
`.image-gallery-content .image-gallery-slide .image-gallery-image { max-height: 100vh!important; }`

When i change it to % it breaks max-height completely and just stays full width.
`.image-gallery-content .image-gallery-slide .image-gallery-image { max-height: 100%!important; }`

The attached screenshot illustrates the issue. The grey div is fixed. The lightblue varies. The default css is causing the scrollbars.

![image](https://user-images.githubusercontent.com/53981218/107285298-d5b3e380-6a56-11eb-9da1-03e13dcb7fa2.png)

UPDATE:

The answer was staring at me - use a variation of the base css:

.image-gallery-content .image-gallery-slide .image-gallery-image { max-height: calc(100vh - 200px); }

So the 200px is the fixed height and the 100vh deals with the variable div

This said i'd appreciate a steer on whether this is the correct - i feel there may be a better way. Thankyou

**Comment by k-ahn** [comment]
The answer was staring at me - use a variation of the base css:

`.image-gallery-content .image-gallery-slide .image-gallery-image { max-height: calc(100vh - 200px); }`

So the 200px is the fixed height and the 100vh deals with the variable div

This said i'd appreciate a steer on whether this is the correct - i feel there may be a better way. Thankyou

**Comment by xiaolin** [comment]
That looks fine to me based on your requirements 😄.
