### ISSUE TITLE
Question: Is there a way to get my hands on the current index in the callback of onClick?

### ISSUE THREAD

**Issue by gaborluk** [xiaolin/react-image-gallery#57]

**Comment by xiaolin** [comment]
There is no clean solution I can think of.
We can modify the code to attach the currentIndex to the callback of onClick (someone can open a PR 😄 )

**Comment by gaborluk** [comment]
Thanks for the reply, @xiaolin. I have the changeset for the latter locally, it's basically a `this.props.onClick.bind(this, currentIndex)`, however, this will not be backwards-compatible, as the first argument of the callback is now `currentIndex`, as opposed to `event`. Do you consider this a problem?

**Comment by xiaolin** [comment]
I will document it in the release, so it should be okay.

**Comment by xiaolin** [comment]
@gaborluk Hey I'm curious why you need the currentIndex when an image is clicked?

**Comment by gaborluk** [comment]
I want to open the current image on a large modal and allow zooming on user interaction. The full screen behavior that has been merged last week didn't quite work out for me, especially after discovering that Safari on iOS has no support for the feature yet.

**Comment by xiaolin** [comment]
You can open the image in a modal using `event.target.src`, I'm not sure why you need the `currentIndex`?

**Comment by gaborluk** [comment]
I'm using `srcset` and `sizes` on the image element to deliver optimally sized images to the client in an adaptive manner, and I'm generating the values of these attributes dynamically, based on a base URL, a file name, a file extension, and a rather large set of predefined pixel dimension suffixes (e.g., `_880x880`). So instead of stripping down the `event.target.src` string to its useful components that I can then use to generate these attribute values, I simply refer to the appropriate image object in my already existing data structure using `currentIndex`, since this object already has the snippets of data that I need in a consistent format.

Hope this makes sense. In fact, I would like to contribute `srcset` and `sizes` handling to the project once I get there, so that the images displayed by the gallery can be optimized as well.

**Comment by gaborluk** [comment]
For what it's worth, a `data-index` attribute on the images would probably work just as well, if you'd prefer keeping the signature of the `onClick` callback intact.

**Comment by xiaolin** [comment]
I only ask because as I was looking through #59 I realize its a bit awkward passing in `currentIndex` into all the onclick handler. This is my fault for suggesting that. What about adding a public function called `getCurrentIndex()` which will just return the current index?

**Comment by gaborluk** [comment]
I totally get your point and it's a good one, a `getCurrentIndex()` is absolutely fine, too.

**Comment by gaborluk** [comment]
I've updated the PR to use `getCurrentIndex()` instead of the modified signature. Don't merge yet, though – apparently there's an issue regarding the removal of `onTouchStart`. I should have known better than to handle two issues in one PR, but let's try and fix that one, too. I'll add my comment about it on https://github.com/xiaolin/react-image-gallery/issues/58.

**Comment by xiaolin** [comment]
Cool, yeah I think I looked into it once, and maybe even tried to remove it myself, haha. I can't remember. It definitely needs a fix sooner or later.

Thanks!

**Comment by nitiandiv** [comment]
I am not able use getCurrentIndex()

**Comment by nitiandiv** [comment]
Many things in this library seems unresolved.
I got screwed after choosing this library.

**Comment by xiaolin** [comment]
@nitiandiv this is 4 years old... Can you list the problems that are unresolved? `getCurrentIndex` is working and there is a live example of it working on the [demo page](https://www.linxtion.com/demo/react-image-gallery/)

There is also an example of how it is used.
https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js#L72
