### ISSUE TITLE
Disable Transition animations?

### ISSUE THREAD

**Issue by GN** [xiaolin/react-image-gallery#570]
I can't seem to find anything about it in any of the docs, but maybe I missed it. I'm basically just looking to disable transition animations on index changes and left/right nav button clicks.

**Comment by xiaolin** [comment]
Take a look at the demo, if you set `slideDuration` to 0 that should do the trick.

**Comment by GN** [comment]
@xiaolin thank you! 

Is there a way to disable the sliding on the thumbnails as well?

**Comment by mislavmiocevic** [comment]
@xiaolin what about the animations after exiting the fullscreen, there is slight "resizing" between the fullscreen image and the container image. 
Can this be disabled/improved somehow?

You can easily see here by resizing the screen, opening any of the images in fullscreen and exiting.
You will see that the gallery container image has some "resizing" going on.
https://www.linxtion.com/demo/react-image-gallery/

Same happens for entering the fullscreen where bigger image is "adjusting" to width, but more important is for exiting.

Thanks.

**Comment by xiaolin** [comment]
If you remove the width transition from the CSS that would prevent the resizing animation.

**Comment by xiaolin** [comment]
If you remove the width transition from the CSS that would prevent the resizing animation. The transition is only on the demo, the image gallery does not have that built in.
