### ISSUE TITLE
Please add onClick for image

### ISSUE THREAD

**Issue by Navipro70** [xiaolin/react-image-gallery#573]
**Feature**

Default full screen mode is looks like so bad. And for custom modal I need to use renderItem, but it will be good idea to make onClick for every image that looks like that: `(item: GaleryItem, index: number) => void`.

**Comment by Navipro70** [comment]
UPD: I cant get index in renderItem. Is this lib have any way to get index of item??????

**Comment by xiaolin** [comment]
Please see doc for getting index https://github.com/xiaolin/react-image-gallery#functions `getCurrentIndex()`

**Comment by Navipro70** [comment]
Not the best solution, but thank you)
