### ISSUE TITLE
Changing slideInterval prop dinamically

### ISSUE THREAD

**Issue by jpaladin** [xiaolin/react-image-gallery#577]
My use case needs an ability to set duration of the slide different for each i.e.
```
const images = [
    {
      original: "https://picsum.photos/id/1018/1000/600/",
      thumbnail: "https://picsum.photos/id/1018/250/150/",
      duration: 1000
    },
    {
      original: "https://picsum.photos/id/1015/1000/600/",
      thumbnail: "https://picsum.photos/id/1015/250/150/",
      duration: 5000
    }
]
```
So I tried setting the _slideInterval_ prop dynamically in the _onBeforeSlide_ prop callback like this using the _slideInterval_ state variable

```
<ImageGallery
        items={images}
        slideInterval={slideInterval}
        autoPlay={true}
        onBeforeSlide={(nextIndex) => setSlideInterval(images[nextIndex].duration)}
 />
```
This does not apply the newly set slideInterval

**Comment by jpaladin** [comment]
My idea of why this doesn't work is that your components _componentDidUpdate_ does not take into account the _slideInterval_ prop
https://github.com/xiaolin/react-image-gallery/blob/a5201ce0cc1a4ec8bda711a72fbb209228c2a445/src/ImageGallery.js#L267

**Comment by jpaladin** [comment]
My current workaround was to use _ref_ and calling _pause_ and _play_ methods but I think it would be more elegant if it was by design. 

```
      <ImageGallery
        ref={(input) => (this.gallery = input)}
        slideInterval={slideInterval}
        autoPlay={true}
        onBeforeSlide={(nextIndex) => {
          setSlideInterval(images[nextIndex].duration);
          this.gallery.pause();
          this.gallery.play();
        }}
      />
```

**Comment by xiaolin** [comment]
Agreed, It would make sense to handle the interval refresh automatically. In the live example, it is actually doing the same to refresh the `slideInterval` prop https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js#L64

Easy enough to place this logic into the lib.
