### ISSUE TITLE
.exitfullscreen

### ISSUE THREAD

**Issue by Reyyah09** [xiaolin/react-image-gallery#578]
I have been using react ref to implement .exitfullscreen but its not working, it is showing me .exitfullscreen is not a function.

**Comment by kwielicki** [comment]
I also needed to use this method. In my case, it was possible to do it this way: (example with Typescript )
```javascript
import ImageGallery from 'react-image-gallery';
const CustomGallery = () => {
const ImageGalleryRef = useRef<ImageGallery>();
handleCloseGallery = () => ImageGalleryRef?.current?.exitFullScreen();
  return (
    <>
     <ImageGallery  ref={ImageGalleryRef}/>
     <button onClick={handleCloseGallery}>Close</button>
    </>
  )
}
````

**Comment by xiaolin** [comment]
Please see https://reactjs.org/docs/refs-and-the-dom.html
Most common thing I've seen is not calling `current` on your ref e.g. `ref.current.exitFullScreen()`
