### ISSUE TITLE
Include support for imgix data

### ISSUE THREAD

**Issue by jde** [xiaolin/react-image-gallery#579]
Thanks to the whole community for a fantastic image gallery!

Many data cms' these days serve sets of imgixParams for images. These data packets look something like this (taken from datocms):
```
fragment responsiveImageFragment on ResponsiveImage {
  srcSet
  webpSrcSet
  sizes
  src
  width
  height
  aspectRatio
  alt
  title
  bgColor
  base64
}
```
and can be included in React similar to this:
```
import { Image } from "react-datocms"
...
<Image data={data.blogPost.cover.responsiveImage} />
```

Handling images this way can be extremely beneficial, as the data provides tremendous flexibility in how to fit, size, etc... the image. In addition, the base64 encoded field allows images to be built into the page so that all the information is served in a single CDN request. This behavior plays especially well with nextjs style static rendering.

It would be wonderful if react-image-gallery supported this format, or allowed for a way to pass in something like the Image object above instead of just the src urls.

**Comment by xiaolin** [comment]
You can use `renderItem` prop to override how the image is rendered and provide your own params.
