### ISSUE TITLE
Layout shift

### ISSUE THREAD

**Issue by BrTG0D** [xiaolin/react-image-gallery#581]
I put the image gallery inside of a div with this css to center in the center of page:
`
.mainGallery {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}
`

the .tsx file:
`<div className={styles.mainGallery}>
      <ImageGallery
        items={imageUrls}
        ref={ref}
        additionalClass={styles.imageGallery}
        thumbnailPosition="right"
        showFullscreenButton={false}
      />
    </div>`

But after change the image the image 'jumps' from top to center like the gif

**Comment by BrTG0D** [comment]
![ezgif-2-b950d213d1b3](https://user-images.githubusercontent.com/83646796/116999284-c8a13c00-acb5-11eb-991a-94cf7b2af5c1.gif)

**Comment by xiaolin** [comment]
I'm not sure what the issue is here, it looks like a CSS / image aspect ratio type of fix.
