### ISSUE TITLE
Photos are downloaded unnecessarily

### ISSUE THREAD

**Issue by ryanhugh** [xiaolin/react-image-gallery#583]
Looks similar to #580, but I though I'd make a new issue. Basically, every time I hit the next or prev button, it looks like 5 images are downloaded (with lazy load enabled). I'd expect a max of one image to be downloaded, and I don't think images that have already been downloaded should be re-downloaded. 

With lazy load disabled, it looks like every image is being re-downloaded every time I hit next or prev (which makes the page laggy)

![image](https://user-images.githubusercontent.com/5777995/117360125-4196c400-ae6d-11eb-8978-f9489d1aaec9.png)

Would it be possible to improve some of this behavior and eliminate the re-downloading of images? :)

**Comment by ryanhugh** [comment]
Also - looks like this is happening if I use the `render` method to render images or the `original` field.

**Comment by xiaolin** [comment]
I'm unable to reproduce using the [example](https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js) and [demo page](https://www.linxtion.com/demo/react-image-gallery/). 

Can you reproduce the issue using the example provided?

**Comment by xiaolin** [comment]
Try rendering a simple gallery using the code below and see if you can replicate.

```jsx
import ImageGallery from 'react-image-gallery';

const images = [
  {
    original: 'https://picsum.photos/id/1018/1000/600/',
    thumbnail: 'https://picsum.photos/id/1018/250/150/',
  },
  {
    original: 'https://picsum.photos/id/1015/1000/600/',
    thumbnail: 'https://picsum.photos/id/1015/250/150/',
  },
  {
    original: 'https://picsum.photos/id/1019/1000/600/',
    thumbnail: 'https://picsum.photos/id/1019/250/150/',
  },
];

class MyGallery extends React.Component {
  render() {
    return <ImageGallery items={images} />;
  }
}
```

**Comment by ryanhugh** [comment]
I just tried it with the demo site, and I can reproduce it there too - here's a video. 
https://youtu.be/F2ehI-puwSE

I'm using:
Google Chrome Version 90.0.4430.93 (Official Build) (x86_64)
LMK if you want any more info.

**Comment by ryanhugh** [comment]
wow How'd i miss that LOL

Thanks for your help! :)
