### ISSUE TITLE
Add ability to exclude first image from thumbnail list

### ISSUE THREAD

**Issue by EliRobinson** [xiaolin/react-image-gallery#584]
Hello,
It'd be great if you could either pass the index of each thumbnail to the `renderThumbInner` function so we can remove the first image from the thumbnail list, or just offer a boolean to do so.

First would be something like this...
```
// Short pseudo code for brevity
customRenderThumbInner = (thumb, index) => { if (index !== 0) return <Some code/>};
```

Or:
`renderFirstImageInThumbnails: boolean;`

**Comment by xiaolin** [comment]
You can call `getCurrentIndex()` to access the index and implement your custom render.

**Comment by EliRobinson** [comment]
Where can you call `getCurrentIndex`? It's a method on the class itself. How would I call that from a property function?

**Comment by xiaolin** [comment]
See sample code https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js#L73

**Comment by xiaolin** [comment]
I would not be against adding an index to the function. Ideally we also update `renderItem` too. Feel free to open a PR if you like 🙏

**Comment by EliRobinson** [comment]
Also ran into an issue here…

```
        thumbnails.push(
          <button
            key={`thumbnail-${item.original}-${index}`}
            type="button"
            tabIndex="0"
            aria-pressed={currentIndex === index ? 'true' : 'false'}
            aria-label={`Go to Slide ${index + 1}`}
            className={igThumbnailClass}
            onMouseLeave={slideOnThumbnailOver ? this.onThumbnailMouseLeave : null}
            onMouseOver={event => this.handleThumbnailMouseOver(event, index)}
            onFocus={event => this.handleThumbnailMouseOver(event, index)}
            onKeyUp={event => this.handleThumbnailKeyUp(event, index)}
            onClick={event => this.onThumbnailClick(event, index)}
          >
            {handleRenderThumbInner(item)}
          </button>,
        );
```

Cannot hide the button code using merely `handleRenderThumbInner(item)`. Would need to create a const for `handleRenderThumbInner(item)` and not render the button if undefined or null are returned from the output of that function.

**Comment by EliRobinson** [comment]
For short term fix: I added some CSS that removes the first child of the buttons.

**Comment by xiaolin** [comment]
Marking this as resolved, feel free to open PR if the index is useful.
