### ISSUE TITLE
Ability to show nav controls only on hover (or any/all controls)

### ISSUE THREAD

**Issue by EliRobinson** [xiaolin/react-image-gallery#585]
Would be nice to have the ability to show controls only on hover of the main image.

**Comment by xiaolin** [comment]
You can implement that by adding a onhover and using props to show and hide controls.

**Comment by EliRobinson** [comment]
Would you be willing to add something like this? Or take a PR... All it does it makes the controls invisible by default and when you hover over the slide wrapper they mildly slowly fade in. (Can even pass a configurable ease if necessary)

This is what I ended up doing:

```
showControlsOnHover: boolean;

...

.image-gallery-slide-wrapper{
  .image-gallery-icon {
    visibility: hidden;
    opacity: 0;
    transition: visibility 0s linear 250ms, opacity 250ms;
  }

  &:hover {
    .image-gallery-icon {
      visibility: visible;
      opacity: 1;
      transition: visibility 0s linear 250ms, opacity 250ms;
    }
  }
}
```

**Comment by xiaolin** [comment]
Generally, I leave customizations like this up to the user to override instead of adding it to the library which may or may not be wanted by everyone.

**Comment by EliRobinson** [comment]
On mobile, you'd never want to hide those things anyway. I have it not doing that on mobile. Thanks though.
