### ISSUE TITLE
Add local development support for node > 11

### ISSUE THREAD

**Issue by xiaolin** [xiaolin/react-image-gallery#586]

**Comment by pm0u** [comment]
Any movement on this? I am going to have to pass on using this lib due to the rest of the project using a later node version

**Comment by xiaolin** [comment]
Not yet, the node support is mostly for local development. Any reason you need a greater node version to use a React component?

**Comment by pm0u** [comment]
@xiaolin i am getting strange errors, I attributed this to a later node version but it is very difficult for me to understand what the issue is.

I have removed it from my project, but the error was:

````
TypeError (0, _clsx2.default) is not a function
```

along those lines.. it looked like _clsx2.default.default was the default export rather than _clsx2.default - this is in the compiled code. As the compiled code is not in the repository, I assumed this was related to it being built locally using node 14.16.0

**Comment by pm0u** [comment]
I am not able to take the time to re-include this in the project and re-compile, etc --

but on lines 611 - 615 `build/image-gallery`

```
        if (showThumbnails) {
          var igThumbnailClass = (0, _clsx2.default)('image-gallery-thumbnail', thumbnailClass, { active: currentIndex === index });
          thumbnails.push(_react2.default.createElement(
            'button',
            {
```
At this line, _clsx2.default was an object and clsx2.default.default was the default export from `clsx`

**Comment by xiaolin** [comment]
If you're trying to run a local copy of this lib you will get an error with node > 11, but there should be no error when you install this as a dependency for your project. Are you getting an error running a local copy `yarn start`? 

Or are you getting an error trying to use the library in your project after following the [example doc](https://github.com/xiaolin/react-image-gallery#example)

`clsx` supports all version of node and should be unrelated as far as I know.

**Comment by youminkim** [comment]
Hi, I am getting this error 

`
 % npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-image-gallery@1.1.1',
npm WARN EBADENGINE   required: { node: '<12' },
npm WARN EBADENGINE   current: { node: 'v14.15.4', npm: '7.18.1' }
npm WARN EBADENGINE }

up to date, audited 945 packages in 2s

147 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by igordanchenko** [comment]
Same warning here.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-image-gallery@1.1.1',
npm WARN EBADENGINE   required: { node: '<12' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '7.18.1' }
npm WARN EBADENGINE }
```

**Comment by multiwebinc** [comment]
Node 11 has been past its end-of-life since 2019-06-01 (over 2 years ago now), according to https://en.wikipedia.org/wiki/Node.js#Releases.

**Comment by xiaolin** [comment]
Released support for newer version of node using webpack released in
https://github.com/xiaolin/react-image-gallery/releases/tag/v1.2.2
