### ISSUE TITLE
"[Violation] Added non-passive event listener..." possible fix for this package

### ISSUE THREAD

**Issue by Carlo-Defilippis** [xiaolin/react-image-gallery#587]
It looks like the error exists in the react-swipeable package, this issue was fixed by the react-swipeable team as of this update https://github.com/FormidableLabs/react-swipeable/pull/210 , can we upgrade react-swipeeable to get rid of this performance issue please? Thank you for your time and this amazing package!

**Comment by xiaolin** [comment]
should be fixed by #598

**Comment by xiaolin** [comment]
Released https://github.com/xiaolin/react-image-gallery/releases/tag/v1.1.0
