### ISSUE TITLE
Any way to add a custom button?

### ISSUE THREAD

**Issue by softshape** [xiaolin/react-image-gallery#590]
We need to add "delete" button to the gallery. Is there any way to do this without rewrite of the code?

**Comment by xiaolin** [comment]
What are you trying to do with the delete button?

**Comment by softshape** [comment]
It would mark a photo to deletion, and when the gallery is closed, our code sends delete request to a server.

**Comment by xiaolin** [comment]
You can add your own custom button outside the library and implement the logic. You can use `getCurrentIndex()` to get the current index when the button is clicked and mark the appropriate image to delete.
