### ISSUE TITLE
Height and Width not available on build

### ISSUE THREAD

**Issue by lucasengel** [xiaolin/react-image-gallery#592]
`/src/ImageGallery.js` has the width and height properties right but the compiled version from NPM doesn't:

`/src/ImageGallery.js`:
![image](https://user-images.githubusercontent.com/1020229/119541707-bc604a00-bd5c-11eb-9817-90921651cd13.png)

`/build/image-gallery.js`
![image](https://user-images.githubusercontent.com/1020229/119542144-31cc1a80-bd5d-11eb-888a-2792a43a0feb.png)

I'm not familiar with publishing packages. Is this because the build failed on NPM?

**Comment by xiaolin** [comment]
Seems like this has not been released yet, I'll try to get a release out for this later today.

**Comment by lucasengel** [comment]
Spectacular! Thanks, @xiaolin

**Comment by xiaolin** [comment]
Released in v1.0.10 https://github.com/xiaolin/react-image-gallery/releases/tag/v1.0.10
