### ISSUE TITLE
ClassName property for Thumbnail container?

### ISSUE THREAD

**Issue by IrhadOmanovic** [xiaolin/react-image-gallery#593]
Hello, I was wondering if you could add className property for thumbnails container. My use case would be
![image](https://user-images.githubusercontent.com/37186906/119626402-77472100-be0b-11eb-9755-469a1ee46844.png)

So I have this button leserprobe that needs to be always fixed on the right, and thumbnails container should have like 70% max-width. But there is a case when this button is not present, so i would like to have that thumbnails container at full width. I would be grateful if you could add classname property for tuhumbnails container.

Also, I did try with that custom renderThumbInner, but problem is my custom rendered button would not be fixed on the right.

**Comment by xiaolin** [comment]
You should be able to target the thumbnail container by wrapping a custom class around your gallery.

e.g.
```jsx
<div className={shouldHideButton ? "withoutButton" : ""}>
  <ImageGallery />
</div>
```

```css
.withoutButton .image-gallery-thumbnail-inner {
 // your styles
}
```

**Comment by IrhadOmanovic** [comment]
Thanks for feedback. I will give it a go.
