### ISSUE TITLE
Fix upstream dependency conflict with react 17

### ISSUE THREAD

**Issue by arabah** [xiaolin/react-image-gallery#594]
I am unable to install this package in a project with `react@^17.0.0` as I get the following error message:

```
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-image-gallery@1.0.7
npm ERR! node_modules/react-image-gallery
npm ERR!   react-image-gallery@"1.0.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

It appears the solution is to update this project to the latest version of ReactJS.

**Comment by xiaolin** [comment]
This project should be compatible with the latest react. I tested this yesterday by updating to the latest react and running it locally.

**Comment by arabah** [comment]
My bad, false alarm. I'm no longer able to reproduce it after removing and adding some other packages.
