### ISSUE TITLE
Thumbnails should have their own width and height

### ISSUE THREAD

**Issue by lucasengel** [xiaolin/react-image-gallery#595]
The same way we have `alt` and `src` for thumbnails, there should be an option to pass `width` and `height` too. This affect Layout Shifting (CLS) as the HTML renders much bigger images until the CSS kicks in.

**Comment by xiaolin** [comment]
Should be easy enough to add, feel free to open PR.

**Comment by xiaolin** [comment]
Needs release with a breaking change note.

**Comment by xiaolin** [comment]
released https://github.com/xiaolin/react-image-gallery/releases/tag/v1.1.0
