### ISSUE TITLE
Only YouTube video supported or any other video support in this component?

### ISSUE THREAD

**Issue by urjit0204** [xiaolin/react-image-gallery#600]
First of all, this is a very good component.

I have my own videos and images that come from AWS s3. 

I want to upload AWS s3 videos in the gallery from my DB. So your component will work in this scenario? @xiaolin

**Comment by xiaolin** [comment]
Hey, the gallery does not natively support any videos. See the example.js to see how the youtube video is rendered. You can fo the same using the customRender prop.

**Comment by urjit0204** [comment]
Thank you
