### ISSUE TITLE
Custom actions are working or not?

### ISSUE THREAD

**Issue by urjit0204** [xiaolin/react-image-gallery#602]
I want to perform some actions on my image gallery like image rotations, image forward to chat system, etc. I developed those actions but is there any way to put that actions in your gallery? I share some images here so you can understand my point easily.

![img1](https://user-images.githubusercontent.com/68319672/121495672-714e6400-c9f7-11eb-9094-1fac9f328161.png)
![img2](https://user-images.githubusercontent.com/68319672/121495663-6f84a080-c9f7-11eb-9cb5-cad6aeb69883.png)

Also, I need these options only for images. Not for videos.

In the above images, I used static gallery but is there any way to use this kind of 3 dot option in your image-gallery? 
Please help me over here. @xiaolin

**Comment by urjit0204** [comment]
Please help me over here @xiaolin

**Comment by xiaolin** [comment]
You can implement your own three dot button and place it inside the gallery.
```
<div>
   <MyThreeDotButton /> // use css to place it in the corner.
   <ImageGallery />
</div>
```

**Comment by urjit0204** [comment]
Got it :+1:  Thank you.
