### ISSUE TITLE
Video automatically run on component load

### ISSUE THREAD

**Issue by urjit0204** [xiaolin/react-image-gallery#604]
Hi @xiaolin, 

This is some weird issue that happened when the component loads the video in the gallery automatically plays. 

I used renderItem props for the video but it will automatically play the video on component load. So how can I stop autoplay video on the gallery?

Need some help.

Thank you in advance.

**Comment by xiaolin** [comment]
Please use google for questions outside of the gallery.

**Comment by urjit0204** [comment]
But this is a gallery related issue.

**Comment by xiaolin** [comment]
The gallery does not have built in support for videos. If you're using `renderItems` you're customizing the built in render method. If there is something in the component causing this you can open an issue explaining what section/line of code is causing this, but videos automatically playing should not be caused by the component.

**Comment by urjit0204** [comment]
Yes, I understand your point, and I also got the solution. 

Thank you for your support @xiaolin.

**Comment by SatyamKr07** [comment]
@urjit0204 can you tell which plugin are you using for playing video as I also want to have video in my carousel.

**Comment by urjit0204** [comment]
> @urjit0204 can you tell which plugin are you using for playing video as I also want to have video in my carousel.
@SatyamKr07 
If you want to play a video then use renderItem prop and pass the function for video.
renderItem prop is for original video and renderThumbInner prop for thumbnail
ex.

```
{
   original: "https://videoUrl.mp4", // url
   renderItem: this.renderVideoFunction.bind(this),
   renderThumbInner: this.renderThumbnailForVideoFunction.bind(this)
}
```

And at the function side.
```
videoThumbInner = (videoItem) => {
    return (
      <video width="100%" >
        <source src={videoItem.original} type="video/mp4" />
      </video>
    )
  }

  renderVideo = (item) => {
    return (
      <div>
        {
          item.original ?
            <video ref={(ref)=>this.input[item.index]= ref} autoPlay={false} width="100%" controls >
              <source src={item.original} />
            </video>
            :
            null
        }
      </div>
    );
  }
```

I hope this would be helpful :)
