### ISSUE TITLE
Docs are stale?

### ISSUE THREAD

**Issue by wle8300** [xiaolin/react-image-gallery#606]
Hi there! Love this component. It's got the perfect balance of features, and customizability.

Are the docs out-of-sync with the latest release? Seems like there's a few things (like the `embedUrl` field) aren't mentioned in the docs.

**Comment by xiaolin** [comment]
The library supports custom renders using `renderItem`, the `embedUrl` you see in the example is an example of what you can do if you wanted to render a video in your gallery.

**Comment by wle8300** [comment]
Ohhh I understand. Thx for the quick response :P
