### ISSUE TITLE
Having issue when using in next.js

### ISSUE THREAD

**Issue by saeed-jalilian** [xiaolin/react-image-gallery#607]
hi, i wrote the code below and when i try to run the server, it says : 
`./node_modules/react-image-gallery/src/ImageGallery.js
Module parse failed: Unexpected token (169:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     swipeThreshold: 30,
|     renderLeftNav: (onClick, disabled) => (
>       <button
|         type="button"
|         className="image-gallery-icon image-gallery-left-nav"
`

and the code i wrote is : 

`
const images = [
      {
         original: '/img/some-image.jpg',
         thumbnail: '/img/some-image.jpg'
      },
      {
         original: '/img/some-image.jpg',
         thumbnail: '/img/some-image.jpg'
      }]

const settings = {
      showPlayButton: false,
      isRTL: true,
      showIndex: true,
   }

const SomePage = () => {
return(<ImageGallery {...settings} items={images}/>)}
`
i've did all the imports correctly, so can anyone please help me solve this problem?

**Comment by akramaskar** [comment]
Up! 

How did you solve this issue?
