### ISSUE TITLE
Thumb is selected even if we override renderThumbInner

### ISSUE THREAD

**Issue by ziedHamdi** [xiaolin/react-image-gallery#611]
**Describe the bug**
I have an image gallery where I can remove(and restore) previously added images.

**To Reproduce**
Overriding renderThumbInner makes thumbs select onClick anyway (handled in an outside div)

```
    function _onRemoveAction(item, remove) {
        const {onRemoveAction} = props
        return (e) => {
            e.preventDefault()
            e.stopPropagation()

            onRemoveAction(item._id, remove)
        }
    }
```

**Expected behavior**
We should be able to avoid the thumb selection by calling preventDefault on the event (seems to be too late)

**Screenshots**
Here you can see two thumbnails selected at the same time
![image](https://user-images.githubusercontent.com/7271508/124354505-3a3d2e00-dc04-11eb-86c2-1a2b82336b9b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome

**Additional context**
```
    function renderThumbInner(item) {
        const attachmentAttributes = attachments.attachmentsAttributes[item._id]
        const deleted = attachmentAttributes?.deleted
        // logger.debug("rendering item: ", JSON.stringify(item), " attr: ", JSON.stringify( attachmentAttributes))
        return (
            <span className="image-gallery-thumbnail-inner">
                <img
                    className="image-gallery-thumbnail-image"
                    src={item.thumbnail}
                    height={item.thumbnailHeight}
                    width={item.thumbnailWidth}
                    alt={item.thumbnailAlt}
                    title={item.thumbnailTitle}
                />
                {!deleted && <RemoveCircleIcon className={classes.delete} onClick={_onRemoveAction(item, true)}/>}
                {deleted && <RestoreFromTrashIcon className={classes.restore} onClick={_onRemoveAction(item, false)}/>}
                {deleted && <div className={classes.deltedLayer}/>}
                {
                    item.thumbnailLabel && (
                        <div className="image-gallery-thumbnail-label">
                            {item.thumbnailLabel}
                        </div>
                    )
                }
            </span>
        );
    }

```

**Comment by xiaolin** [comment]
The selection is done via CSS on the current active index. Take a look at the CSS that handles focus on thumbnails, you should be able to remove the class when the thumbnail is "removed" which would not highlight the deleted thumbnail.

https://github.com/xiaolin/react-image-gallery/blob/master/styles/scss/image-gallery.scss#L392

```css
.image-gallery-thumbnail:focus {}
```

**Comment by ziedHamdi** [comment]
Thanks for answering this fast Xiaolin, my need is more about controlling whether the thumb gains focus or not, since when a user clicks on the "remove" or "undelete" icon, I don't want the thumb to receive focus at all. So I need to get the control at the very moment a thumb is clicked instead of analyzing the situation afterward to check if it is actually a "true or a false" focus.
Maybe the lib was not designed this way, and this ticket should be classified as an enhancement request. 
I love the lib otherwise, it saved me a lot of development time :-)

**Comment by ziedHamdi** [comment]
Great!

Didn't think about catching the event on the icon directly. Thanks for the time you took for me Xiaolin :-)
