### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by mustafa-hanif** [xiaolin/react-image-gallery#613]
**Describe the bug**
I believe the latest release broke something, just include image-gallery in a nextJS project to see this bug

#16 190.4 ReferenceError: self is not defined
#16 190.4     at Object.<anonymous> (/app/node_modules/react-image-gallery/build/image-gallery.js:1:252)
#16 190.4     at Module._compile (internal/modules/cjs/loader.js:1085:14)
#16 190.4     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
#16 190.4     at Module.load (internal/modules/cjs/loader.js:950:32)
#16 190.4     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
#16 190.4     at Module.require (internal/modules/cjs/loader.js:974:19)
#16 190.4     at require (internal/modules/cjs/helpers.js:92:18)
#16 190.4     at Object.2582 (/app/.next/server/pages/hotels.js:188:52)
#16 190.4     at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)

**To Reproduce**
just include image-gallery in a nextJS project to see this bug

**Desktop (please complete the following information):**
 - OS: MacOS, building NextJS through docker.
 - NodeJS version 14

**Comment by ihsanbudiman** [comment]
i have same problem here, self is not defined

**Comment by ihsanbudiman** [comment]
hello @mustafa-hanif try import style its works for me

**Comment by fsoubes** [comment]
Hello,
I have the same issue

**Comment by adamdrake210** [comment]
I also just updated to v 1.2.2 and using nextJs. It was working fine before and now getting same error as above.

**Comment by xiaolin** [comment]
Looks like a build issue for users who use nextJS, will release a new build today which should fix this.

**Comment by xiaolin** [comment]
@mustafa-hanif Just released a new build on `1.2.4` which should fix the issue.

**Comment by rajanvalencia** [comment]
> @mustafa-hanif Just released a new build on `1.2.4` which should fix the issue.

Thank you for the quick  fix

**Comment by xiaolin** [comment]
Marking this as fixed. Feel free to re-open otherwise.

**Comment by mustafa-hanif** [comment]
@xiaolin sorry for late reply, yes this indeed fixes it.
