### ISSUE TITLE
Next button and maximize buttons overlap if image very short

### ISSUE THREAD

**Issue by vuki656** [xiaolin/react-image-gallery#614]
**Describe the bug**
When there is an image that is very short, maximize and the next image button will overlap.

**Expected behavior**
For the buttons to not overlap. Possibly for the gallery to have a min-height so this doesn't happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/8104698/125423500-4578fd19-50d4-4b5b-a4d6-34931fbea60d.png)

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser: Chrome Version 91.0.4472.114 (Official Build) (64-bit)
 - Version: 1.2.4

**Comment by xiaolin** [comment]
The gallery does not know about image height or width. I'm leaving this up to you to modify via CSS. You can add a min-height or render your own slide via `renderItem` prop.
