### ISSUE TITLE
Thumbnails swipe gesture issue

### ISSUE THREAD

**Issue by SatyamKr07** [xiaolin/react-image-gallery#617]
Describe the bug
When we touch any thumbnail that is below the carousel, the thumbnail moves a bit horizontally even when scrolling up or down in mobile device.

To Reproduce

Go to https://www.linxtion.com/demo/react-image-gallery/
Touch any thumbnail in carousel
Scroll down or up
See the horizontal movement of thumbnails in the carousel.
Expected behavior
The thumbnail in the carousel should not move when scrolling up or down as it leads to bad user experience.

Smartphone (please complete the following information):

Device: Realme 2 pro
OS: Android 10
Browser : chrome

**Comment by xiaolin** [comment]
Released in version 1.2.7
