### ISSUE TITLE
Image Swiping using mouse events

### ISSUE THREAD

**Issue by YashCerebulb** [xiaolin/react-image-gallery#620]
I'm always feel uncomfortable when I am swiping using the key down.
So,
Solution is that we can swipe images when user rotate mouse wheel on thumbnail area.

please consider my request and reply me if it is possible to add feature.
or if it is not possible than give me some other idea that how I can modify swiping feature

**Comment by xiaolin** [comment]
You can use `getCurrentIndex` and `slideToIndex(index)` to implement your mouse wheel requirement.

**Comment by YashCerebulb** [comment]
Thanks For Your reply,
it helped me to implement this requirement.

but the Issue is speed of sliding.
can you give me solution for speed up image sliding ?

My code is below:

```
const ImageView = (props) => {

    const refImg = useRef(null)
    
    const handleScrollEvent = (e) => {
        console.log(e)
        if(e.deltaY < 0){
            refImg.current.slideToIndex(refImg.current.getCurrentIndex() + 1)
        }else{
            refImg.current.slideToIndex(refImg.current.getCurrentIndex() - 1)
        }
    }

    useEffect(() => {
        let el = document.querySelector(".image-gallery-thumbnails-container")
        if(el){
            document.querySelector(".image-gallery-thumbnails-container").addEventListener("wheel", (e) => handleScrollEvent(e));
        }
    }, [props.Images])


    return (
        <ImageGallery
            ref={refImg}
            items={props.Images} 
            showNav={false} 
            showPlayButton={false}
            startIndex={props.Images.length-1}
            lazyLoad={true}
        />
    )
}
```

**Comment by xiaolin** [comment]
See doc for `slideDuration`. That modifies the speed of the slide.

**Comment by YashCerebulb** [comment]
Thank You @xiaolin Issue is Solved.
