### ISSUE TITLE
Error in production build

### ISSUE THREAD

**Issue by carlobambo** [xiaolin/react-image-gallery#621]
**Describe the bug**
I'm receiving this error when I use this on a production build using Webpack 4.
`Super expression must either be null or a function`

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2021-08-10 at 17 22 52](https://user-images.githubusercontent.com/11373340/128842589-26c70747-671e-4dfe-85cb-798ea977a13f.png)
![Screen Shot 2021-08-10 at 17 22 46](https://user-images.githubusercontent.com/11373340/128842618-606ed651-1518-40c5-9c7c-b45c186a3d17.png)

**Additional context**
I'm using Webpack 4 with react and react-dom 16.

**Comment by xiaolin** [comment]
Closing this in favor of #624, please see thread there.
