### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'React'

### ISSUE THREAD

**Issue by jacksontrieu** [xiaolin/react-image-gallery#622]
**Describe the bug**
When compiling an app that imports `react-image-gallery` with [webpacker](https://github.com/rails/webpacker), we're getting the following error:

> ModuleNotFoundError: Module not found: Error: Can't resolve 'React' in '/tmp/build_c250ab12/node_modules/react-image-gallery/build'

In our Heroku deployment the error shows up as:

> ERROR in ./node_modules/react-image-gallery/build/image-gallery.js Module not found: Error: [CaseSensitivePathsPlugin] `path-to-app/node_modules/React/index.js` does not match the corresponding path on disk `react`

This error seems to be happening because the built `build/image-gallery.js` file contains the following line which references `React` rather than `react`:

`define.amd?define(["React"],t)`

This is because [webpack.build.js](https://github.com/xiaolin/react-image-gallery/blob/master/webpack.build.js#L39) has an `jsOutput.externals.amd` value of `React` (with a capital "R"), rather than `react`.

To confirm this, I've cloned this repo, changed the `jsOutput.externals.amd` value to `react` Building the clone repo with `yarn build` will then output a `build/image-gallery.js` with the correct amd definition and fixes the issue in webpacker:

`define.amd?define(["react"],t)`

Reverting it back to `React` causes the issue to happen again.

**To Reproduce**

1. Create a rails app that uses `webpacker` and `react_on_rails`
2. Create a react component that imports `react-image-gallery`
3. Reference that react component in `app/javascript/packs/application.js`
4. Run `bundle exec rails webpacker:compile`
5. An error will occur when webpacker tries to compile the application's js pack

**Comment by xiaolin** [comment]
Hi, thanks for reporting, this should be fixed in v1.2.7
