### ISSUE TITLE
Possibly issue with minify

### ISSUE THREAD

**Issue by mister-t-69** [xiaolin/react-image-gallery#626]
First of all apologies if this is the wrong place - I've been developing winforms apps for a few decades but I'm new to ASP.Net Core MVC and React.  Anyway, I've been developing an app for the last few weeks and have made reasonable progress.  I have data coming from Azure Tables displaying in tables, and images displaying in this gallery component.

I'm using VS2019 and ASP.Net Core 2.1

Yesterday I tried to publish the app to two different hosts and it won't build.  I spent close to five hours trying different things but I always get this error:

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/react-image-gallery/build/image-gallery.js:1:269 

I tried three different versions of react-scripts including the very latest.  I updated everything I could.  But the error never changed.  here is my package.json file:

{
  "name": "remoteeye",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "ajv": "^6.12.6",
    "bootstrap": "^3.4.1",
    "react": "^16.14.0",
    "react-bootstrap": "^0.31.5",
    "react-datepicker": "^4.2.0",
    "react-dom": "^16.14.0",
    "react-image-gallery": "^1.2.7",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^4.0.3",
    "rimraf": "^2.7.1"
  },
  "scripts": {
    "start": "rimraf ./build && react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

I've given up for now and am starting from scratch, but I thought I'd at least put it up here.  Just in case it is a real issue or someone knows how to solve.

**Comment by xiaolin** [comment]
Not sure if this will help, but looks like an issue others may have faced 
https://stackoverflow.com/questions/45671597/failed-to-minify-the-code-from-this-file

**Comment by mister-t-69** [comment]
Hi xiaolin,

Thanks for your response.  

I did come across that post and tried to follow it.  Unfortunately I didn't really understand how they were doing what they suggest.  I found webpack.config.prod.js and I found the relevant entry:

    // Minify the code.
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        // Disabled because of an issue with Uglify breaking seemingly valid code:
        // https://github.com/facebookincubator/create-react-app/issues/2376
        // Pending further investigation:
        // https://github.com/mishoo/UglifyJS2/issues/2011
        comparisons: false,
      },
      mangle: {
        safari10: true,
      },        
      output: {
        comments: false,
        // Turned on because emoji and regex is not minified properly using default
        // https://github.com/facebookincubator/create-react-app/issues/2488
        ascii_only: true,
      },
      sourceMap: shouldUseSourceMap,
    }),

But I have no idea how to change it to use "terser-webpack-plugin-legacy" or how I add that plugin in the first place.

Sorry, this is all very new to me :-)

**Comment by xiaolin** [comment]
closing this as its probably stale, feel free to reopen if you are still experiencing issues.
