### ISSUE TITLE
Support additional props on <img> without having to provide a custom renderItem

### ISSUE THREAD

**Issue by TimNZ** [xiaolin/react-image-gallery#628]
**Is your feature request related to a problem? Please describe.**
I need to set 'cross-origin' on the &lt;img&gt;

**Describe the solution you'd like**
Explicit crossOrigin prop on gallery/item props, or 'customImgProps' that is spread on the &lt;img&gt;?

**Describe alternatives you've considered**
Custom renderItem, but a lot for a single prop.

**Comment by xiaolin** [comment]
closing in favor of using `renderItem`
