### ISSUE TITLE
How can I modify the full screen height?

### ISSUE THREAD

**Issue by mmgh900** [xiaolin/react-image-gallery#629]
I'm using the fullscreen mode with `useBrowserFullscreen={false}`. I have a navbar that I want to be visible in the fullscreen mode and I want the gallery to appear below that. I used this style to modify the height but It doesn't work cause the inner element has a larger height.
`
.image-gallery.fullscreen-modal {
  top: 60px !important;
  height: calc(100vh - 60px);
}
`
What other styles should I change in order for this to work?

**Comment by artstylee** [comment]
same issue. cant customize styles. module styles overwrites my styles. want to remove width: 100%

**Comment by artstylee** [comment]
i fixed it with 

> .image-gallery-image {
>   width: auto !important
> }
but this is very bad solution. i would like  to have ability to change built-in css

**Comment by xiaolin** [comment]
Please use the issues template to report issues. For CSS related question, please use google.

@artstylee 
You can override the built in css by being [more specific](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) or making sure your [css loads after](https://stackoverflow.com/questions/31028579/how-to-import-styles-in-the-right-order-in-webpack) the image gallery css.


e.g.
import gallery.css
import myApp.css

or
```
.my-app .image-gallery-image {
  width: auto;
}
```
