### ISSUE TITLE
Adding the callback function in component 

### ISSUE THREAD

**Issue by YashCerebulb** [xiaolin/react-image-gallery#638]
Hi,

I am using the react image galley for my application and I want to customize some of the features like I want to add feature which can scroll the image based on wheel rotation.
so,
I am using the loader for showing the loading if the image gallery is not shown at that time I am using useEffect for adding my custom function in the application. so at the time useEffect is executed the my function is unable to find the image gallery components because of the loader in the document.

so we can add one callback function which will be executed if the image gallery is successfully rendered on the dom.

my code is below.

`
const ImageView = (props) => {

    const { promiseInProgress } = usePromiseTracker();
    const refImg = useRef(null)

    const handleScrollEvent = (e) => {

        if (e.deltaY < 0) {
            refImg.current.slideToIndex(refImg.current.getCurrentIndex() + 1)
        } else {
            refImg.current.slideToIndex(refImg.current.getCurrentIndex() - 1)
        }
    }

    useEffect(() => {
        console.log(refImg)
        let el = document.querySelector(".image-gallery-thumbnails-container")
        if (el) {
            document.querySelector(".image-gallery-thumbnails-container").addEventListener("wheel", (e) => handleScrollEvent(e));
        }
    }, [props.Images])

    return (
        <>
            {!promiseInProgress ?
                <ImageGallery
                    ref={refImg}
                    items={props.Images}
                    showNav={false}
                    showPlayButton={false}
                    startIndex={props.Images.length - 1}
                    lazyLoad={true}
                    slideDuration={0}
                    showFullscreenButton={false}
                /> :
                <LoadingIndicator />
            }
        </>
    )
}

export default ImageView;
`

**Comment by xiaolin** [comment]
you should be able to use refs to check if image gallery was loaded.
