### ISSUE TITLE
Slides to show in thumbnail slider and show current slide at top

### ISSUE THREAD

**Issue by abhverma10** [xiaolin/react-image-gallery#639]
**Is your feature request related to a problem? Please describe.**
I am trying to implement the slider on the PDP, but the thumbnail slider shows half images when slided and also there is no props for limiting the number of slides to be shown in the thumbnail.

**Describe the solution you'd like**
I would like that if when I slide, the whole thumbnail should slide to the top and only a limited(decided by us) thumbnails are visible to us.

**Describe alternatives you've considered**

**Additional context**

**Comment by xiaolin** [comment]
There are only a limited amount of thumbnails visible. If you want less thumbnails visible you can adjust the container size of the thumbnail via css.
