### ISSUE TITLE
slideInterval prop doesn't work when used with slideDuration

### ISSUE THREAD

**Issue by chetrit** [xiaolin/react-image-gallery#640]
**Describe the bug**
slideInterval prop doesn't work when used with slideDuration (only tested on web because not interested in mobile vers)

**Image Gallery Version**
^1.2.7

**To Reproduce**
```js
      <ImageGallery
        items={images}
        autoPlay={true}
        slideInterval={5000} slideDuration={3000}
      />
```
If you want an image that stays for 5 seconds and that takes 3 seconds to slide with autoplay.
Then doing this will only work for the first image, and all the remainings will only stay for 3 seconds (the slideDuration prop's value). Refreshing will do the same behaviour (first img stay 5 secs, slide is always 3 secs, and all remaining images (even the first one) will only stay 3 secs). 

**Expected behavior**
A slideshow with images that stays for 5 seconds and that takes 3 seconds to slide with autoplay.

**Desktop (please complete the following information):**
 Ubuntu  20.04.3 LTS
 Chrome Version 93.0.4577.63 (Official Build) (64-bit)

**Additional context**
 I tried every kind of variations, inverting slideInterval and slideDuration values, but nothing would work. This was the closest solution I found. Though, when putting slideInterval to 3000 and slideDuration to 5000, everything takes 5 secs (both slideInterval and slideDuration), which is also a problem.
 
 The problem is probably linked with a prop that is first set well, and then reseted to the default value, or somewhere slideDuration is used instead of slideInterval ...

**Comment by xiaolin** [comment]
This is happening because `slideInterval` continues to count while the transition is happening. 
If you want the image to stay for 5 seconds and taking 3 seconds to slide, try using

`slideInterval={8000} slideDuration={3000}`
