### ISSUE TITLE
Image gallery component not respecting height of parent

### ISSUE THREAD

**Issue by povilasDadelo** [xiaolin/react-image-gallery#641]
**Describe the bug**
ImageGallery component is not respecting height of parent div.

**Image Gallery Version**
Latest version

**To Reproduce**
1. Create div max-height 500px width 100% of container.
2. Image is out of parent bounds

**Expected behavior**
I would expect this component to stay inside parent.
Adding custom CSS to this library is a headache.

**Comment by SVallant** [comment]
try changing the width of the parent, this works

**Comment by Novizh** [comment]
Experiencing the same problem here, any workarounds?

**Comment by ignacio-dev** [comment]
Same issue here
