### ISSUE TITLE
How to load local images

### ISSUE THREAD

**Issue by bob-nem** [xiaolin/react-image-gallery#642]
I cant't understand how i can load local images to this gallery. In this project is possible to load only linked images?
Example:
  const images = [
          {
            original: 'https://picsum.photos/id/1018/1000/600/',
            thumbnail: 'https://picsum.photos/id/1018/250/150/',
            
          },
  ]
If I try to write the path instead of 'https' local path via src={example image}, it will result in an error

**Comment by multilabCole** [comment]
Hi Bob-nem,

Use it like this in order to load local images
`
import example from '../example'

const images = [
  original: example.src,
  thumbnail: example.src
]
`

hope that helps!

**Comment by yassinemaalejchtr** [comment]
Can you explain how to use local images with the example in app.js, please ?

**Comment by bob-nem** [comment]
> Hi Bob-nem,
> 
> Use it like this in order to load local images
> 
> import example from '../example'
> 
> const images = [ original: example.src, thumbnail: example.src ]
> 
> hope that helps!

no this not work too maybe it's because i'm use nextjs framework? here example of code:

import Image from 'next/image'
import style from '../../styles/Gallery.module.css';
import ImageGallery from "react-image-gallery";
import "react-image-gallery/styles/css/image-gallery.css";

import example from '../../images/our-works'

export default function Gallery() {
    const images = [
        {
            original: firstIMG.src,
            thumbnail: firstIMG.src
        },
    ];

    return (
        <div className={style.Container} id="gallery">       
        <ImageGallery
            items={images}
            showBullets={true}
            showIndex={true}
            showThumbnails={true}
            lazyLoad={true}
            showPlayButton={false}
        />
        </div>
    )
}

**Comment by bob-nem** [comment]
this approach not work too
```
import Image from 'next/image'
import style from '../../styles/Gallery.module.css';
import ImageGallery from "react-image-gallery";
import "react-image-gallery/styles/css/image-gallery.css";

import example from '../../images/our-works/1.webp'

export default function Gallery() {
    const images = [
        {
            original: [function() {return<div><Image src={example}/></div>}],
            thumbnail: [function() {return<div><Image src={example}/></div>}],
        },
    ];

    return (
        <div className={style.Container} id="gallery">
            <h2 className={style.Header}>Gallery</h2>
            <p className={style.Description}>here you can see before and after results of our work</p>
        <ImageGallery
            items={images}
            showBullets={true}
            showIndex={true}
            showThumbnails={true}
            lazyLoad={true}
            showPlayButton={false}
        />
        </div>
    )
}
```

**Comment by xiaolin** [comment]
closing as its unrelated to lib and adjusted via your local setup.

**Comment by Umair-Kiani** [comment]
Thanks guys.. This actually works.

Use it like this in order to load local images

import example from '../example'

const images = [ original: example.src, thumbnail: example.src ]

**Comment by kevinrkowalski** [comment]
this thread runs in circles, did anyone actually figure out how to get this to work with local images? Seems like docs should mention this...

**Comment by kevinrkowalski** [comment]
I'm using NextJS. I'm importing the image as normal and passing it exactly as shown in the docs and how others have mentioned above and it doesn't work. Does this work with NextJS and local images?

**Comment by xiaolin** [comment]
When you inspect the page that renders the gallery, what is the `src` for the `<image src=?` tag rendered?

It may be a wrong path to your local images that is served by NextJS.
