### ISSUE TITLE
Allow custom aria-role for slides, instead of forcing all slides to have role "button"

### ISSUE THREAD

**Issue by dbridenbeck** [xiaolin/react-image-gallery#645]
**Is your feature request related to a problem? Please describe.**
If you are using `renderItem()` to render your items, and the JSX returned by `renderItem()` has focusable elements (buttons, links , etc.), you'll get an accessibility warning when running an accessibility audit with [axe devTools](https://www.deque.com/axe/devtools/) that "Interactive Controls must not be nested".

![Screen Shot 2022-01-06 at 7 56 34 AM](https://user-images.githubusercontent.com/49624436/148411416-4a59fcf4-6bf9-490b-9802-4cb52faa99e0.png)

**Describe the solution you'd like**
Currently slides are hard coded to have the role "button" (see source code [here](https://github.com/xiaolin/react-image-gallery/blob/69d70175dde5df39710e8d8d8695161f5190398e/src/ImageGallery.js#L520)). I'd like to be able to pass a `slideRole` prop into the `ImageGallery` component that could override the hardcoded value.

**Describe alternatives you've considered**
We could get more opinionated if we'd like - for example we could traverse the DOM on the return of renderItem to see if there's focusable elements within it and then set it to "group" if there are focusable items, and "button" if not . . . but that feels like overkill.

**Additional context**
I've created a branch locally and am ready to push up a fix for this, but I'm getting a 403 when I try to push. Do you need to give me access to this repo first?

Also, THANKS for making this library! We're using this on https://www.driveway.com/ in a few different places :)

**Comment by xiaolin** [comment]
Happy to support this if you open a PR. You don't have access to directly push to this repo.
