### ISSUE TITLE
How do I style the nav buttons?

### ISSUE THREAD

**Issue by davidc360** [xiaolin/react-image-gallery#646]
![Screen Shot 2022-01-11 at 12 59 01 AM](https://user-images.githubusercontent.com/43507686/148889398-512b63f9-7378-49f3-a296-7d66d24d8ac1.png)

Currently the nav button are huge on my component. I was wondering how i can change the size of it. Thanks in advance.

**Comment by mattdell** [comment]
Either use CSS or use the `renderLeftNav` and `renderRightNav` properties.

Example code from my project

```
renderLeftNav={(leftNavOnClick) => (
  <ArrowButton
    direction="left"
    onClick={leftNavOnClick}
    className={navButtonClassnames}
  />
)}
```
