### ISSUE TITLE
On build, width and height are 0

### ISSUE THREAD

**Issue by MelanieCroce** [xiaolin/react-image-gallery#648]
**Describe the bug**
I'm on nextjs, when I'm in production, width and height is 0, whether or not I specify the value in items. In my case I don't have the value of width and height, I would like it not to be filled in at all. In dev, I have no problem.

**Image Gallery Version**
^1.2.7

**To Reproduce**
I built my item array like this:```
temp.push({
                original: photo.contentUrl,
                thumbnail: photo.contentUrl,
                originalClass: Styles.itemCarousel,
                thumbnailClass: Styles.itemPagination, 
                width: "100%",
                height: "100%",
                originalAlt: "Images"
            })
```

```
 <ImageGallery 
                        items={images} 
                        useBrowserFullscreen={false}
                        renderLeftNav={(onClick, disabled) => {
                            return (
                            <button 
                                className={Styles.arrow + " " +Styles.arrowLeft + " "+ (disabled && Styles.isDisabled)} 
                                onClick={onClick}
                            >
                                <span className="material-icons-outlined">chevron_left</span>
                            </button>
                        )}}
                        renderRightNav={(onClick, disabled) => (
                            <button 
                                className={Styles.arrow + " " +Styles.arrowRight + " "+ (disabled && Styles.isDisabled)} 
                                onClick={onClick}
                            >
                                <span className="material-icons-outlined">chevron_right</span>
                            </button>                       
                        )}
                    />
```
**Expected behavior**
`<img class="image-gallery-image" src="....." alt="Images" srcset="" sizes="" title="">`
instead of 
`<img class="image-gallery-image" src="....." alt="Images" width="0" height="0" srcset="" sizes="" title="">`


**Desktop (please complete the following information):**
 - OS: IOS
 - Browser : Chrome
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by Fer96carvalho** [comment]
width and height in px, not %.
