### ISSUE TITLE
Global classes named `left` or `right` overwrite react-image-gallery classes

### ISSUE THREAD

**Issue by mariokandut** [xiaolin/react-image-gallery#651]
**Describe the bug**
Global classes named `left` or `right` overwrite react-image-gallery classes

**Image Gallery Version**
1.2.7

**To Reproduce**
Create a in your global css file a class named `left` or `right` and assign it for example `width: 50%`

**Expected behavior**
react-image-gallery should use custom classNames

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser:  chrome

**Comment by ethananselkelly** [comment]
Hi, I'd like to try working on this issue but could use some clarification. Where are the left and right classes that need to be renamed?

**Comment by xiaolin** [comment]
They are in https://github.com/xiaolin/react-image-gallery/blob/master/styles/scss/image-gallery.scss.

The `left` and `right` classnames are not specific enough so making it more specific should fix the issue.

**Comment by Luo-Yihang** [comment]
@xiaolin Hi! I have fixed this issue in #692, could you please check on that?
