### ISSUE TITLE
I am not able to drag thumbnails using mouse

### ISSUE THREAD

**Issue by Nagavijay-beachbody** [xiaolin/react-image-gallery#652]
Please help,

I am using this library to implement carousel and I am trying to Drag thumbnails to left or right but it is disabled.

If anyone have solution for it please let me know.

Thanks in Advance!!!

**Comment by xiaolin** [comment]
Drag events are not enabled for desktop. Swipe and Drags are only on mobile devices. You can also test it using the chrome simulator.
