### ISSUE TITLE
images slide above each other

### ISSUE THREAD

**Issue by mosheraD** [xiaolin/react-image-gallery#655]
**Describe the bug**

**Image Gallery Version**
What version of `react-image-gallery` are you using?
1.2.7

if you have only two or three images.. try to navigate between them by nav buttons . then navigate using thumbnail .. click twowice on the same thumbnail .. you will show a strange behavior 

**To Reproduce**
1.make sure you have only two images.
2.try to navigate between them by nav buttons.
3. then navigate using thumbnail.
4. click twice on the same thumbnail.
5. you will see unexpected behavior.

**Expected behavior**
images not slide above each other.

**Desktop (please complete the following information):**
 - OS: [10.15.7 iOS] 
 - Browser [chrome, safari]

**Comment by entanglesoftware** [comment]
It is happening for the case of 2 images. 👍 Strangely, nobody has reported since ages. lol 
I will try to fix it and generate a pull request.

**Comment by umamahesswari** [comment]
This issue still persists? Any updates ??

**Comment by xiaolin** [comment]
Fixed in https://github.com/xiaolin/react-image-gallery/pull/751
