### ISSUE TITLE
Cannot find module 'babel-runtime/core-js/object/assign'

### ISSUE THREAD

**Issue by xueyongg** [xiaolin/react-image-gallery#66]
I am using react 15.0.2, when i follow the instructions. I encountered an error on my console as seen in the title.

Please advise, thank you

**Comment by xiaolin** [comment]
I'm unable to replicate this what version of npm and node are you using?

**Comment by xueyongg** [comment]
The version i use is 0.6.3

Following the instructions from https://www.npmjs.com/package/react-image-gallery

Any advices to go about resolving this issue?

**Comment by xiaolin** [comment]
I released version `0.6.4` which should solve your issue. Let me know if that works.

**Comment by xiaolin** [comment]
@xueyongg I'm going to close this feel free to open if its still an issue.
