### ISSUE TITLE
can I show just single image in middle?  

### ISSUE THREAD

**Issue by baganaakh** [xiaolin/react-image-gallery#668]
name: Label question
image is showing with next pictures half 
Wanted to show one picture at one time

**Comment by spadmabandu** [comment]
I am having the same issue. Image gallery is showing all images, not just a single image.
![Screen Shot 2022-11-14 at 6 38 51 PM](https://user-images.githubusercontent.com/57332728/201797781-859370de-2aec-43f0-9c4f-30696439af4b.png)

My code: 
```
import ImageGallery from 'react-image-gallery';

const TestPage = () => {
  const images = [
    {
      original: 'https://picsum.photos/id/1018/1000/600/',
      thumbnail: 'https://picsum.photos/id/1018/250/150/',
    },
    {
      original: 'https://picsum.photos/id/1015/1000/600/',
      thumbnail: 'https://picsum.photos/id/1015/250/150/',
    },
    {
      original: 'https://picsum.photos/id/1019/1000/600/',
      thumbnail: 'https://picsum.photos/id/1019/250/150/',
    },
  ];
  return <ImageGallery items={images} />;
};
export default TestPage;
```

**Comment by xiaolin** [comment]
That looks like a CSS issue. You'll need to import the CSS file for the component.

**Comment by spadmabandu** [comment]
> That looks like a CSS issue. You'll need to import the CSS file for the component.

Yes, adding the CSS solved the issue. Thanks very much - sorry for the hassle.
