### ISSUE TITLE
Can i make the fullscreen image smaller?

### ISSUE THREAD

**Issue by RadomirVujosevic** [xiaolin/react-image-gallery#669]
Basically I'm looking for a way to make the full screen images slightly smaller -i want them to be about 50-75vh. Is there a way to do this easily?
I tried adding some css but whatever I did, it either messes up the fullscreen images or the smaller images before I click on fullscreen.

**Comment by xiaolin** [comment]
Yes, you can make full screen image whatever size you like as it can be customized by CSS.
