### ISSUE TITLE
getCurrentIndex() returns 'not a function'

### ISSUE THREAD

**Issue by Shobhit1** [xiaolin/react-image-gallery#67]
Was trying getCurrentIndex() function and it keeps returning me `Uncaught TypeError: _this._imageGallery.getCurrentIndex is not a function`  
I tried to console out `this._imageGallery` and i get the component but i dont see any open function with getCurrentIndex()

I am on version ^0.6.1  

Console out of `this._imageGallery`  

>  ![react-image-gallery](https://cloud.githubusercontent.com/assets/4496335/16400649/e02e0b7e-3ca2-11e6-8de3-6ed67ca17bcd.png)

**Comment by xiaolin** [comment]
`getCurrentIndex` was introduced in `v0.6.2`.

**Comment by xiaolin** [comment]
@Shobhit1 closing this, feel free to open if you continue to have problems.

**Comment by Shobhit1** [comment]
Ok. Cool. Thanks for quick reply.
