### ISSUE TITLE
Vertical thumbnail scrolling broken with react 18 rendering

### ISSUE THREAD

**Issue by p-young** [xiaolin/react-image-gallery#674]
The thumbnail scrolling does not get the proper translate when rendering with react 18.

Using the latest image gallery version (1.2.8) and react (18.1.0).

My guess is that the thumbnailsWrapperHeight is registering as 0 at the start (the translation seems to match that) maybe because of how batch updates or rendering has changed in react 18.

After manually resizing the window and thus resizing react-image-gallery, the resize observers fire and the issue improves. However the calculation is still wrong and it is slightly offset from where the scroll should be.

To reproduce, use the latest react and the new way to start the rendering (createRoot() and root.render() instead of ReactDOM.render()), and set thumbnail position to "left" or "right". Then just change slides around and the issue can be seen.

Changing the render back to ReactDOM.render() (which reverts rendering the same way as React 17) fixes the issue.

A picture attached demonstrates the thumbnail scroll being in the wrong position (and out of bounds)

![react-image-gallery-bug](https://user-images.githubusercontent.com/35713583/172502068-e1ac15d6-61ac-4632-9a4a-c417f9d37b73.JPG)

**Comment by p-young** [comment]
Is there anything I can add to help get this looked at? Thanks for the updates!

**Comment by xiaolin** [comment]
Thanks for reporting, I've not had a chance to test react18's new render. Will look into it when I get a chance.

Fastest way is to open a PR if anyone is down to tackle this issue.

**Comment by alexdevmotion** [comment]
Anyone found a fix for this? Can't figure it out.

**Comment by MohammedSaberMohammed** [comment]
@xiaolin @alexdevmotion I've the same issue, any clue ?

**Comment by alexdevmotion** [comment]
@MohammedSaberMohammed unfortunately not, haven't dug for a workaround yet.

**Comment by xiaolin** [comment]
This should be fixed in v1.2.10

**Comment by pickyourdestiny** [comment]
Just to clarify did you mean it will be fixed in version 1.3.10? Thank you in advance

**Comment by FridoAnggoro123** [comment]
> This same issue still exists in React 18.2 and react-image-gallery version 1.30 Thank you in advance.

yess same with me, issue still exists

**Comment by subhanyousaf** [comment]
any update or fix for this?

**Comment by moeabdol** [comment]
Still exists on v1.4.0
