### ISSUE TITLE
Image Gallery goes over other components

### ISSUE THREAD

**Issue by agarabedian** [xiaolin/react-image-gallery#677]
**Describe the bug**
The Image gallery goes over sticky components, such as headers or footers. Can't get it to behave like other components. See example screenshot below.

**Image Gallery Version**
1.2.8

**To Reproduce**
1. Add sticky component such as header or footer.
2. Add Image gallery to page.
3. Parts of the Image gallery go on top of the header or footer (or any sticky positioned component).

**Expected behavior**
Image gallery to behave like other general components.

**Screenshots**
![image](https://user-images.githubusercontent.com/32342672/175439589-db201154-75c1-449f-a32f-843f01efbc60.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Version 102.0.5005.115

**Comment by xiaolin** [comment]
You can use a higher z-index on your sticky footer.
