### ISSUE TITLE
Click on large image to open gallery full screen. 

### ISSUE THREAD

**Issue by raoulguillermo** [xiaolin/react-image-gallery#678]
Would it be possible to add a feature that the user clicks on the image(large one) to open the gallery full screen?
Or can i already do this?

**Comment by xiaolin** [comment]
There are onclick handlers you can override to handle this.

**Comment by Pau1fitz** [comment]
@raoulguillermo @xiaolin what was the solution here. How can you set the default behavior to be full screen?

**Comment by raoulguillermo** [comment]
@Pau1fitz i ended up using a different library.
