### ISSUE TITLE
About startIndex and onSlide event handler

### ISSUE THREAD

**Issue by KevinChien** [xiaolin/react-image-gallery#68]
Hi @xiaolin, 
     When I play image over than 15 items, and start index is last two item. the player will start in error index.
    Ex: I hope start index is 14, but final player start in 7 or 8. And I found the "onSlide" has been trigger twice. It will work as normal, when I play images with index 0~12( onSlide just trigger once when initial )
    After player initialized, it can work as normal(onSlide will trigger once, when I click thumbnail of nav, or by touch slide event)
    I cannot finger out the root cause, or maybe I just set wrong configuration?
    
My sample code:

```
    state:{
       imgArray : [{image_info}, {image_info}, {image_info}, ...]; //15 images 
    }
    <ImageGallery
                ref={i => this._imageGallery = i}
                startIndex={this.state.currentIndex}
                infinite={false}
                lazyLoad={true}
                showNav={false}
                showThumbnails={true}
                items={this.state.imgArray }
                onImageLoad={this.handleImageLoad}
                onSlide={this.handleSlide.bind(this)}
                onClick={this.handleClick.bind(this)}
     />
```

     handleSlide and handleClick just print log, no more else action.

If you need more information, please let me know.
I hope you can help me to solve this problem, thanks.
 :)

Kevin

**Comment by xiaolin** [comment]
How are you setting `this.state.currentIndex` maybe its updating `currentIndex` more than once?

I try to reproduce this by using the sample code and setting `startIndex={13}` and everything is working as expected.

```
<ImageGallery
                ref={i => this._imageGallery = i}
                startIndex={13}
                infinite={false}
                lazyLoad={true}
                showNav={false}
                showThumbnails={true}
                items={images }
                onImageLoad={this.handleImageLoad}
                onSlide={this._onSlide.bind(this)}
                onClick={this._onImageClick.bind(this)}
     />
```

**Comment by xiaolin** [comment]
@KevinChien is this still an issue?

**Comment by xiaolin** [comment]
Closing this, feel free to open again.
