### ISSUE TITLE
Layout shift of gallery controls 

### ISSUE THREAD

**Issue by teaguestockwell** [xiaolin/react-image-gallery#680]
Hello,

I am really enjoying using this component. Thanks for all the work that was put into this for the community to use :) 

**Describe the bug**
Is there a documented best way to prevent layout shift  of the inner controls while the gallery is loading if you know its height and width in advance?

**Image Gallery Version**
This is from https://www.linxtion.com/demo/react-image-gallery/ - I believe this is the latest from master.

**To Reproduce**
https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js
1. Go to https://www.linxtion.com/demo/react-image-gallery/
2. Set network throttling in dev tools to slow 3g
3. Reload the page
4. Set network throttling to offline right when the gallery mounts

**Expected behavior**
Given a known width and height, when the gallery mounts, then it's controls should be in their normal positions while the picture is loading.

**Screenshots**
# Current
![Screen Shot 2022-07-06 at 20 27 52](https://user-images.githubusercontent.com/71202372/177685667-7923b9bf-7d24-4d65-b362-cef0b5faa735.png)
# Expected - something similar to this with a placeholder for the thumbnails?
![Screen Shot 2022-07-06 at 20 55 05](https://user-images.githubusercontent.com/71202372/177687278-8be04431-5eaf-4348-9bae-a213c90453cf.png)

**Comment by xiaolin** [comment]
You can handle this outside the library by detecting whether or not your assets has finished loading. You can render a placeholder container or a loading icon until the first image and thumbnail has loaded, then load the gallery.

Another option is to override `renderItem` and `renderThumbInner` to add your own logic on rendering the content. These functions could wait for the image to load before rendering it.

**Comment by intaek-h** [comment]
@xiaolin can you provide a simple example? I don't quite understand how I can place a loading spinner until the image loads.

**Comment by cardiffinc** [comment]
This is my implementation. Height is 1 because if the div is hidden it'll show the actual height as empty. 

{loading? <LoadingIndicator /> : null}
<div style={loading? {visibility: 'hidden', height: 1}  : null}>
    <ReactImageGallery
        onImageLoad={handleImageLoad}
        items={images} />
</div>

**Comment by shanejdonnelly** [comment]
The fix detailed by @cardiffinc would work great, except that `onImageLoad()` is buggy. Not firing at all for me. See #627 #566 #480 

Given the large CLS hit this component causes, this issue seems worthy of reopening @xiaolin 

PS - Thanks for an otherwise great component!

**Comment by xiaolin** [comment]
If you check the [demo gallery](https://www.linxtion.com/demo/react-image-gallery/) It's firing `onImageLoad` every time you refresh the page, even if the image is from cache. Make sure you have verbose logging turned on to see debug output.

![image](https://user-images.githubusercontent.com/1286776/222644589-49beccd6-b24c-4748-9206-60ee4c1d04eb.png)
