### ISSUE TITLE
How to properly import control components?

### ISSUE THREAD

**Issue by NazarovALAL** [xiaolin/react-image-gallery#681]
Please explain how to properly import Fullscreen to project, for this example

```
renderFullscreenButton: (onClick, isFullscreen) => (
    <Fullscreen onClick={onClick} isFullscreen={isFullscreen} />
  ),
```

I tried

`import ImageGallery, { Fullscreen } from 'react-image-gallery';`

and

`import Fullscreen from 'react-image-gallery/src/controls/Fullscreen';`

**Comment by xiaolin** [comment]
`Fullscreen` is your own component you create to override the existing render of `renderFullscreenButton`

e.g.
```jsx
const MyFullScreenButton = ({ onClick, isFullScreen }) => {
  return isFullScreen ?
    <button onClick={onClick}>Turn off</button>
  :
    <button onClick={onClick}>Turn on</button>
}

renderFullscreenButton: (onClick, isFullscreen) => (
  <MyFullScreenButton onClick={onClick} isFullscreen={isFullscreen} />
),
```
