### ISSUE TITLE
React 18 type issue (`@types/react-image-gallery`)

### ISSUE THREAD

**Issue by ASteinheiser** [xiaolin/react-image-gallery#682]
**Describe the bug**
I am trying to upgrade a project to use latest `react` version `18`. I am unable to build the project with typescript due to a compile error, which I believe is related to a type mismatch between `@types/react-dom` and `@types/react-image-gallery`:
```
'ImageGallery' cannot be used as a JSX component.
  Its instance type 'ReactImageGallery' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("/Users/andrew/Projects/example/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.ts(2786)
```

**Image Gallery Version**
```
"react-image-gallery": "1.2.8",
"@types/react-image-gallery": "1.0.5",
```

**To Reproduce**
1. Create a typescript react project with `react` at version `18.2.0`, `react-dom` at version `18.2.0`, `@types/react` at version `18.0.13`, `@types/react-dom` at version `18.0.5`, `react-image-gallery` at version `1.2.8`, and `@types/react-image-gallery` at version `1.0.5`.
2. Create a component that uses the `ImageGallery` component from `react-image-gallery`.
3. Try to build your project with typescript.

**Expected behavior**
I expected that this project would be able to compile using typescript.

**Desktop (please complete the following information):**
 - OS: macOS 11.5.1

**Comment by xiaolin** [comment]
Hi, I'm not sure who maintains `@types/react-image-gallery`, but it may need an update to work with react 18. Closing this as it's not related to this lib. Feel free to re-open if something can be updated in this package.

**Comment by ruskeyz** [comment]
rm rf node modules, lock files, 
reinstall and it will work
