### ISSUE TITLE
Whole slider size goes wild when different image sizes comes into play

### ISSUE THREAD

**Issue by ModithaAk** [xiaolin/react-image-gallery#684]
**Describe the bug**
when there are smaller pictures the whole slider goes wild with shrinking and growing

**Image Gallery Version**
latest

**To Reproduce**
1. try different image sizes instead of the same image size

**Expected behavior**
some way to keep the size of the slider consistent

**Screenshots**
![image](https://user-images.githubusercontent.com/96397651/180095341-7e0e0a8b-aa40-4291-acb8-025b44ddf738.png)
![image](https://user-images.githubusercontent.com/96397651/180095401-180c3b1e-3992-4943-a857-68b7dd318d2b.png)

**Comment by xiaolin** [comment]
I'm not sure I understand the issue here. Can you clip a video?

**Comment by cajakil** [comment]
I think @ModithaAk is saying that the `<ImageGallery>` resizes when image size varies, and they don't want this to happen.

**Comment by xiaolin** [comment]
Ah, the gallery does not take into account different image sizes and generally, you should have consistent image height & width for a better user experience. If you'd like to have various sizes Id leave it up to you to modify the CSS to support your use case.

**Comment by jmaister** [comment]
For the future visitors of this thread (like me), I solved it with some CSS:

Creating a container with the image class:
```
const ImageContainer = styled.div`
    .image-gallery-image {
        width: 100%;
        height: 600px;
    }
`;
```

Then wrapping the ImageGallery:

```
                <ImageContainer>
                    <ImageGallery
                        items={images}
                        thumbnailPosition="bottom"
                        infinite={true}
                        showBullets={true}
                        showNav={true}
                        showIndex={true}
                        additionalClass="simple-border"
                        />
                </ImageContainer>
```
