### ISSUE TITLE
flickering issue when colour swatch is changed

### ISSUE THREAD

**Issue by Himkumar2** [xiaolin/react-image-gallery#687]
**Describe the bug**
when changing image with item image is flickering in mobile 
**Image Gallery Version**
What version of `react-image-gallery` are you using? 1.2.7

**To Reproduce**
open this in mobile and try to change image by carousel and then change item colour by swatch .
https://www.coach.com/products/swinger-bag/C0638.html?frp=C0638%20B4%2FHA

**Expected behavior**
0th index image should load with out flickering.

**Screenshots**

https://user-images.githubusercontent.com/96405034/181483273-5a6894dc-d8cb-48d8-a93f-ade03fffd60d.mp4

**Smartphone (please complete the following information):**
 - Device: [ iPhoneXR]
 - Browser [ safari]

**Additional context**
<ImageGallery
          ref={elementRef}
          items={items}
          infinite
          showThumbnails={false}
          showNav={false}
          showFullscreenButton={false}
          showPlayButton={false}
          showBullets={true}
          swipeThreshold="10"
          onSlide={handleOnSlide}
        />

**Comment by xiaolin** [comment]
Thanks for reporting, this looks like an issue with transition when rendering a new array of items that needs to start at index 0.

**Comment by Himkumar2** [comment]
Hi @xiaolin yes it need to start from start at index 0 and it does like that but smoothness is not there in transition flickering of last set of image is happening.

**Comment by xiaolin** [comment]
This should be fixed in v1.2.9
https://github.com/xiaolin/react-image-gallery/releases/tag/v1.2.9
