### ISSUE TITLE
How to set size for the gallery

### ISSUE THREAD

**Issue by vinhtq** [xiaolin/react-image-gallery#69]
I see that the gallery will adjust size base on the image inside.
But if i want to adjust custom size how can i do that?

**Comment by xiaolin** [comment]
I'm not sure what you mean by this. Can you give an example?

**Comment by vinhtq** [comment]
I have image size: 400x300
But the gallery auto adjust the size to 266x200 like the image here: http://imgur.com/crUoaDi

I check but there is not option for setting the width, height for the gallery. So how can I set the dimension for the gallery

**Comment by vinhtq** [comment]
It works, thank you!

**Comment by Andynopol** [comment]
But how can I set the size of the whole slider?

If the property "sizes" is the answer, I would like to see an example of how to use this property. I have made some tries(like sizes={width:'100px'} or sizes={{width:'100px'}}) but no success so far.

**Comment by ndricimrr** [comment]
@Andynopol  I had a similiar question, Something like this solved it for me: 
```
.image-gallery {
    width: 400px;
}
```
As for how to use the **sizes** property I had a similar intuition but it doesn't seem to work like that. As specified in the docs [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img) you also need to specify **srcset** alongside **sizes** :

> If the srcset attribute is absent, or contains no values with a width descriptor, then the sizes attribute has no effect.

If it helps you may find an explained example on how to use it [here](https://medium.com/@MRWwebDesign/responsive-images-the-sizes-attribute-and-unexpected-image-sizes-882a2eadb6db)

**Comment by m3c-ode** [comment]
Hi there!

I also wanted to control the size of the gallery, because it changed on every single picture... Is that the only way to control this?
The problem with this control is that, when I toggle the fullscreen mode, this height I defined 
```
.image-gallery-slide img {
  height: 500px;
}
```

is still applicable. And I would like it to be full screen.

What would be a suggestion?
