### ISSUE TITLE
Can't prevent swipes after version 1.1.0

### ISSUE THREAD

**Issue by qrisse** [xiaolin/react-image-gallery#690]
I have an app that uses Image Gallery that sometimes have a react-compare-image component inside of it. I have changed the react-compare-image component to not propagate touch events if the slider is being touched so that image gallery should not swipe to the next image. 

Efter updating Image Gallery this does not seem to work anymore. I created an example in https://codesandbox.io/s/react-playground-forked-79f12f?file=/index.js which works with 1.0.10 but not with 1.1.0. 

Funny thing is that on rare occasions it actually does work even with newer versions, but I haven't managed to figure out when this happens, and most of the times image gallery and compare image swipes at the same time which makes the image compare pretty useless on touch devices. 

Can be reproduced on desktop by opening the app in a new window and toggling to device toolbar in Chrome inspector. 

1. Swipe to the second image
2. Touch the middle bar and slide left/right - the bar should move, but gallery should not move
3. Touch anywhere else in the image and bar should be moved to that location, but when swiping starts it should swipe to the next/prev image. 
4. Switch version of react-image-gallery between 1.0.10 and 1.1.0 to see the change in behavior. 

Don't know if this is a bug in Image Gallery or not, but somehow this stopped working and there seem to be quite a lot of changes between 1.0.10 to 1.1.0 so it's hard to identify what I need to do to get this working again.

**Comment by xiaolin** [comment]
I'm not sure I understand the issue you're having, but have you tried using `disableSwipe`? Looks like you want to separate gallery swipe events with the compare slider swipe.

**Comment by qrisse** [comment]
I don't want to disable sweep completely, but only when touching the slider bar in the image compare. Previously I was able to call e.preventDefault(); and e.stopPropagation(); to stop the events from bubbling to image gallery if the slider bar was the element that was touched, but now that does not seem to work anymore so both packages do sliding which is kind of awkward. 

So it really doesn't have to be the compare-image component per se, but how would I go about preventing touch events from propagating from a child component in renderItem to react-image-gallery code?

**Comment by qrisse** [comment]
Finally found the problem, before 1.1.0 it was apperently enough to stop propagation of the touchstart event to prevent image gallery from swiping, but from 1.1.0 touchmove also needs to be stopped. So not really a but in image gallery, just changed behavior.
