### ISSUE TITLE
Custom renderItem 3d canvas is not working.

### ISSUE THREAD

**Issue by krishnakantgaudcimpress** [xiaolin/react-image-gallery#691]
**Describe the bug**
The 3D canvas slide is rendered using renderItem, and the custom thumbnails are displayed using renderThumbInner. We now have a total of three slides, the first of which is a 3D canvas (using the renderItem) and the other two are images. It functions properly when I click on the second slide and it returns to the first slide, which is once more a canvas. However, 3D doesn't function when I click on the second slide, the third slide, and finally the first slide.  I've noticed that the canvas's width and height reset, which is why it stops functioning.

**Image Gallery Version**
"react-image-gallery": "^1.2.8",

**Expected behavior**
Regardless of the slide selected, a 3D canvas slide should always function.

**Screenshots**
<img width="590" alt="Screenshot 2022-08-08 at 4 16 16 PM" src="https://user-images.githubusercontent.com/75369276/183403972-3f49eac7-8619-49f6-8b12-f5904ecd2e55.png">

**Video**
https://user-images.githubusercontent.com/75369276/183403275-d8447260-f64e-4787-8cb4-7c2c0d0696d1.mp4
(Chrome is a recommended browser for opening the video)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: Version 103.0.5060.134 (Official Build) (x86_64)

**Comment by xiaolin** [comment]
Can you provide steps to reproduce? The lib should not be affecting the height/width changes of the canvas item you're rendering.

Take a look at the [demo](https://www.linxtion.com/demo/react-image-gallery/), which renders a custom video (iframe) in the first slide. I am not able to reproduce the disappearing slide you're seeing in the video.
