### ISSUE TITLE
Invalid hook call error

### ISSUE THREAD

**Issue by shivak-cbre** [xiaolin/react-image-gallery#696]
**Describe the bug**
Invalid hook call error in useSwiepable  in image-gallery.js 

**Image Gallery Version**
What version of `react-image-gallery` are you using?
1.0.6 to 1.2.9 

**To Reproduce**
I recently update the react scripts version from 3 to 5 . my react and react-dom version is 16.10.2. I am facing this issue in my app when I linked one of my libraries locally. it is not happening when I get the same package from the npm registry 

**Expected behavior**
It should work with out giving invalid hook call error

**Screenshots**
![image](https://user-images.githubusercontent.com/82529125/185604411-66a77c6d-1134-4483-98c3-b5db5b5d9339.png)

**Comment by xiaolin** [comment]
Please see https://stackoverflow.com/questions/56663785/invalid-hook-call-hooks-can-only-be-called-inside-of-the-body-of-a-function-com
