### ISSUE TITLE
Alt + left/right arrow causes next image to slide in

### ISSUE THREAD

**Issue by dummy26** [xiaolin/react-image-gallery#697]
**Describe the bug**
Alt + left/right arrows are used to navigate to previous or next page in browsers, but they also cause next image to slide in

**Image Gallery Version**
1.2.9

**To Reproduce**
1. Press Alt + left/right arrow
2. Image slides

**Expected behavior**
Image doesn't slide

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Microsoft Edge
 - Version 104.0.1293.70

**Comment by xiaolin** [comment]
You can disable arrow keys using `disableKeyDown`
