### ISSUE TITLE
Error loading build css on latest react/webpack versions

### ISSUE THREAD

**Issue by msmfsd** [xiaolin/react-image-gallery#70]
Error is: 
`ERROR in ./~/react-image-gallery/build/image-gallery.css
Module parse failed: .../node_modules/react-image-gallery/build/image-gallery.css Unexpected character '@' (1:0)`

If you remove:
`@charset "UTF-8";`
it works ok.

**Comment by xiaolin** [comment]
How are you importing the css file?

Does this stackoverflow discussion help?

http://stackoverflow.com/questions/37369318/material-design-lite-with-react-and-webpack

**Comment by msmfsd** [comment]
I had copied the file to my src directory and loading it with module loader for css set to 
`style-loader!css-loader`

**Comment by xiaolin** [comment]
`@charset "UTF-8"` is a w3 standard, this is definitely odd.

**Comment by msmfsd** [comment]
Agreed that it is an odd error and could just be my config possibly. Am on OSX and my IDE sets all my css files to utf-8 so this is not a huge issue.

**Comment by xiaolin** [comment]
Closing this.
