### ISSUE TITLE
 Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by fedot199614** [xiaolin/react-image-gallery#700]
Received this issue:
`./node_modules/react-image-gallery/src/ImageGallery.js
SyntaxError: ... ImageGallery.js: Support for the experimental syntax 'jsx' isn't currently enabled (512:9):

  510 | 
  511 |       const slide = (
> 512 |         <div
      |         ^
  513 |           aria-label={`Go to Slide ${index + 1}`}
  514 |           key={`slide-${index}`}
  515 |           tabIndex="-1"

Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 'plugins' section of your Babel config to enable transformation.`

**Comment by xiaolin** [comment]
Please follow the template on opening issues, and provide reproducible steps.
