### ISSUE TITLE
Incorrect TS type definition of 'type ReactImageGalleryItem'

### ISSUE THREAD

**Issue by nik32** [xiaolin/react-image-gallery#702]
**Describe the bug**
The TS type definition of 'type ReactImageGalleryItem' does not contain definition for attributes 'loading' and 'thumbnailLoading' - even though they are valid properties for 'item' object according to the docs

**Image Gallery Version**
1.2.9

**To Reproduce**
1. Set-up a TS-react app
2. Install the TS types for react-image-gallery
3. In VS code - just define the items array with type as 'ReactImageGalleryItem' and define the 'loading' or 'thumbnailLoading' property in this items array (as shown in the below image) -
<img width="983" alt="image" src="https://user-images.githubusercontent.com/51018572/193396937-b89aa5de-5d41-4dbc-a948-c32dd03f0950.png">

**Expected behavior**
TS should not produce error while using 'loading' or 'thumbnailLoading'. Just add these properties in you TS types

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by xiaolin** [comment]
Hey, there are no officially supported TS for react-image-gallery. The one you're using is likely an open-source version that may be out of date.

**Comment by nik32** [comment]
Got it. Thanks for such a quick reply and for such a great component!!
