### ISSUE TITLE
Original and fullscreen images. Incorrect behavior.

### ISSUE THREAD

**Issue by maksimdev** [xiaolin/react-image-gallery#709]
Our app has 3 different images: thumbnail, original and fullscreen. (size and quality)
There is a bug when you click to open in fullscreen mode.
First of all, our original image will be shown and only in a half of second will be changed to fullscreen image.
Browsers Chrome and Safari.

Possible solution for this is to do not use fullscreen prop at all but I would like to use fullscreen prop as well.

`
<ImageGallery
                items={[{
                    "original":"/images/image-gallery/1.original.img",
                   "fullscreen":"/images/image-gallery/1.fullscreen.img"
                }]}
/>
`
On this screenshot you can see two different sizes (original and fullscreen):
<img width="1440" alt="Screenshot 2022-11-30 at 09 33 37" src="https://user-images.githubusercontent.com/33132871/204751212-2938b8a4-ea2b-4a9f-a16d-99dde08cb0e2.png">

On your website(https://www.linxtion.com/demo/react-image-gallery/) as example you use only original prop.

Could you verify the issue please. Thanks!

**Comment by xiaolin** [comment]
The full-screen images are not loaded until fullscreen is toggled, with lager images the browser would need to download it to update the slide.

I suggest pre-loading your fullscreen images if you're expecting users to frequently go into fullscreen mode, this way, the browser will load and cache the image ahead of time.

You can do this in a few ways, below is an example of preloading images in HTML.

e.g.
```
<link rel="preload" as="image" href="/images/image-gallery/1.fullscreen.img">
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload
