### ISSUE TITLE
AutoScroll stops on android device after clicking on image

### ISSUE THREAD

**Issue by texate** [xiaolin/react-image-gallery#71]
First of all, the component is wonderful.
Easy to use example, good demo, all you need to know is documented.
Good job.
I used component like this:
```javascript
<ImageGallery
  ref={i => this._imageGallery = i}
  items={slides}
  infinite={true}
  showThumbnails={false}
  showNav={false}
  showBullets={true}
  autoPlay={true}
  slideInterval={SLIDER_AUTOPLAY_TIMEOUT}
  onClick={this.handleOnClick}
/>
```
On Android device automatic scrolling of images working fine until i touch the image itself (not the bullet).
If i touch the image i'll see onClick event and after that automatic scrolling is stop working.
```javascript
handleOnClick() {
  this._imageGallery.setState({
    hovering: false
  });
  this._imageGallery.play(this._imageGallery.state.currentIndex);
},
```
Adding the code above solved the problem, but i wonder is this a good solution and why this behavior reproducible only on Android, but not on iOS. Is there an easiest way to solve the problem i'm talking about?

**Comment by xiaolin** [comment]
The reason this is happening is because `onMouseOver` is being triggered when you click on the image. I can replicate this on a touched enabled browser. I have to think a bit on the right solution, this one is a bit tricky.

**Comment by xiaolin** [comment]
This is fixed since `onMouseOver` has been removed from image slides.
