### ISSUE TITLE
How to make thumbnails wrapper width 100% of it's container?

### ISSUE THREAD

**Issue by zebedal** [xiaolin/react-image-gallery#715]
**Checklist before opening an issue**\
Lots of issues are opened that are unrelated to this package, please take a moment to ensure the issue is not on your end 🙏.
- [x] Did you try google?
- [x] Did you search for previous Issues in this repo?

**Describe the bug**\
I am having issues trying to make the thumbnails wrapper to be 100% width. If I set the width manually it works but trying to make it 100% is causing an overflow on the screen. 

**Image Gallery Version**\
1.2.11

**Expected behavior**\
I expected the thumbnails wrapper to be able to stretch to 100% of it's container so I can have fully responsive behaviour

**Client info (please complete the following information):**\
 - OS: [e.g. iOS] MacOS Ventura
 - Browser: [e.g. chrome, safari] Chrome

**Comment by xiaolin** [comment]
The thumbnail does stretch to 100% width of its container, see example.
