### ISSUE TITLE
React v15 throws 'Unknown props' Warning

### ISSUE THREAD

**Issue by msmfsd** [xiaolin/react-image-gallery#72]
After upgrading react to 15.2.1 I get the following warning:

```
Warning: Unknown props `delta`, `onSwipingLeft`, `onSwipingRight`, `onSwiped`, `onSwipedLeft`, `onSwipedRight`, `flickThreshold`, `preventDefaultTouchmoveEvent`, `nodeName` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Swipeable)
    in Swipeable (created by ImageGallery)
    in div (created by ImageGallery)
    in section (created by ImageGallery)
    in ImageGallery (created by MyComponent)
    in div (created by MyComponent)
```
Warning references: [https://fb.me/react-unknown-prop](https://fb.me/react-unknown-prop)
See following issues:
[https://github.com/facebook/react/issues/7163](https://github.com/facebook/react/issues/7163)
[https://github.com/callemall/material-ui/issues/4594](https://github.com/callemall/material-ui/issues/4594)

**Comment by xiaolin** [comment]
@msmfsd Thanks, I will take a look at this when I get a chance.

**Comment by msn0** [comment]
Above warnings relates to react-swipeable and should be fixed right now in `react-swipeable@3.5.1` https://github.com/dogfessional/react-swipeable/pull/44/files

These still remains:
```
Warning: Unknown props `activeDelay`, `classBase`, `handlers` on <span> tag. Remove these props from the element.
```

and we are waiting for https://github.com/JedWatson/react-tappable/issues/79

**Comment by msmfsd** [comment]
Thanks @msn0 the swipable update has removed all warnings from the console for me with no side effects. Cheers.

**Comment by xiaolin** [comment]
Thanks, will bump up the version for react-swipeable on the dependencies.

**Comment by xiaolin** [comment]
bumped react-swipeable to 3.5.1 in v0.6.5
