### ISSUE TITLE
Add videos in display

### ISSUE THREAD

**Issue by suntong** [xiaolin/react-image-gallery#720]
**Is your feature request related to a problem? Please describe.**

Risking to be closed immediately as #675, 

I want to mix pictures and videos for display.

**Describe the solution you'd like**

I _know_ there is example code, but only YouTube videos are supported so far, as confirmed in #600,   
whereas I want to show my own videos and images.

I know that online viewing/preview might be difficult, but showing them in list and offering to download might be an easier start, which will be more than good enough for me.

**Describe alternatives you've considered**

No alternatives I can think of, as I don't want to upload my own videos to YouTube just for this.

**Additional context**

N.A.

**Comment by suntong** [comment]
online viewing/preview _seems_ to be not too difficult, based on this file

https://github.com/harryyizihan/around_web/blob/f882f4aeee4cd865db2f37272fed9de44057ae7b/src/components/Home.js#L112

and this Demo video: https://youtu.be/tXMTwyzDsZk

**Comment by xiaolin** [comment]
You can use `renderItem` and custom render your own videos. This lib itself does not support videos and the example with youtube slide is showcase what you can do using `renderItem`

**Comment by suntong** [comment]
OK, I'm not a JS developer at all, but I'' take a look...

**Comment by suntong** [comment]
closed as completed? Could you point out which commit fix the reported issue please.

**Comment by xiaolin** [comment]
There was no issue here, I only saw a question, which I answered and you acknowledged, so I'm closing.

**Comment by suntong** [comment]
The request was titled _"Add videos in display"_, and in OP it says, 

> I want to show my own videos and images.

A feature obviously _missing_ from react-image-gallery.

**Comment by suntong** [comment]
> Risking to be closed immediately as #675,
> 
> I want to mix pictures and videos for display.

Good that this is _not_ the _only_ react-image-gallery available, as the grass is greener over here --  
https://github.com/OriAmir/React-Responsive-Gallery

**Comment by boly38** [comment]
U're right, and this one is so amazing too
https://github.com/igordanchenko/yet-another-react-lightbox

**Comment by xiaolin** [comment]
@suntong please read my original reply above yours.
> You can use renderItem and custom render your own videos. This lib itself does not support videos and the example with youtube slide is showcase what you can do using renderItem

Adding video to your slide can be achieve by adding your own `renderItem` function. Here is an example (not tested, rough).

```javascript
  renderVideo(item) {
    return (
      <div>
        <video controls >
          <source src={item.videoSrc} type="video/mp4" />
        </video>
      </div>
    )
  }

  render() {
    const myCustomItems = [
      {
        thumbnail: 'https://www.w3schools.com/html/mov_bbb.jpg',
        videoSrc: 'https://www.w3schools.com/html/mov_bbb.mp4',
        renderItem: this.renderVideo // this will use your custom function to render the video
      }
    ];
  
    return <ImageGallery items={myCustomItems} />
  }
```

👋 Friendly reminder that this is a **free** and **open source** lib, being snarky and passive aggressive here does not help anyone 👎

**Comment by boly38** [comment]
"as the grass is greener over here" was probably too much. I personnaly reacted to the suggest to open to more project to get/pick idea from there. Any project could helps others. And thanks @xiaolin : the current repository and react-image-gallery is really amazing and I was using it from 3 years ago with a lots of pleasure. Continue on this ; it participate to the open source movement andreact adoption with many success 👍 👍
