### ISSUE TITLE
Accessibility: Alt text for thumbnail images

### ISSUE THREAD

**Issue by andy-lamb** [xiaolin/react-image-gallery#723]
**Is your feature request related to a problem? Please describe.**
Our accessibility audit requires alt text on all non-decorative images

**Describe the solution you'd like**
Could there be a way to add alt text to thumbnail images?

Great component, really enjoy using it, thanks.

**Comment by xiaolin** [comment]
Yes, there is a `thumbnailAlt` prop you can pass in the component. See readme for more info.
