### ISSUE TITLE
Control on Preload images.

### ISSUE THREAD

**Issue by yashvekaria** [xiaolin/react-image-gallery#724]
**Is your feature request related to a problem? Please describe.**
I am using this image gallery on the list where there are 20 items where item has its own gallery. So while checking on performance on the mobile viewport. I figured out it preloads 3 images for each item. so nearly 60 images and it consumes up to 8Mbs of data. So I felt if something like preload prop was given where I can pass 2 images instead of 3 then also it would create a significant impact on performance. 

The same type of question was raised in Nov 2017 but after that no further updates.
https://github.com/xiaolin/react-image-gallery/issues/231

**Describe the solution you'd like**
```preloadImage={2} //default to 3```

**Describe alternatives you've considered**

**Additional context**

**Comment by xiaolin** [comment]
You can use `loading="lazy"` for your images if you want to defer some of those 20 items that may not be viewed yet.
