### ISSUE TITLE
Build error using Astro framework

### ISSUE THREAD

**Issue by menepet** [xiaolin/react-image-gallery#727]
# Build error using Astro framework

I am using Astro framework with `react-image-gallery` and everything was going fine on dev environment running as expected showing the image gallery. Only when I tried to make a **prod build** (static generation) using the command: `astro build` the build fails at the page the `<ImageGallery />`  is used with error:

```
 error   Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

 ### Steps to reproduce:
Make a new [Astro](https://docs.astro.build/en/getting-started/#start-your-first-project) project and use [react](https://docs.astro.build/en/guides/integrations-guide/react/#installation) and `react-image-gallery`.

Part of my `package.json`:

```json
  "dependencies": {
    "@astrojs/react": "~2.1.1",
    "@types/react": "~18.0.21",
    "@types/react-dom": "~18.0.6",
    "astro": "~2.3.0",
    "react": "~18.2.0",
    "react-dom": "~18.2.0",
    "react-image-gallery": "~1.2.11"
  },
```
The component that the error comes from:

`components/project.jsx`:
```jsx
import React from "react";
import ImageGallery from "react-image-gallery";
import "react-image-gallery/styles/scss/image-gallery.scss";
import styles from "./styles.module.scss";

function ProjectPage({ project = {} }) {
  return (
    <div className={styles.project}>
      <ImageGallery
        items={project.images}
      />
    </div>
  );
}
export default ProjectPage;
```

And I consume the above inside an Astro page component like:
```
---
import ProjectView from '@components/project';
---

...
<ProjectView project={selectedProject} client:load />
...
```

node version: `v18.14.2`

As far I searched for this error I found that is about how to import the component.

When I comment out the `<ImageGallery />` the error does not exist. Why this happens ?

**Comment by qpIlIpp** [comment]
Was facing the same issue. 
This one helped:
https://github.com/vitejs/vite/issues/6776#issuecomment-1031215897

```
import Gallery from "react-image-gallery";
const ImageGallery = (Gallery as any).default ?? Gallery;
```

**Comment by menepet** [comment]
> Was facing the same issue.
This one helped:
https://github.com/vitejs/vite/issues/6776#issuecomment-1031215897

Seems that works like a charm this solution! Thanks @qpIlIpp

**Comment by matthewmcvickar** [comment]
If you are not using TypeScript, this workaround will work:

```js
import Gallery from 'react-image-gallery';
const ImageGallery = Gallery.default ? Gallery.default : Gallery;
```

**Comment by dwin0** [comment]
> Was facing the same issue. This one helped: [vitejs/vite#6776 (comment)](https://github.com/vitejs/vite/issues/6776#issuecomment-1031215897)
> 
> ```
> import Gallery from "react-image-gallery";
> const ImageGallery = (Gallery as any).default ?? Gallery;
> ```

Thanks @qpIlIpp for your solution!

For full TypeScript support, I added the following:

```ts
import Gallery from 'react-image-gallery';
const ImageGallery = ((Gallery as any).default as typeof Gallery) ?? Gallery;
```
