### ISSUE TITLE
Will not work on server, Super expression must either be null or a function

### ISSUE THREAD

**Issue by innotivity** [xiaolin/react-image-gallery#731]
**Checklist before opening an issue**\
Lots of issues are opened that are unrelated to this package, please take a moment to ensure the issue is not on your end 🙏.
- [X] Did you try google?
- [X] Did you search for previous Issues in this repo?

**Describe the bug**\
Works fine on local machine, when uploaded to server, gives "image-gallery.js:1046 Uncaught TypeError: Super expression must either be null or a function
    at image-gallery.js:1050:1", etc.  Entire page will not load.  

**Image Gallery Version**\
v1.2.11 and v1.2.7

React 17.0.2

**To Reproduce**\
1. Load to server on a page, load main page or any page.  
2.  Are dead. 

**Expected behavior**\

**Screenshots**\

**Client info (please complete the following information):**\
 - Browser: [e.g. chrome, safari]

**Additional context**\

**Comment by innotivity** [comment]
Also having this issue https://stackoverflow.com/questions/73502127/local-environment-working-when-pushed-up-to-amplify-uncaught-typeerror-super-e

**Comment by h27-webdev** [comment]
@innotivity any update on this? were you able to fix the issue at your end?

**Comment by xiaolin** [comment]
This does not seem to be an issue with this lib and looks to be something related to your build config.

**Comment by riteshreg** [comment]
do we have any update
