### ISSUE TITLE
Prop drill an optional ref prop to the root div

### ISSUE THREAD

**Issue by jordanparker6** [xiaolin/react-image-gallery#735]
**Is your feature request related to a problem? Please describe.**

I am trying to use react-image-gallery for its smart and responsive image display. It works really well. However, I can't get it to work with a library that needs to attach a ref to the root of react-image-gallery and access the array of photos. I need to be able to attach a ref to the root div of the Gallery component and then run some JS library on the root. It would be awesome if there was an optional ref prop that passed through to the root so this functionality would work

**Describe the solution you'd like**

add an optional ref to the Props of the Gallery and attach this ref prop to the ref={ref} attribute of the root html tag of the gallery.

**Describe alternatives you've considered**

This is the only way to get it to work. Would be great win for customisation

**Comment by zainkhas** [comment]
This is already available. Try something like this. This is also in the example.

```
 <ImageGallery
          ref={i => this._imageGallery = i}
... />
```

**Comment by zainkhas** [comment]
Looks like this was missing in the docs, so added it here https://github.com/xiaolin/react-image-gallery/pull/738
