### ISSUE TITLE
Switching to functional components

### ISSUE THREAD

**Issue by mkoumila** [xiaolin/react-image-gallery#737]
**Is your feature request related to a problem? Please describe.**
I'm having a problem of using this library with other components in my projects which are based on functional components.

**Describe the solution you'd like**
I suggest to switch the code structure to functional components to be able to use with other components and unlock the full capacity of hooks.

**Comment by zainkhas** [comment]
@mkoumila Can you please elaborate and provide some examples to understand what exactly is blocking you.

**Comment by mkoumila** [comment]
@zainkhas As we all know, Class components aren't used anymore because the code is clearer and less complicated, And i can't use hooks and custom hooks inside of it especially if my whole project is built with functional components.

**Comment by xiaolin** [comment]
You should not run into issues mixing class components and functional components with hooks.

**Comment by xiaolin** [comment]
Eventually, Id like to refactor to functional components, but have not found the time to do so yet 😛
