### ISSUE TITLE
Is it possible to make the thumbnail list vertical, like, on the left or the right side?

### ISSUE THREAD

**Issue by phoenixgao** [xiaolin/react-image-gallery#74]
I've tried to use css to achieve this but the positions of the thumbnails seems to be calculated in javascript

**Comment by msn0** [comment]
We did it here https://allegro.de/produkte/monitor-34-um-cx1ee-001-c9393b46-597c-4713-a7f9-c7875ef8c1cf with only css.

**Comment by xiaolin** [comment]
@phoenixgao you can also stop the calculation of thumbnail scrolling using `disableThumbnailScroll` as a prop

**Comment by xiaolin** [comment]
@msn0 really awesome work with that design! 👍

**Comment by xiaolin** [comment]
@phoenixgao did you solve your issue?

**Comment by xiaolin** [comment]
Closing this, feel free to reopen if you have further questions.

**Comment by phoenixgao** [comment]
sorry for late reply, yes I've tried flexbox thanks to the awesome work from @msn0, but then it doesn't scroll as expected. I will try to make vertical scrolling work by myself later, thanks!

**Comment by xiaolin** [comment]
@phoenixgao release v0.7.6 allows for the option to set thumbnails vertically.

**Comment by phoenixgao** [comment]
Hi @xiaolin Thanks for the update !!
