### ISSUE TITLE
Slide no longer works

### ISSUE THREAD

**Issue by iolloyd** [xiaolin/react-image-gallery#75]
After updating to the latest version to resolve the issue of sliding to the left in the event that there were only two images, slide no longer works.

**Comment by iolloyd** [comment]
Update. This now works if I set lazyLoad to false.

**Comment by xiaolin** [comment]
@iolloyd thanks for the report, I know exactly whats causing this. I will release another version tonight.

**Comment by xiaolin** [comment]
@0.6.7 fixes this.
