### ISSUE TITLE
v1.2.11 works perfectly on my project, then the gallery break on v.1.2.12 and v.1.3.0

### ISSUE THREAD

**Issue by ivanyufen** [xiaolin/react-image-gallery#752]
Here is my code: `render() {
    const { images, defaultImage, height, onClick, useLazyLoad } = this.props;

    const newImages = images.map((img) => {
      return {
        original: typeof img === 'object' ? img.c_url : img,
        originalClass: 'slider-image',      };
    });

    return (
      <div>
        {useLazyLoad ? (
          <LazyLoadComponent>
            <ImageGallery
              showThumbnails={false}
              defaultImage={defaultImage}
              items={newImages}
              showFullscreenButton={false}
              showPlayButton={false}
              onClick={onClick}
              stopPropagation={true}
              lazyLoad={useLazyLoad}
            />
          </LazyLoadComponent>
        ) : (
          <ImageGallery
            showThumbnails={false}
            defaultImage={defaultImage}
            items={newImages}
            showFullscreenButton={false}
            showPlayButton={false}
            onClick={onClick}
            stopPropagation={true}
            lazyLoad={useLazyLoad}
          />
        )}
      </div>
    );
  }`

I just upgraded from version 0.9.0 and found that my code works until v.1.2.11. Started from v.1.2.12 and v.1.3.0 it just won't works.. here is the screenshot in the UI:
v.1.2.12 and v.1.3.0 (not showing anything, but no error)
<img width="346" alt="image" src="https://github.com/xiaolin/react-image-gallery/assets/25142502/43145993-3abf-46c8-9d70-5232aba0ef11">

expected result on v.1.2.11
<img width="340" alt="image" src="https://github.com/xiaolin/react-image-gallery/assets/25142502/dca95238-60af-41d8-acd2-c1b8e121aa43">

**Comment by ShotSkydiver** [comment]
Same thing happens for me, I'm assuming it's due to the CSS class name changes in 1.2.12, personally I use a custom CSS file for the image gallery that I import, and I see that the SCSS file changed in 1.2.12, but not the CSS file. Could be an oversight?

**Comment by ShotSkydiver** [comment]
I was actually just able to fix this for me by updating my image gallery CSS file (I had just duplicated the original image gallery css and modified it for my needs), the main changes in 1.2.12 are just renaming the `.image-gallery-thumbnails.left` and `.image-gallery-thumbnails.right` to `.image-gallery-thumbnails-left` and `.image-gallery-thumbnails-right`, as well as the same for `.image-gallery.center` to `.image-gallery-center`, if you're using a custom CSS file with those classes, making those name changes should work!

**Comment by ivanyufen** [comment]
> I was actually just able to fix this for me by updating my image gallery CSS file (I had just duplicated the original image gallery css and modified it for my needs), the main changes in 1.2.12 are just renaming the `.image-gallery-thumbnails.left` and `.image-gallery-thumbnails.right` to `.image-gallery-thumbnails-left` and `.image-gallery-thumbnails-right`, as well as the same for `.image-gallery.center` to `.image-gallery-center`, if you're using a custom CSS file with those classes, making those name changes should work!

hey, thanks! i replaced the whole old css with newer image-gallery.css and now it works seamlessly

**Comment by xiaolin** [comment]
looks like all is good, closing.
