### ISSUE TITLE
Thumbnails Navigation 

### ISSUE THREAD

**Issue by Abhimanyuv92** [xiaolin/react-image-gallery#76]
Can we have a navigation for thumbnails similar to that of original images.?

**Comment by xiaolin** [comment]
This shouldn't be too hard to implement. I'll take a look at this when I get a chance.

**Comment by Blkc** [comment]
I am not sure if I am asking the same thing as above, but I would like swiping on thumbnails since when there are alot of thumbnails it is better on mobile for the user to be able to swipe to the image they want rather than to use the bullets to navigate. Is swiping on thumbnails in progress?

**Comment by xiaolin** [comment]
I think @Abhimanyuv92 was talking about having left, and right arrow navigation that will slide a series of thumbnails. But as apart of that I did plan to have swipe functionality too.

Currently not in progress.

**Comment by xiaolin** [comment]
Closing this as its a feature enhancement related to PR #189
