### ISSUE TITLE
How to customize styles of thumbnail?

### ISSUE THREAD

**Issue by bsor-dev** [xiaolin/react-image-gallery#761]
I would like to change border color and spacing of thumbnail but it seems like there is no default way to do it

**Comment by patrickgratao** [comment]
Hi @bsor-dev, 

You can change border-color and spacing (gap) using css classes. 

To add spaces between thumbnails you can use this class:

`.image-gallery-thumbnails .image-gallery-thumbnails-container`

```
display: flex;
justify-content: center;
gap: 1rem;
```

To change border color you can use this class:

`.image-gallery-thumbnail.active, .image-gallery-thumbnail:focus`

Hope be helpfull.

**Comment by la-salman** [comment]
@patrickgratao I've positioned the thumbnails on the left, and now I want to vertically center align them. I'm using Tailwind CSS. How can I achieve this?
