### ISSUE TITLE
add virtual list

### ISSUE THREAD

**Issue by 2218675712** [xiaolin/react-image-gallery#765]
When there are more than 3000 pictures in the gallery, clicking will freeze for 5 seconds. Can you add a virtual option and use a virtual list for calculation when switching to avoid lag caused by DOM redrawing?

**Comment by xiaolin** [comment]
Have you tried the lazyLoad option? it essentially limits the render to only three elements.

**Comment by 2218675712** [comment]
I tried the lazyLoad option?But it was very laggy.
 
  When I reduced the items to 100, the problem disappeared. 
  
  I checked the dom and found that with the lazyLoad option turned on, each button in the dom would still be rendered. Maybe there were too many buttons.

**Comment by 2218675712** [comment]
<img width="1266" alt="image" src="https://github.com/xiaolin/react-image-gallery/assets/38459269/0bf21940-3cee-4bc3-83a8-f1be8cda48a1">

**Comment by 2218675712** [comment]
Thank you, I think I can achieve this by manually controlling the content of an item

**Comment by 2b0x** [comment]
> It’s likely the thumbnail and bullets causing an issue. If you don’t need thumbnails and bullets you can disable them both and that should help. Eventually we would need virtualization on thumbnails and bullets for it to work with large data.

i have the same problem when i render more than 1000 item in react-image-gallery, when i trigger onThumbnailClick, DOM Render was be very slow.
