### ISSUE TITLE
Astro Project in Vercel doesnt work

### ISSUE THREAD

**Issue by Laguilavo10** [xiaolin/react-image-gallery#768]
**Checklist before opening an issue**\
Lots of issues are opened that are unrelated to this package, please take a moment to ensure the issue is not on your end 🙏.
- [X ] Did you try google?
- [ X] Did you search for previous Issues in this repo?

**Describe the bug**\

I'm using react-image-gallery in an Astro project, it works fine in dev environment, however I upload the project to Vercel and it doesn't work. I get an error [500: FUNCTION_INVOCATION_FAILED](https://vercel.com/docs/error/application/FUNCTION_INVOCATION_FAILED#500:-function_invocation_failed)
The invocation of a serverless function was not completed successfully. This is an application error.

When I remove the component, the project works fine, so the problem is caused by the library.  

**Image Gallery Version**\

What version of `react-image-gallery` are you using?
1.3.0

**Screenshots**\
![image](https://github.com/xiaolin/react-image-gallery/assets/111542850/84237669-1894-49ba-8cf7-2b86217edf2d)
![image](https://github.com/xiaolin/react-image-gallery/assets/111542850/e601580f-e21b-4a39-a251-1bf410d7d4c4)

**Client info (please complete the following information):**\
 - OS: Windows 
 - Browser: Chrome

**Comment by xiaolin** [comment]
Not sure what happened here. Is there a better stacktrace you can provide to check on the actual error? The error above does not help much with debugging.

**Comment by xiaolin** [comment]
Is Astro ESM? this package is bundled using UMD. Try importing it this way.

```
import Gallery from 'react-image-gallery';
const ImageGallery = Gallery.default ? Gallery.default : Gallery;

```

**Comment by xiaolin** [comment]
Looks like it is, ill create a ticket to one day support both builds. If someone wants to open a PR for it would be great too.
