### ISSUE TITLE
Can we have the state isFullscreen as property?

### ISSUE THREAD

**Issue by robinschuere** [xiaolin/react-image-gallery#769]
**Is your feature request related to a problem? Please describe.**
I am frustrated that I cannot start the component in fullscreen mode

**Describe the solution you'd like**
have a property `isFullscreen` that I can call to set the initial mode of the component to fullscreen

**Describe alternatives you've considered**
other packages tbh

**Additional context**
none

**Comment by gGerz** [comment]
Hi! You can start it like this)
`
const galleryRef = useRef();

  useEffect(() => {
    galleryRef.current.toggleFullScreen();
  }, []);
`

**Comment by robinschuere** [comment]
Hey, I also found this workaround and am using it for now, although I'm not convinced it is a good approach to start a component with a useEffect.

**Comment by xiaolin** [comment]
Completely normal to start a component with `useEffect`!
