### ISSUE TITLE
Request new feature - Scrollable image view

### ISSUE THREAD

**Issue by NiceDay608088** [xiaolin/react-image-gallery#777]
**Is your feature request related to a problem? Please describe.**
Could you implement new feature to make image view scrollable when scrolling mouse, and show current image and part of next image in the image view panel?

**Describe the solution you'd like**
Please refer to sample in image mentioned in  https://stackoverflow.com/questions/77388113/react-css-image-viewer

**Comment by xiaolin** [comment]
You can use JS & CSS to accomplish your task above.
