### ISSUE TITLE
can you show an example of using renderItem? 

### ISSUE THREAD

**Issue by booboothefool** [xiaolin/react-image-gallery#781]
The library works great for me for the most part. I am using it with NextJS. However I would l like to render videos/sound clip as well, so am trying to use `renderItem`. 

I assume it's simply used like:
```
renderItem: () => <div>hello</div>
```

but this does not clearly show up like all the default images do. It seems it is out of position/skewed, but I am not using any weird styles.

**Comment by xiaolin** [comment]
Your rendered item needs to have some container width height.

Try something like

`renderItem: () => <div style={{width: "400px", height: "400px"}}>hello</div>`
