### ISSUE TITLE
add circular border over forward and backward slider

### ISSUE THREAD

**Issue by duser77** [xiaolin/react-image-gallery#787]
above explained
![forward arr](https://github.com/xiaolin/react-image-gallery/assets/134565424/caecf586-ecc6-4a95-b541-7de539869a71)
![forward](https://github.com/xiaolin/react-image-gallery/assets/134565424/540ac369-23bd-4e33-a265-db6b8c710109)

**Comment by duser77** [comment]
and make it smaller

**Comment by dancielos** [comment]
Or you can also use additionalClass property to design your nav. For instance:

in the App.jsx:
`<ImageGallery 
... 
additionalClass={"extra-class"}
/>
`

in your css file:
`.extra-class .image-gallery-left-nav {
  padding: 0;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background-color: #fff;
}

.extra-class .image-gallery-left-nav .image-gallery-svg {
  stroke-width: 2px;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  height: auto;
  width: 14px;
  color: #000;
}`

The disadvantage of this approach is you can't change the icon svg itself, but it's doable.
