### ISSUE TITLE
many deprecation warnings 

### ISSUE THREAD

**Issue by flyon** [xiaolin/react-image-gallery#79]
Im using react 15.3.0:

```Warning: You are manually calling a React.PropTypes validation function for the `items` prop on `ImageGallery`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.```

and many more, all about manually calling PropTypes

**Comment by xiaolin** [comment]
Thanks for bringing it up, I will take a look soon.

**Comment by xiaolin** [comment]
@flyon I'm not seeing anything wrong on my end. Are you calling PropTypes? see https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by flyon** [comment]
No I'm not doing anything with proptypes, but all the proptype warnings come up when I insert the ImageGallery from this library. Also, my mistake, I'm using react 0.14.3, not 15.3.0.

**Comment by xiaolin** [comment]
I'm not able to replicate this issue. I've tried both `0.14.3` and `15.3.0` and they're fine. Are you using a boilerplate? How are you inserting `ImageGallery`?

**Comment by xiaolin** [comment]
closing this.
