### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by sanjay-spinx** [xiaolin/react-image-gallery#798]
**Checklist before opening an issue**\
Lots of issues are opened that are unrelated to this package, please take a moment to ensure the issue is not on your end 🙏.
- [ ] Did you try google?
- [ ] Did you search for previous Issues in this repo?

**Describe the bug**\

**Image Gallery Version**\
What version of `react-image-gallery` are you using?

**To Reproduce**\

**Expected behavior**\

**Screenshots**\

**Client info (please complete the following information):**\
 - Browser: [e.g. chrome, safari]

**Additional context**\

**Comment by AnthonyGress** [comment]
If you're using next js, make it a client component
