### ISSUE TITLE
arrow key should work only if the component is focused

### ISSUE THREAD

**Issue by BesatZardosht** [xiaolin/react-image-gallery#80]
Thanks for amazing component!
being able to use arrow keys to change slides is great however, it should be disable if the component is not focused.

**Comment by xiaolin** [comment]
That might not always be desired. If you are running into conflicts with `keydown` events you can add a wrapper to `ImageGallery`, see below. 

```javascript
  _enableArrowKeys() {
    this.setState({disableArrowKeys: false});
  }

  _disableArrowKeys() {
    this.setState({disableArrowKeys: true});
  }


render() {
  return (
    <div
      onMouseOver={this._enableArrowKeys.bind(this)}
      onMouseLeave={this._disableArrowKeys.bind(this)}
    >
      <ImageGallery disableArrowKeys={this.state.disableArrowKeys}/>
    </div>
  );
}
```

**Note**: Toggling `disableArrowKeys` was just release and only works on `0.6.8`

**Comment by xiaolin** [comment]
Closing this as a wontfix, feel free to reopen if you have any questions.
