### ISSUE TITLE
Bug mobile fullscreen 

### ISSUE THREAD

**Issue by luis27diego** [xiaolin/react-image-gallery#800]
Issue Title: Custom CSS Not Applied to Center Image in Fullscreen on Mobile Devices

Description:

Hello,

I'm trying to apply custom CSS to my gallery component, specifically to center the image when it is in fullscreen mode on mobile devices. However, the custom CSS doesn't seem to be applied.

Details:

    I'm using the react-image-gallery component in my project.
    I've tried modifying the CSS directly to center the image in fullscreen mode, but the changes are not reflected.
    The specific CSS class I’m targeting is .image-gallery image-gallery-using-mouse.
    The issue occurs on mobile devices when the gallery is viewed in fullscreen mode.
    I'm working within a Docusaurus project, which might be influencing how CSS is applied.

Steps to Reproduce:

    Create a Galeria component that wraps react-image-gallery.
    Apply custom CSS to center the image in fullscreen mode on mobile devices.
    Observe that the custom styles are not applied as expected.

**Comment by xiaolin** [comment]
This looks to be an issue that is not related to this lib. Maybe something in Galeria doc on how to override css.
