### ISSUE TITLE
Thumbnails should scroll vertically too.

### ISSUE THREAD

**Issue by sylvesteraswin** [xiaolin/react-image-gallery#81]
Right now I see you have only translateX.

I am using this plugin and I have requirement where I need to translateY.

Would you be kind enough to implement this feature :)

**Comment by xiaolin** [comment]
take a look at #74. You should be able to do this using css.

**Comment by xiaolin** [comment]
Were you able to figure it out @sylvesteraswin ?

**Comment by sylvesteraswin** [comment]
First I made it work with CSS, but the problem was the thumbnails transform was X axis only so if I have many images it wouldn't move, so I had a hack it using the onSlide function to recalculate the transform position for Y axis  and changed it :)

**Comment by xiaolin** [comment]
Interesting,  did you try using css rotate? I thought that might work since you can rotate the whole thumbnail container and its thumbnails and have it still slide.

Since this does not seem easy, I will see if I can find some time to actually add this as a property feature.

**Comment by harrington101** [comment]
I agree, this would be a good feature but can you make it so that it can be vertical on large screens and horizontal on small screens?

**Comment by sylvesteraswin** [comment]
@xiaolin Using CSS transform and rotating will not work, since you are always calculating the width from the X axis and it looked too hacking to do anything with CSS.

Good you provided the onSlide helper function :)

You should create a config. I will see if I can find time and send a pull request for this feature 💃

**Comment by xiaolin** [comment]
Ideally we can turn this on as a prop like `thumbnailBarLocation={'left'}` If I have time I will try to get to this if no one opens a PR.

**Comment by akuji1993** [comment]
@xiaolin I need exactly this `thumbnailBarLocation={'left'}`. Did you get a chance to implement this, yet?

**Comment by sylvesteraswin** [comment]
@akuji1993 I worked on a separate project to accomodate this feature and many more inspired from this library. Have a look at this repo https://github.com/sylvesteraswin/react-gallery-swiper

**Comment by xiaolin** [comment]
@akuji1993 @sylvesteraswin I was able to finish off what I had on a feature branch, `v0.7.6` includes the functionality to set `thumbnailPosition` as a prop.

I've also updated the readme, and [demo page](http://linxtion.com/demo/react-image-gallery/)

Let me know if you guys have any questions.

**Comment by akuji1993** [comment]
Very cool, thank you for replying so quickly. I'll check both of your solutions out. Happy new year.

**Comment by akuji1993** [comment]
If you could update npm also, that'd be great. I see it as latest version is 0.7.6 right now.

**Comment by xiaolin** [comment]
FYI, missing default `thumbnailPosition` in `0.7.7` not an issue if you set it, but I've bump the version to `0.7.8` setting a default `thumbnailPosition`

**Comment by akuji1993** [comment]
Was indeed working perfectly, still thanks for the reminder, upgraded my project to 0.7.8. Thanks.

**Comment by akuji1993** [comment]
I believe, you can close this issue, too. It should be resolved with that change.
