### ISSUE TITLE
thumbnail container width < 100% 

### ISSUE THREAD

**Issue by psimyn** [xiaolin/react-image-gallery#82]
Trying to get the navigation arrows at the bottom (on either side of the thumbnails). Positioning them works, but it means the thumbnails at the end get covered by the arrows.

Due to thumbnail translateX using galleryWidth instead of thumbnailContainer width - probably same fix as for https://github.com/xiaolin/react-image-gallery/issues/76

**Comment by xiaolin** [comment]
The navigation arrows are absolutely positioned, you can manipulate them more towards the left or right using negative values.

#76 is asking for the ability to navigate through thumnails, I don't think its the same as your issue.

![screen shot 2016-08-24 at 6 30 16 pm](https://cloud.githubusercontent.com/assets/1286776/17950386/eee9d4d2-6a28-11e6-90b2-93f537edcf08.png)

**Comment by psimyn** [comment]
Close, but I wanted the arrows inside the container. This image shows the problem, the left and right-most images and covered

![image](https://cloud.githubusercontent.com/assets/1731922/17951478/b2556234-6aa5-11e6-8d34-25dd1c418c40.png)

**Comment by xiaolin** [comment]
@psimyn released `0.6.10` which makes thumbnails adjust based on its own width,and not the containers width.

**Comment by psimyn** [comment]
:tada: Thanks! change you made was identical to our own fork!
