### ISSUE TITLE
How to use the renderItem prop?

### ISSUE THREAD

**Issue by vldolot** [xiaolin/react-image-gallery#83]
Hi, first of all, thanks for a neat image carousel/gallery react component.

This is not really an issue but rather a question on how to use the **`renderItem`** prop.
What I would like to do is to modify the content of the item.description to have some links into it.

Appreciate your response to this.

Thanks!

**Comment by xiaolin** [comment]
The example (untested) below should get you started.

```javascript
class MyComponent extends React.Component {

  _handleImageError(event) {
    if (this.props.defaultImage &&
        event.target.src.indexOf(this.props.defaultImage) === -1) {
      event.target.src = this.props.defaultImage;
    }
  }

  _myImageGalleryRenderer(item) {
    // your own image error handling
    const onImageError = this._handleImageError

    return (
      <div className='image-gallery-image'>
        <img
            src={item.original}
            alt={item.originalAlt}
            srcSet={item.srcSet}
            sizes={item.sizes}
            onLoad={this.props.onImageLoad}
            onError={onImageError.bind(this)}
        />
        {
          item.link && item.linkLabel &&
            <a className='my-own-class' href={item.link}>
              {item.linkLabel}
            </a>
        }
      </div>
    )
  }

  render() {
    const items = [
     {
        original: `example.jpg`,
        thumbnail: `example_thumb.jpg`,
        link: 'http://example.com',
        linkLabel: 'click me'
      }
    ]

    <div>
      <ImageGallery items={} renderItem={this._myImageGalleryRenderer}/>
    </div>
  }
}
```

**Comment by vldolot** [comment]
Great! It works! So, the only missing piece of code on my part was the `.bind(this)`. Thank you so much.

**Comment by sag1v** [comment]
@xiaolin Nice project! i was following your snippet example here of implementing `renderItem` and it's working nice except one thing that took me a while to figure out.
You are not passing `this.props.defaultImage` to `ImageGallery` and that would lead to a default image in the gallery but an empty image in the thumbnail if the `src` link is broken.
So it should be:
`<ImageGallery items={items} renderItem={this._myImageGalleryRenderer.bind(this)} defaultImage={this.props.defaultImage}/>`
Or maybe even spread the entire props object just in case:
`<ImageGallery items={items} renderItem={this._myImageGalleryRenderer.bind(this)} {...this.props}/>`
Maybe consider to update and fix your example so others won't waste time figure it out like i did.
