### ISSUE TITLE
Referencing Vidoe and Audio file

### ISSUE THREAD

**Issue by samquarm** [xiaolin/react-image-gallery#84]
First of all, this is an amazing react solution.

Is it possible to reference video and Audio files. If not is there flexibility to customize this plugin to handle vidoe and audio files.

Thank you.

**Comment by xiaolin** [comment]
see #83 you have the ability to override how a slide can be rendered. In there you should be able to put your video, and audio files.

**Comment by xiaolin** [comment]
Were you able to figure it out? @samquarm

**Comment by xiaolin** [comment]
@samquarm I've updated the demo, and `example/app.js` to show an how to implement videos in between slides.

**Comment by xiaolin** [comment]
Closing this.
