### ISSUE TITLE
Incorrect attribute name in readme

### ISSUE THREAD

**Issue by steplerbox** [xiaolin/react-image-gallery#85]
size: 'Optional size (image size relative to the breakpoint)'

I think, it should be 'sizes'

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Example_4_Using_the_srcset_and_sizes_attributes

**Comment by xiaolin** [comment]
Yes you are right.

**Comment by steplerbox** [comment]
So, I close it :)
