### ISSUE TITLE
Fullscreen not working in iphone

### ISSUE THREAD

**Issue by dientuki** [xiaolin/react-image-gallery#86]
Hi, the fullscreen option it's not working in iphone (safari and android). It's seen is an implementation issue http://caniuse.com/#feat=fullscreen, however, there are a jquery gallery who use a fullscreen mode http://dimsemenov.com/plugins/royal-slider/gallery/ (it's not 100% fullscreen, but it's something)

**Comment by xiaolin** [comment]
@dientuki mobile full screen should now work in v0.7.0
