### ISSUE TITLE
Add lazyload to thumbnails

### ISSUE THREAD

**Issue by vladop** [xiaolin/react-image-gallery#88]
I set lazyload  property but doesn't effect anything

**Comment by xiaolin** [comment]
What version are you on? And what is not working?

**Comment by imperat0r** [comment]
It seems thumbnail images are not lazyloaded. When there are  100 images that is 100 requests for thumbnails. Maybe would be solution to load only images that should be visible at some point. I made performance little better by adding this code when thumbnails array is created. (Not great when startIndex bigger than 1 ,but helps in my situation.
                    var currentIndex=this.state.currentIndex;
                      index-currentIndex<8 ;
                  if (this.props.lazyLoad) {
                     if (alignment || index-currentIndex<8) {
                        thumbnails.push(thumbnailHtml);
                    }
                    } else {

                  thumbnails.push(thumbnailHtml);
                    }

Instead of pushing every thumbnail to thumbnails array I only push first 8  images whose index is greater than currentIndex. It helps in my situation(no infinite scrool, firstIndex is 1)

**Comment by xiaolin** [comment]
Ah, yes. This was mainly the reason I left out lazyLoads on thumbnails.

I'll revisit when I get a chance to see if I can come up with a solution that supports `infiniteScroll` and `startIndex`

**Comment by mikkom** [comment]
@kamui Could you show an example how exactly you're using react-lazyload with react-image-gallery? If I just disable lazyLoad prop in react-image-gallery component and wrap it with <LazyLoad> then all images are still loaded on the first page load.

**Comment by xiaolin** [comment]
@kamui I would like to avoid the extra dependency since lazy loading slides are working. Adding a lazy load to the thumbnails shouldn't be too bad.

**Comment by kamui** [comment]
@mikkom You're right, I forgot in my case I was using this library for lazy loading above the fold. That's what the library does, so it wont help with thumbnails anyhow. Sorry about that.

**Comment by xiaolin** [comment]
No updates on this so far. If you need lazy loading for thumbnails I suggest implementing a solution where you conditionally add more images to the gallery based on your gallery needs.

e.g.

```jsx
// untested
const allMyImages = [{},{},N...];
const maxImagesToLoad = 5;
state = {
  items: allMyImages.splice(0, maxImagesToLoad); // load 5 at a time.
};
loadMore = () => {
  this.setState({
     items: [
       ...this.state.items,
       ...allMyImages.splice(0,maxImagesToLoad), // add the next 5 images.
     ]
  });
};
onSlide = (nextIndex) => {
  if (this.state.items.length - nextIndex <= 3) { // if we're 3 or less away from the last slide load more 
    this.loadMore();
  }
};
render  {
  <ImageGallery items={this.state.items} onSlide={this.onSlide} />
}
```

**Comment by tpinne** [comment]
We currently implement custom `renderThumbInner` function and render the html from the original source code but add the `loading="lazy"` attribute, which gets more and more implemented in browsers and doesn't hurt the ones who don't understand it.

So we gradually getting the benefit in the future without doing anything. But it would be great if this attribute would be rendered by this lib to not have to overwrite this function for this basic little snippet.
