### ISSUE TITLE
Video plays even after slide is change

### ISSUE THREAD

**Issue by AshvinkumarPatel** [xiaolin/react-image-gallery#92]
This is really great plugin along with video in gallery.

I have seen one issue in video.

Step 1: Reach slide where we have video
Step 2: Click to play video
Step 3: Slide the gallery to next or previous
Step 4: Video which we played in step2 still plays. It should stop playing when we change slide.

Thanks,
Ashvinkumar

**Comment by xiaolin** [comment]
The video demo was meant to be an example of what you can do with `renderItem`. Its not part of the library.

To fix your issue you can pass in your own `onSlide` function into the gallery and turn off the video when a slide event occurs.

**Comment by AshvinkumarPatel** [comment]
Thanks for your guidance in that.
