### ISSUE TITLE
Play and Full Screen buttons are not creating

### ISSUE THREAD

**Issue by AshvinkumarPatel** [xiaolin/react-image-gallery#94]
Hello,

Facing an issue in full screen and play options in gallery. PFA screenshot in which I have shows markups are not generating same which is generating in sample-gallery.

In my issue-facing-gallery.png, you can see it is not generating "image-gallery-slide-wrapper" as well as full screen button and play gallery button.

Could you please guide me if I have missing anything?

![sample-gallery](https://cloud.githubusercontent.com/assets/12441443/18496419/4f1c0cce-7a43-11e6-916a-7cb16ae4a475.jpg)
![issue-facing-gallery](https://cloud.githubusercontent.com/assets/12441443/18496420/4f1cf440-7a43-11e6-8cf5-09c114df867f.png)

**Comment by xiaolin** [comment]
What version of the library are you using? You might be using an older version.

**Comment by AshvinkumarPatel** [comment]
There was no issue in plugin. I was using the older version 0.6, I have just tool latest and it solved my issue. Hence closing issue.
