### ISSUE TITLE
Full Screen Width

### ISSUE THREAD

**Issue by AshvinkumarPatel** [xiaolin/react-image-gallery#95]
Is there any way to occupy full width of screen on click of full screen button?

**Comment by xiaolin** [comment]
@AshvinkumarPatel There are many ways to do this. Full screen should respect the width of your browser. If the gallery is not set to 100% then the full screen will not be set to 100% either.

**Comment by xiaolin** [comment]
Please take a moment and research your questions, if you cannot find the answer, and its related to the library feel free to open an issue.
