### ISSUE TITLE
Support for multiple slides to be visible at a time

### ISSUE THREAD

**Issue by nelsieborja** [xiaolin/react-image-gallery#96]
Will u be able to support this soon? Would want to use it on my project.

**Comment by xiaolin** [comment]
You should be able to do this with the custom `renderItem` function.

**Comment by xiaolin** [comment]
@nelsieborja were you able to figure this out?

**Comment by xiaolin** [comment]
Closing this, feel free to open if you have any more questions.

**Comment by kallebornemark** [comment]
@xiaolin I'm trying to figure this out. Want to help?

I'd like it to be able to display N (say 2) images at a time. Something like this:
![image](https://user-images.githubusercontent.com/10062735/33767710-2e562888-dc23-11e7-925d-c5be6d54d4ba.png)

**Comment by xiaolin** [comment]
@kallebornemark Using css will allow you to display 2 images at a time, however the slide function still only slides 1 at a time.

```css
.image-gallery-slide {
  width: 50%;
}
```

**Comment by jorrit** [comment]
This works, however while sliding right, the new slide is blank for a short while. I guess this is because under normal circumstances this slide is not yet visible. Is there anything I can do to make this slide load earlier?

**Comment by xiaolin** [comment]
If you turn off `lazyLoad` all the slides should load.

**Comment by jorrit** [comment]
It still happens for lazyLoad = false. The problem seems to be that the slide is not added soon enough when infinite is on, because of this code:

```
if (this._shouldPushSlideOnInfiniteMode(index)) {
slides.push(slide);
}
```

**Comment by tayloraucoin** [comment]
Is this a feature that is in the pipeline?  If its not I will have to either build my own solution or may consider submitting a PR.  More likely the former than the latter.

**Comment by xiaolin** [comment]
Feel free to open an issue and tag as feature. If there is enough interest I can work on it during some downtime.
